### ISSUE TITLE
Java backend crashes when rewriting a variable of sort Id

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#101]
Command to reproduce the crash:
krun --term Id.imp --backend java --search -depth 1

Id.imp contains the following initial configuration pattern:
<k>X:Id</k><state> n |-> 0 </state>

And the exception thrown:
[2states, 1steps, 54.05 ms]
Exception in thread "main" java.lang.ClassCastException: org.kframework.kil.KApp cannot be cast to org.kframework.backend.java.kil.Term
    at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:416)
    at org.kframework.backend.java.kil.MapLookup.accept(MapLookup.java:89)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTranslation.transform(BackendJavaKILtoKILTranslation.java:53)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTranslation.transform(BackendJavaKILtoKILTranslation.java:66)
    at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:124)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTranslation.transform(BackendJavaKILtoKILTranslation.java:53)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTranslation.transform(BackendJavaKILtoKILTranslation.java:66)
    at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:124)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTranslation.transform(BackendJavaKILtoKILTranslation.java:53)
    at org.kframework.backend.java.kil.Cell.accept(Cell.java:92)
    at org.kframework.backend.java.symbolic.JavaSymbolicKRun.search(JavaSymbolicKRun.java:203)
    at org.kframework.krun.Main.normalExecution(Main.java:296)
    at org.kframework.krun.Main.execute_Krun(Main.java:1142)
    at org.kframework.main.Main.main(Main.java:59)

**Comment by yilongli** [comment]
The reason is that the Java implementation of the builtin MapLookup operation cannot handle the case where the key is a variable. Therefore X:Id is simply rewritten to '_|->_(Id(#"n"),, Int(#"0"))[X:Id], which causes the ClassCastException in the BackendJavaKILtoKILTranslation.

What I would like to see is that X:Id being bound to Id(#"n") and then rewritten to Int(#"0").

**Comment by yilongli** [comment]
Since I have already implemented narrowing on symbolic map lookup, I am closing this issue.
