### ISSUE TITLE
krun --search on windows throws IOException

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/k-legacy#102]
krun --search exercises/exercise_1/programs_and_results/break-from-exception.simple

Result:
Configuration is displayed correctly, followed by:

java.io.IOException: E:\work\k-framework\dist\tutorial\2_languages\1_simple\1_untyped.k\krun8442818777350805300 was not successfully renamed to E:\work\k-framework\dist\tutorial\2_languages\1_simple\1_untyped.k\krun
        at org.kframework.krun.FileUtil.renameFolder(FileUtil.java:154)
        at org.kframework.krun.Main$1.run(Main.java:727)

Platform: Windows. Works on Linux.

Solution:
I will replace Java 1.0 rename api call with the more informative Java 1.7 one, to gather more debug information.

**Comment by denis-bogdanas** [comment]
The problem is caused by the call of method files.move, or whatever alternative, inside a shutdown hook. Looks like windows don't allow file operations in a shutdown hook. But shutdown hook is "required" because of the abuse of calls to System.exit within the project.

A simple solution to this would be to wrap System.exit(code) calls into something like K.exit(code) that does the following:
1. Executes the shutdown hook as regular code.
2. Calls System.exit(code).
