### ISSUE TITLE
Assertion Error when syntax module is not included in the main module

### ISSUE THREAD

**Issue by traiansf** [kframework/k-legacy#104]
Maybe it is a rare case, but it just happened to me while I was trying to create a simple test.

Take a definition, where syntax is in a separate module.

I would assume here that we talk about IMP, although it possibly happens everywhere

replace module IMP with the following module

```
module IMP
  configuration <k> $PGM:Pgm </k>
endmodule
```

kompile works without complaints (although it probably shouldn't, as we refer to Pgm which is not defined.

krun example.imp crashes badly:
Exception in thread "main" java.lang.AssertionError
        at org.kframework.kil.TermCons.<init>(TermCons.java:34)
        at org.kframework.kil.loader.JavaClassesFactory.getTerm(JavaClassesFactory.java:76)
        at org.kframework.parser.ProgramLoader.loadPgmAst(ProgramLoader.java:69)
        at org.kframework.parser.ProgramLoader.loadPgmAst(ProgramLoader.java:85)
        at org.kframework.parser.ProgramLoader.processPgm(ProgramLoader.java:138)
        at org.kframework.krun.RunProcess.runParser(RunProcess.java:119)
        at org.kframework.krun.RunProcess.runParserOrDie(RunProcess.java:96)
        at org.kframework.krun.Main.execute_Krun(Main.java:1129)
        at org.kframework.main.Main.main(Main.java:59)

I assume some additional checks should be done at parsing time.

**Comment by radumereuta** [comment]
Since syntax modules are now collected recursively starting from the main module, this is not an issue anymore.
