### ISSUE TITLE
map lookup doesn't work

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#1080]
If I have the following definition:

```
module TEST

     configuration <k> $PGM:K </k><map>.Map</map>
     syntax KItem ::= "start" | "abc"
     rule <k>start => abc ...</k>
      <map>... (.Map => ("a" |-> 1)) ...</map>

     rule <k> abc => M["a"] </k>
      <map>M:Map</map>
endmodule
```

If I run the program start, the java backend will give me the error as:

```
[Error] Internal: Uncaught exception thrown of type ClassCastException.
Please file a bug report at https://github.com/kframework/k/issues

```

If I have the following definition:

```
module TEST

     configuration <k> $PGM:K </k><map>.Map</map>
     syntax KItem ::= "start" | "abc" | map(Int)
     rule <k>start => abc ...</k>
      <map>... (.Map => ("a" |-> map(2)) ("b" |-> map(1)) ("c" |-> map(2)) ("d" |-> map(2))) ...</map>

     rule <k> abc => M["a"] </k>
      <map>M:Map</map>
endmodule
```

Then, I run the program start, I will get the following bug from Java backend:

```
java.lang.UnsupportedOperationException: missing SMTLib translation for 'map
    at org.kframework.backend.java.symbolic.KILtoSMTLib.transform(KILtoSMTLib.java:383)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:573)
    at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:120)
    at org.kframework.backend.java.kil.KItemProjection.accept(KItemProjection.java:102)
    at org.kframework.backend.java.symbolic.KILtoSMTLib.transform(KILtoSMTLib.java:340)
    at org.kframework.backend.java.symbolic.SymbolicConstraint.accept(SymbolicConstraint.java:1139)
    at org.kframework.backend.java.symbolic.KILtoSMTLib.translateConstraint(KILtoSMTLib.java:138)
    at org.kframework.backend.java.symbolic.SymbolicConstraint$SymbolicConstraintOperations.checkUnsat(SymbolicConstraint.java:238)
    at org.kframework.backend.java.symbolic.SymbolicConstraint.checkUnsat(SymbolicConstraint.java:498)
    at org.kframework.backend.java.kil.ConstrainedTerm.unify(ConstrainedTerm.java:208)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.computeRewriteStep(SymbolicRewriter.java:125)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.rewrite(SymbolicRewriter.java:65)
    at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaKILRun(JavaSymbolicExecutor.java:89)
    at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.internalRun(JavaSymbolicExecutor.java:68)
    at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:64)
    at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:151)
    at org.kframework.krun.tools.Executor$Tool.run(Executor.java:103)
    at org.kframework.krun.tools.Executor$Tool.run(Executor.java:72)
    at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
    at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:70)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:44)
    at org.kframework.main.Main.main(Main.java:40)
<k>
    abc ~> _42:K
</k>
<map>
    "a" |-> map ( 2 )
    "b" |-> map ( 1 )
    "c" |-> map ( 2 )
    "d" |-> map ( 2 )
</map>

```

Basically, if I remove the map lookup operator from the above definitions, the programs can run finely. Once I add the map lookup operator, they will not work.

**Comment by yilongli** [comment]
The problem is that smt solver is called even the user is just trying to execute the programs using the unification-based rewriter. I think smt solver should only be called if krun option `--prove` is given. You can specify `--smt none` or `--pattern-matching` option to bypass this problem for now.

**Comment by yilongli** [comment]
BTW, during debugging, I see `M["a"]` in the rule being translated to `projection(Map:lookup(_4:Map,, String(#""a"")))`, which later becomes `projection(Int(#"1")` in execution. It looks like a bug in `AddInjections` pass, what do you think ? @andreistefanescu

**Comment by liyili2** [comment]
I try these two definitions. It works only if I specify both --smt none and --pattern-matching as:

```
krun a.test --smt none --pattern-matching
```

**Comment by andreistefanescu** [comment]
This is a bug in the AddInjections pass. I'm not sure if it is worth fixing
at this point, since we are planning to switch to the new KORE/KAST soon.

Andrei
