### ISSUE TITLE
Cannot define a function to get a the value list of a map

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#1088]
If I have the following definition:

```
module TEST

     syntax List ::= theValues(Map) [function]

     rule theValues(.Map) => .List
     rule theValues((_:K |-> A:K) M:Map) => A theValues(M)
endmodule
```

If I compile the definition in java backend as:

```
kompile test.k --backend java
```

I will get the following error:

```
[Error] Internal: Uncaught exception thrown of type AssertionError.
Please file a bug report at https://github.com/kframework/k/issues
```

**Comment by andreistefanescu** [comment]
Can you use `values(Map)`, as defined in map.k?

**Comment by liyili2** [comment]
Yes. The problem is that I want to define the values function to test the builtin values function.

**Comment by yilongli** [comment]
This rule is problematic: `rule theValues((_:K |-> A:K) M:Map) => A theValues(M)`
Change `A` to `ListItem(A)` on the right-hand side.

**Comment by yilongli** [comment]
@dwightguth I need some help here. How can I call the `KExceptionManager` from `BuiltinList.Builder`. Here is the complete stack trace:

```
java.lang.AssertionError: unexpected sort K of concatenated term A:K; expected List
    at org.kframework.backend.java.kil.BuiltinList$Builder.concatenate(BuiltinList.java:415)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:341)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:1)
    at org.kframework.kil.ListBuiltin.accept(ListBuiltin.java:87)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:468)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:1)
    at org.kframework.kil.Rule.accept(Rule.java:63)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:602)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:1)
    at org.kframework.kil.Definition.accept(Definition.java:166)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transformDefinition(KILtoBackendJavaKILTransformer.java:110)
    at org.kframework.backend.java.symbolic.JavaSymbolicBackend.lastStep(JavaSymbolicBackend.java:70)
    at org.kframework.backend.LastStep.compile(LastStep.java:21)
    at org.kframework.backend.LastStep.compile(LastStep.java:10)
    at org.kframework.compile.utils.CompilerSteps.compile(CompilerSteps.java:44)
    at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:118)
    at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:88)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:43)
    at org.kframework.main.Main.main(Main.java:40)
[Error] Internal: Uncaught exception thrown of type AssertionError.
Please file a bug report at https://github.com/kframework/k/issues
```

**Comment by dwightguth** [comment]
Do you need to throw an error? If so, go ahead and use GlobalSettings.kem
and I will refactor it later in my own pull request. If you want to create
a warning then it will be a little more complex though.
