### ISSUE TITLE
problem with maude backend and java backend

### ISSUE THREAD

**Issue by nwpuzhangfan** [kframework/k-legacy#1103]
I change the maude backend to java backend, original K file can both kompiled by maude and java backend, but only krun with maude backend ok, and when change to java backend, krun report the error message below:

Exception in thread "main" java.lang.AssertionError: The greatest lower bound (GLB) of sorts [ArrayElementImplList, PpeListValue, UnitsList, BooleanTerm]doesn't exist!

at org.kframework.backend.java.kil.KItem.<init>(KItem.java:190)
at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:159)
......
at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transformTerm(KILtoBackendJavaKILTransformer.java:128)
at org.kframework.backend.java.kil.Term.of(Term.java:49)
at org.kframework.backend.java.symbolic.JavaSymbolicKRun.javaKILRun(JavaSymbolicKRun.java:97)
at org.kframework.backend.java.symbolic.JavaSymbolicKRun.internalRun(JavaSymbolicKRun.java:82)
at org.kframework.backend.java.symbolic.JavaSymbolicKRun.run(JavaSymbolicKRun.java:77)
at org.kframework.krun.Main.normalExecution(Main.java:370)
at org.kframework.krun.Main.execute_Krun(Main.java:1452)
at org.kframework.main.Main.main(Main.java:64)
I think It's must be some different with maude and java backend, but currently I can't solve this problem.

**Comment by yilongli** [comment]
According to the assertion error, you have a `KItem` which could have sort ArrayElementImplList, PpeListValue, UnitsList, and/or BooleanTerm. However, these 4 sorts have no GLB. The Java backend couldn't decide a sort for your `KItem` in this case.

**Comment by dlucanu** [comment]
IMHO, this is a parsing problem and it shouldn't depend on the backend.

**Comment by radumereuta** [comment]
I can parse even if there is no GLB for a term.
I think the error is thrown because of overlapping klabels which should be different. I manage to parse ok because I have enough context to disambiguate properly, but the backend does this differently. I'm not sure if this is exactly the case. I would need more details about the definition.

**Comment by nwpuzhangfan** [comment]
ok, I try to eliminate all ambiguty first. after that, we can make the error message more clear in detail.

Radu Mereuta notifications@github.com编写：

**Comment by nwpuzhangfan** [comment]
Finally, I found the why the error occurs. AADL standard syntax have lots of overlap, so cause the ambiguty, and my team spent lot of time to eliminate the overlap in definition, and it works now:)
