### ISSUE TITLE
better error message for "[Error] Internal: Failed to localize JSGLR to a thread"

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1143]
I was trying to prove `avl_tree.cil.c` w.r.t `avl_tree_spec.k`. I started krun from eclipse and didn't increase the default stacksize of JVM. Then I got the following message:

```
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.kframework.parser.concrete.DefinitionLocalKParser.invokeReflective(DefinitionLocalKParser.java:73)
    at org.kframework.parser.concrete.DefinitionLocalKParser.ParseProgramString(DefinitionLocalKParser.java:113)
    at org.kframework.parser.ProgramLoader.loadPgmAst(ProgramLoader.java:79)
    at org.kframework.parser.ProgramLoader.loadPgmAst(ProgramLoader.java:99)
    at org.kframework.parser.ProgramLoader.processPgm(ProgramLoader.java:177)
    at org.kframework.krun.RunProcess.runParser(RunProcess.java:130)
    at org.kframework.krun.InitialConfigurationProvider.get(InitialConfigurationProvider.java:84)
    at org.kframework.krun.InitialConfigurationProvider.get(InitialConfigurationProvider.java:1)
    at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
    at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:73)
    at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
    at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:63)
    at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1053)
    at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
    at com.google.inject.Scopes$1$1.get(Scopes.java:65)
    at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
    at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
    at com.google.inject.internal.ExposedKeyFactory.get(ExposedKeyFactory.java:54)
    at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
    at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
    at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:279)
    at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
    at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
    at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:279)
    at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1000)
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1053)
    at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:996)
    at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:93)
    at com.google.inject.throwingproviders.ThrowingProviderBinder$SecondaryBinder$3.get(ThrowingProviderBinder.java:293)
    at com.google.inject.throwingproviders.ThrowingProviderBinder$SecondaryBinder$3.get(ThrowingProviderBinder.java:290)
    at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
    at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
    at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1000)
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1046)
    at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:996)
    at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:93)
    at com.google.inject.throwingproviders.ThrowingProviderBinder$SecondaryBinder$2$1.invoke(ThrowingProviderBinder.java:276)
    at com.sun.proxy.$Proxy9.get(Unknown Source)
    at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:69)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:43)
    at org.kframework.main.Main.main(Main.java:40)
Caused by: java.lang.RuntimeException: java.lang.StackOverflowError
    at org.strategoxt.lang.StackSaver.invokeStackFriendly(StackSaver.java:79)
    at org.strategoxt.lang.Context.invokeStrategyCLI(Context.java:178)
    at org.kframework.parser.concrete.KParser.ParseProgramString(KParser.java:305)
    ... 52 more
Caused by: java.lang.StackOverflowError
    at org.spoofax.jsglr.client.ParseNode.isParseProductionChain(ParseNode.java:135)
    at org.spoofax.jsglr.client.imploder.TreeBuilder.buildTreeNode(TreeBuilder.java:230)
    at org.spoofax.jsglr.client.ParseNode.toTreeTopdown(ParseNode.java:218)
    at org.spoofax.jsglr.client.imploder.TreeBuilder.buildTreeNode(TreeBuilder.java:234)
    at org.spoofax.jsglr.client.ParseNode.toTreeTopdown(ParseNode.java:218)

        ... omitted a lot more ...

    at org.spoofax.jsglr.client.ParseNode.toTreeTopdown(ParseNode.java:218)
    at org.spoofax.jsglr.client.imploder.TreeBuilder.buildTreeNode(TreeBuilder.java:234)
[Error] Internal: Failed to localize JSGLR to a thread
Aborted at
    javaParseStringPgm_0_0
    parse_string_1_2
    parse_string_1_3
    jsglr_parse_string_1_3
```

At first I thought it was some weird parsing error causing infinite loop, and it took me an hour trying to delta-debug and isolate the root cause. Finally I realized it's due to insufficient stack size.

Another weird thing is that although `avl_tree.cil.c` is a pretty long program, 80% of the code are commented out. It seems that the commented code actually affect the stack size used by the parser because after I remove some commented code, I don't have to increase the JVM stack size. This doesn't look right to me.

@dwightguth @radumereuta any thoughts?

**Comment by radumereuta** [comment]
Well...

```
Aborted at
    javaParseStringPgm_0_0
    parse_string_1_2
    parse_string_1_3
    jsglr_parse_string_1_3
```

Definitely indicates to JSGLR failing to parse somewhere (out of memory of some sort), but I never seen the exception stack before. I think it's related to what @dwightguth did this week.
