### ISSUE TITLE
Fiding executables in non-uniform way causing problems

### ISSUE THREAD

**Issue by osa1** [kframework/k-legacy#1154]
After some of the recent changes in parser my IDE started giving exceptions like this while running kompile:

```
java.io.IOException: Cannot run program "sdf2table.uexe" (in directory "./.kompile-2014-11-04-14-44-17-5adc2fde-7971-470e-8336-8de48510f21a/pgm"): error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at org.kframework.parser.utils.Sdf2Table.run_sdf2table(Sdf2Table.java:34)
    at org.kframework.parser.DefinitionLoader.parseDefinition(DefinitionLoader.java:181)
    at org.kframework.parser.DefinitionLoader.loadDefinition(DefinitionLoader.java:93)
    at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:108)
    at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:87)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:43)
    at org.kframework.main.Main.main(Main.java:40)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 12 more
[Error] Critical: Could not copy
./.kompile-2014-11-04-14-44-17-5adc2fde-7971-470e-8336-8de48510f21a/pgm/Program.tbl
to directory ././lambda-kompiled/.
```

(Note: This is happening without --debug, exceptions are not handled properly in `Sdf2Table`)

Since I'm not running kompile using the shell script provided by the distribution, it can't find required executables.

However, this is handled in ktest. ktest is using `ExecNames` for same thing and it works without requiring setting env variables manually.

I was wondering if we should have a uniform way of handling those. Personally, I don't like setting env variables(especially the PATH) using shell scripts because it's making debugging in IDE harder.

What do you think? I don't see any reasons for parser to not use `ExecNames`.

**Comment by radumereuta** [comment]
I ran into these issues before, so all I can say is that I share the pain.
At the time I just went with what @dwightguth suggested, but it seems to be a reoccurring issue.
Maybe we should rethink how we do this, and take into consideration the most common case. For me setting up an IDE run configuration is far more likely than adding a new executable to the tool.
