### ISSUE TITLE
AssertionError with ListUpdate in baseTerms

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#12]
I need the following rule to compile:

rule MyListItem(1) (MyListItem(3) => .MyList) _:MyList

It currently gives me an assertion error because it finds a ListUpdate in the base terms and it expects either an empty base terms or a variable.

**Comment by traiansf** [comment]
I think it works now.  However the patch was more involved than I thought.

**Comment by dwightguth** [comment]
The above rule works. However, the original rule I was trying to make work had the tags [stdout, stderr]. Consider:

require "builtins/list.k"

module TEST
  imports LIST

  configuration <out stream="stdout"> .MyList </out>

  rule MyListItem(1) (MyListItem(3) => .MyList) _:MyList [stdout]

endmodule

This rule does not work. It throws a ClassCastException.

Exception in thread "main" java.lang.ClassCastException: org.kframework.backend.java.kil.Cell cannot be cast to org.kframework.backend.java.kil.KItem
        at org.kframework.backend.java.kil.Rule.functionKLabel(Rule.java:98)
        at org.kframework.backend.java.kil.Definition.addRule(Definition.java:67)
        at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transform(KILtoBackendJavaKILTransformer.java:475)
        at org.kframework.kil.Definition.accept(Definition.java:121)
        at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transformDefinition(KILtoBackendJavaKILTransformer.java:64)
        at org.kframework.backend.java.symbolic.JavaSymbolicKRun.<init>(JavaSymbolicKRun.java:71)
        at org.kframework.krun.Main.obtainKRun(Main.java:278)
        at org.kframework.krun.Main.normalExecution(Main.java:295)
        at org.kframework.krun.Main.execute_Krun(Main.java:1177)
        at org.kframework.main.Main.main(Main.java:78)

**Comment by traiansf** [comment]
I think I fix it better now.

There was an issue with some code you wrote and how it interacted with some
code Andrei wrote.

An issue was that if no stream cells were found, the rule was still left in
the module.
-    if (generated.isEmpty()) return node;+    if (generated.isEmpty()) {
-            if (result == node)+                return node;
-            GlobalSettings.kem.register(new
  KException(ExceptionType.WARNING, KExceptionGroup.COMPILER,
-                    "Stream cells missing in module " + node.getName() + ". " +
-                            "Some rules tagged with streams have been erased",
-                    node.getFilename(), node.getLocation()));
-            return result;+        }
  Another issue was that when you added the cell on the rules you didn't
  remove the function attribute which was added automatically by Andrei S.
  when a list "constructor" was on top of the lhs.

With Andrei's help I fixed these and some other problems, so I hope you can
get further.

best wishes,
Traian

2013/8/17 dwightguth notifications@github.com
