### ISSUE TITLE
src/README.md issues

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#1309]
I'm following blindly the instructions under src/README.md and I encountered some problems, which I report below.  Please fix ASAP, because in my experience several cs422 students will install from sources.

In github, the first link, to JDK8, is broken (i.e., clicking on it gets you to an error page).  Copying and pasting the URL in browser gets me to a page with trivial instructions on how to install JDK8, but with no JDK8 to download in order to install.  Maybe I'm missing something, but that does not seem to be the right page.  Typing jdk8 in google took to the right place.

Maven section: Not sure whether any specific version of `maven` is needed; I had one installed on my Windows machine, so I just continued.  It would be good to probably also require a certain version of maven if needed.

Git section: It say that you can test it by typing `mvn -version`?  I think that line belongs to the previous section, on Maven.

Install section: It starts with `Checkout this directory in your desired location...`.  You mean `repository` instead of `directory` probably, because the current directory is actually `/src`.  I typed `mvn package` and after 2 min and 22 sec I got the following failure:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.kframework.kore.convertors.TestParserOnKORE
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.075 sec <<< FAILURE!
simpleRuleKORE(org.kframework.kore.convertors.TestParserOnKORE)  Time elapsed: 0.632 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...n(#token(Int,"9")))][
  syntax Exp [location(startLine(#token(Int,"4")),startColumn(#token(Int,"3")),endLine(#token(Int,"4")),endColumn(#toke
(Int,"12")))]
  rule #KRewrite(#token(KVariable,"A") [location(startLine(#token(Int,"1")),startColumn(#token(Int,"1")),endLine(#token
Int,"1")),endColumn(#token(Int,"3")))],#token(KVariable,"B") [location(startLine(#token(Int,"1")),startColumn(#token(In
,"6")),endLine(#token(Int,"1")),endColumn(#token(Int,"7")))]) [location(startLine(#token(Int,"1")),startColumn(#token(I
t,"1")),endLine(#token(Int,"1")),endColumn(#token(Int,"7")))] requires null ensures null [location(startLine(#token(Int
]5")),startColumn(#token(Int,"3")),endLine(#token(Int,"5")),endColumn(#token(Int,"13")))]
endmodule> but was:<...n(#token(Int,"9")))][
  syntax Exp [location(startLine(#token(Int,"4")),startColumn(#token(Int,"3")),endLine(#token(Int,"4")),endColumn(#toke
(Int,"12")))]
  rule #KRewrite(#token(KVariable,"A") [location(startLine(#token(Int,"1")),startColumn(#token(Int,"1")),endLine(#token
Int,"1")),endColumn(#token(Int,"3")))],#token(KVariable,"B") [location(startLine(#token(Int,"1")),startColumn(#token(In
,"6")),endLine(#token(Int,"1")),endColumn(#token(Int,"7")))]) [location(startLine(#token(Int,"1")),startColumn(#token(I
t,"1")),endLine(#token(Int,"1")),endColumn(#token(Int,"7")))] requires null ensures null [location(startLine(#token(Int
"5")),startColumn(#token(Int,"3")),endLine(#token(Int,"5")),endColumn(#token(Int,"13")))]]
endmodule>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.kframework.kore.convertors.BaseTest.testConversion(BaseTest.java:75)
        at org.kframework.kore.convertors.BaseTest.outerOnlyTest(BaseTest.java:34)
        at org.kframework.kore.convertors.TestParserOnKORE.simpleRuleKORE(TestParserOnKORE.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
        at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

(..)ed tests:   simpleRuleKORE(org.kframework.kore.convertors.TestParserOnKORE): expected:<...n(#token(Int,"9")))][

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] K Framework Tool Parent ............................ SUCCESS [  1.746 s]
[INFO] K Framework KORE ................................... SUCCESS [ 48.549 s]
[INFO] K Framework Tool Kernel ............................ SUCCESS [ 33.986 s]
[INFO] K Framework Java Backend ........................... SUCCESS [ 24.808 s]
[INFO] K Framework SDF Backend ............................ SUCCESS [ 30.742 s]
[INFO] K Framework Tool Distribution ...................... FAILURE [  2.253 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:22 min
[INFO] Finished at: 2015-01-24T15:11:17-06:00
[INFO] Final Memory: 50M/650M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project k-d
stribution: There are test failures.
[ERROR]
[ERROR] Please refer to D:\github.grosu-ssh\grosu\k\k-distribution\target\surefire-reports for the individual test resu
ts.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :k-distribution
D:\github.grosu-ssh\grosu\k>
```

**Comment by grosu** [comment]
On the same page, you say

```
once #1133 is merged, see the Guide-for-changing-the-KORE-data-structures
```

Well, it is merged, so you can update that text, too.

**Comment by grosu** [comment]
Once you fix the problem above, please add a new item under Troubleshooting.  The Troubleshooting section starts with `Common error messages:`.  Are you referring to common error message reported by `mvn` when it builds the project?  If yes, please say it so.  For some reason, the third item is numbered `1)`, while the others are not; please fix this as well.

**Comment by grosu** [comment]
Can somebody who knows what's going on help with this?  Today is the last class before I ask students install K (Thursday).

**Comment by radumereuta** [comment]
The failing test, looks to come from what @cos added for KORE.

**Comment by grosu** [comment]
Thanks, Radu, but how can we merge changes that break the release?  I thought that was impossible.

**Comment by radumereuta** [comment]
It may be something that is platform dependent or the setup is wrong.
I think @bmmoore said something similar today at the meetings.

**Comment by grosu** [comment]
I'm using Windows 7.  Can somebody try it on Windows 7 to see if they get the same problem?  BTW, the Prerequisites say that we need a command line git.  I don't have one, I use TurtoiseGit, which gives me a bash if I need to type in commands.  I tried to also run `mvn package` from the git bash window, but it fails very quickly.  Let me know if interested to explore this path.

**Comment by radumereuta** [comment]
I just tested on win7, and I get the same error. It appears to be caused by line endings.
@cos, can you update the testing infrastructure to also take this into consideration?

**Comment by cos** [comment]
Normally, line endings shouldn't affect this in any way. @radumereuta, how did you infer it's the line endings and where did you encounter them?

 My best guess right now is that your git is configured to replace regular line endings with windows-style `\r\n` on checkout. If this is the case, I could account for it with the tests, but it would be much cleaner to fix your git configuration. Even when working from Windows, `\r\n` should not be used.

**Comment by radumereuta** [comment]
Tell that to the students.
I think our tests should just work, and not depend on some settings in git.
Even more so, the pretty printer should generate something representative to the OS in which is running.

I'm in my office at Siebel, where I have windows. If you are around, you can use my PC to see the issue.

**Comment by cos** [comment]
@radumereuta, I've added a custom git setting which should fix the problem. Please checkout and ktest this branch:
https://github.com/kframework/k/tree/autocrlf-input

I haven't played with these git attributes before so it may need a bit of convincing.

**Comment by radumereuta** [comment]
Same issue.
You are trying there to hide the problem. I think that your pretty printer should generate correct strings depending on the platform you are running on.

Or if you want to cheat. Do what I did in the front end with the SDF grammar. I save it to the disk, and load it again. Java knows how to save text files to disk with windows line endings.

**Comment by cos** [comment]
Yes Radu, I'm trying to hide the problem and cheating by learning to use git settings in order to find an elegant solution instead of changing one line in a code file I already know. 
As for the save to disk and loading back, is that in order to bypass doing `str.replaceAll("\r\n","\n")`?

In any case, it's minor and not worth the hustle. Here's the ugly fix with special casing for windows:
https://github.com/cos/k/tree/hotfix/fix-assertions-for-windows

I'll make a pull request if it works.

**Comment by cos** [comment]
addressed my readme issue here: https://github.com/kframework/k/pull/1313

**Comment by radumereuta** [comment]
I don't get the error anymore.
My suggested fix was to use `println`, and `System.lineSeparator()` instead of '\n', which I think is the root of the cause (probably).
