### ISSUE TITLE
Build failed at a fresh Ubuntu 14.04.1 Server 64-bit

### ISSUE THREAD

**Issue by daejunpark** [kframework/k-legacy#1346]
Build failed due to org.kframework.backend.java.symbolic.UseSMTTest failure, (see the details in the below) when I tried it in a fresh `ubuntu-14.04.1-server-amd64` guest OS of VMWare Fusion. All that I've installed are: JDK 1.8, git, and maven.

Indeed, the build succeeded in a desktop version of Ubuntu, `ubuntu-14.04-desktop-amd64`. Maybe some library missed in the server version? If it is, why the maven failed to automatically detect the missed one? Any idea?

```
...
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.kframework.backend.java.builtins.BuiltinFloatOperationsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.217 sec - in org.kframework.backend.java.builtins.BuiltinFloatOperationsTest
Running org.kframework.backend.java.builtins.BuiltinIOOperationsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.19 sec - in org.kframework.backend.java.builtins.BuiltinIOOperationsTest
Running org.kframework.backend.java.kil.JavaSymbolicObjectTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.182 sec - in org.kframework.backend.java.kil.JavaSymbolicObjectTest
Running org.kframework.backend.java.kil.BuiltinMapTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.022 sec - in org.kframework.backend.java.kil.BuiltinMapTest
Running org.kframework.backend.java.kil.BuiltinListTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in org.kframework.backend.java.kil.BuiltinListTest
Running org.kframework.backend.java.symbolic.UseSMTTest
${env.LD_LIBRARY_PATH}:/home/user/javascript-semantics/k/java-backend/target/lib/native:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.064 sec <<< FAILURE! - in org.kframework.backend.java.symbolic.UseSMTTest
testGetModel(org.kframework.backend.java.symbolic.UseSMTTest)  Time elapsed: 0.038 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: /home/user/javascript-semantics/k/java-backend/target/lib/native/libz3java.so: libgomp.so.1: cannot open shared object file: No such file or directory
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1855)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1119)
    at com.microsoft.z3.Native.<clinit>(Native.java:10)
    at com.microsoft.z3.Context.<init>(Context.java:24)
    at org.kframework.backend.java.symbolic.UseSMT.checkSat(UseSMT.java:44)
    at org.kframework.backend.java.symbolic.UseSMTTest.testGetModel(UseSMTTest.java:58)

Running org.kframework.backend.java.symbolic.JavaSymbolicKRunModuleTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.543 sec - in org.kframework.backend.java.symbolic.JavaSymbolicKRunModuleTest
Running org.kframework.backend.java.util.ConjunctionDisjunctionTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 sec - in org.kframework.backend.java.util.ConjunctionDisjunctionTest

Results :

Tests in error: 
  UseSMTTest.testGetModel:58 » UnsatisfiedLink /home/user/javascript-semantics/k...

Tests run: 14, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] K Framework Tool Parent ........................... SUCCESS [1.828s]
[INFO] K Framework KORE .................................. SUCCESS [2:40.741s]
[INFO] K Framework Tool Kernel ........................... SUCCESS [1:10.958s]
[INFO] K Framework Java Backend .......................... FAILURE [2:33.860s]
[INFO] K Framework Coq Backend ........................... SKIPPED
[INFO] K Framework SDF Backend ........................... SKIPPED
[INFO] K Framework Tool Distribution ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6:27.571s
[INFO] Finished at: Sat Feb 14 19:30:51 CST 2015
[INFO] Final Memory: 35M/214M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project java-backend: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/user/javascript-semantics/k/java-backend/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :java-backend
```

**Comment by dwightguth** [comment]
Huh. Didn't realize this was a dependency on Linux. Probably because
libgomp normally comes with gcc and gcc is usually one of the first things
installed on a linux box. I will go through the native dependencies of our
so files trying to document this. We will probably have to tell linux users
to install certain packages.

In the meantime, install gcc and you should be fine.

**Comment by daejunpark** [comment]
Thanks! It works after installing `build-essential`.
