### ISSUE TITLE
Strange error when parsing maps with the key zero

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#1369]
Consider the following simple definition:

```
module ARR
  syntax Value ::=   "{" Map "}"

  configuration
    <k> .K </k>
    <state> $ST:Map </state> 

endmodule
```

The following test is ok:

```
$ krun -cST="a |-> { 1 |-> 2 }"
<k>
    .K
</k>
<state>
    a |-> { 1 |-> 2 }
</state>
```

but the following one returns a very strange error:

```
$ krun -cST="a |-> { 0 |-> 2 }"
[Error] Internal: Uncaught exception thrown of type NullPointerException.
Please file a bug report at https://github.com/kframework/k/issues
```

Note that the only thing changed is the key of the map. For any key =/= 0 it works fine (inlcuding negatives).

**Comment by dwightguth** [comment]
Can you please run the program with the `--debug` option and paste the stack trace into this ticket?

**Comment by dlucanu** [comment]
Here it is:

```
$ kompile --version
K framework version 3.6-SNAPSHOT
Git revision: 4023860
Git branch: master
Build date: Tue Mar 03 16:11:32 EET 2015
$ krun -cST="a |-> { 0 |-> 2 }" --debug
java.lang.NullPointerException
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:269)
    at org.kframework.backend.java.kil.BuiltinMap.accept(BuiltinMap.java:172)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transformTerms(BackendJavaKILtoKILTransformer.java:205)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:185)
    at org.kframework.backend.java.kil.KList.accept(KList.java:166)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:136)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:684)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:269)
    at org.kframework.backend.java.kil.BuiltinMap.accept(BuiltinMap.java:172)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transformCell(BackendJavaKILtoKILTransformer.java:119)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:85)
    at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:305)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transformCell(BackendJavaKILtoKILTransformer.java:119)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:85)
    at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:305)
    at org.kframework.backend.java.util.JavaKRunState.getRawResult(JavaKRunState.java:52)
    at org.kframework.backend.unparser.PrettyPrintingOutputMode$PrintKRunState.run(PrettyPrintingOutputMode.java:31)
    at org.kframework.backend.unparser.PrettyPrintingOutputMode$PrintKRunState.run(PrettyPrintingOutputMode.java:20)
    at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
    at org.kframework.backend.unparser.PrintKRunResult.print(PrintKRunResult.java:48)
    at org.kframework.backend.unparser.PrintKRunResult.run(PrintKRunResult.java:42)
    at org.kframework.backend.unparser.PrintKRunResult.run(PrintKRunResult.java:19)
    at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
    at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
    at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:83)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:51)
    at org.kframework.main.Main.runApplication(Main.java:110)
    at org.kframework.main.Main.runApplication(Main.java:100)
    at org.kframework.main.Main.main(Main.java:52)
java.lang.NullPointerException
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:269)
    at org.kframework.backend.java.kil.BuiltinMap.accept(BuiltinMap.java:172)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transformTerms(BackendJavaKILtoKILTransformer.java:205)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:185)
    at org.kframework.backend.java.kil.KList.accept(KList.java:166)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:136)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:684)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:269)
    at org.kframework.backend.java.kil.BuiltinMap.accept(BuiltinMap.java:172)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transformCell(BackendJavaKILtoKILTransformer.java:119)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:85)
    at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:305)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transformCell(BackendJavaKILtoKILTransformer.java:119)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:85)
    at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:305)
    at org.kframework.backend.java.util.JavaKRunState.getRawResult(JavaKRunState.java:52)
    at org.kframework.backend.unparser.PrettyPrintingOutputMode$PrintKRunState.run(PrettyPrintingOutputMode.java:31)
    at org.kframework.backend.unparser.PrettyPrintingOutputMode$PrintKRunState.run(PrettyPrintingOutputMode.java:20)
    at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
    at org.kframework.backend.unparser.PrintKRunResult.print(PrintKRunResult.java:48)
    at org.kframework.backend.unparser.PrintKRunResult.run(PrintKRunResult.java:42)
    at org.kframework.backend.unparser.PrintKRunResult.run(PrintKRunResult.java:19)
    at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
    at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
    at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:83)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:51)
    at org.kframework.main.Main.runApplication(Main.java:110)
    at org.kframework.main.Main.runApplication(Main.java:100)
    at org.kframework.main.Main.main(Main.java:52)
[Error] Internal: Uncaught exception thrown of type NullPointerException.
Please file a bug report at https://github.com/kframework/k/issues
```

**Comment by dwightguth** [comment]
My guess is this bug has to do with hashCode somehow. Assigning this to @andreistefanescu . Andrei, if you want me to look into it let me know, I know I did tweak the hashCode implementation recently so it might have caused this...
