### ISSUE TITLE
Index arithmetic error in TermCons from KOREToTreeNodes

### ISSUE THREAD

**Issue by cos** [kframework/k-legacy#1519]
```
error was: java.lang.IndexOutOfBoundsException
    at org.pcollections.ConsPStack.listIterator(ConsPStack.java:85)
    at java.util.AbstractSequentialList.get(AbstractSequentialList.java:88)
    at org.kframework.parser.TermCons.get(treeNodes.scala:36)
    at org.kframework.unparser.KOREToTreeNodes$$anonfun$1.apply(KOREToTreeNodes.scala:46)
```

Replicate by running: `ktest tests/config.xml --skip pdf` in `/k-distribution/tutorial-on-kore/1_k/2_imp/lesson_2` on branch `feature/ktest-tutorial2`.

**Comment by dwightguth** [comment]
So, we can definitely have a better error message in this case, but this
looks like a mismatch between the arity of the production being pretty
printed and the arity of the TermCons that is claiming to be an instance of
that production. Given the fact that last I checked you were deliberately
doing this in misc.k with Maps, I'm not going to spend time investigating
this issue unless you can demonstrate that this is an actual bug and not
simply a misuse of the standard library.
