### ISSUE TITLE
data race on field org.kframework.backend.java.kil.KItem.isExactSort/sort/possibleSorts

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1538]
I got this race report when ktest-ing kool-typed-static under RV-Predict:

```
Data race on field org.kframework.backend.java.kil.KItem.isExactSort: {{{
    Concurrent write in thread T43 (locks held: {})
 ---->  at org.kframework.backend.java.kil.KItem.computeSort(KItem.java:242)
        at org.kframework.backend.java.kil.KItem.sort(KItem.java:640)
        at org.kframework.backend.java.symbolic.PatternMatcher.add(PatternMatcher.java:190)
        at org.kframework.backend.java.symbolic.PatternMatcher.stop(PatternMatcher.java:166)
        at org.kframework.backend.java.symbolic.AbstractUnifier.unify(AbstractUnifier.java:165)
        at org.kframework.backend.java.symbolic.PatternMatcher.unify(PatternMatcher.java:520)
        at org.kframework.backend.java.symbolic.AbstractUnifier.unify(AbstractUnifier.java:172)
        at org.kframework.backend.java.symbolic.PatternMatcher.patternMatch(PatternMatcher.java:144)
        at org.kframework.backend.java.symbolic.PatternMatcher.patternMatch(PatternMatcher.java:135)
        at org.kframework.backend.java.symbolic.PatternMatcher.match(PatternMatcher.java:117)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.getMatchingResults(PatternMatchRewriter.java:146)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.computeRewriteStep(PatternMatchRewriter.java:256)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.rewrite(PatternMatchRewriter.java:93)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.patternMatcherRewriteRun(JavaSymbolicExecutor.java:107)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:134)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:118)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T43 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)

    Concurrent write in thread T51 (locks held: {})
 ---->  at org.kframework.backend.java.kil.KItem.computeSort(KItem.java:242)
        at org.kframework.backend.java.kil.KItem.sort(KItem.java:640)
        at org.kframework.backend.java.symbolic.PatternMatcher.add(PatternMatcher.java:190)
        at org.kframework.backend.java.symbolic.PatternMatcher.stop(PatternMatcher.java:166)
        at org.kframework.backend.java.symbolic.AbstractUnifier.unify(AbstractUnifier.java:165)
        at org.kframework.backend.java.symbolic.PatternMatcher.unify(PatternMatcher.java:520)
        at org.kframework.backend.java.symbolic.AbstractUnifier.unify(AbstractUnifier.java:172)
        at org.kframework.backend.java.symbolic.PatternMatcher.patternMatch(PatternMatcher.java:144)
        at org.kframework.backend.java.symbolic.PatternMatcher.patternMatch(PatternMatcher.java:135)
        at org.kframework.backend.java.symbolic.PatternMatcher.match(PatternMatcher.java:117)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.getMatchingResults(PatternMatchRewriter.java:146)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.computeRewriteStep(PatternMatchRewriter.java:256)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.rewrite(PatternMatchRewriter.java:93)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.patternMatcherRewriteRun(JavaSymbolicExecutor.java:107)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:134)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:118)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T51 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}
```

**Comment by yilongli** [comment]
The other two reports:

```
Data race on field org.kframework.backend.java.kil.KItem.possibleSorts: {{{
    Concurrent write in thread T43 (locks held: {})
 ---->  at org.kframework.backend.java.kil.KItem.computeSort(KItem.java:243)
        at org.kframework.backend.java.kil.KItem.sort(KItem.java:640)
        at org.kframework.backend.java.symbolic.PatternMatcher.add(PatternMatcher.java:190)
        at org.kframework.backend.java.symbolic.PatternMatcher.stop(PatternMatcher.java:166)
        at org.kframework.backend.java.symbolic.AbstractUnifier.unify(AbstractUnifier.java:165)
        at org.kframework.backend.java.symbolic.PatternMatcher.unify(PatternMatcher.java:520)
        at org.kframework.backend.java.symbolic.AbstractUnifier.unify(AbstractUnifier.java:172)
        at org.kframework.backend.java.symbolic.PatternMatcher.patternMatch(PatternMatcher.java:144)
        at org.kframework.backend.java.symbolic.PatternMatcher.patternMatch(PatternMatcher.java:135)
        at org.kframework.backend.java.symbolic.PatternMatcher.match(PatternMatcher.java:117)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.getMatchingResults(PatternMatchRewriter.java:146)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.computeRewriteStep(PatternMatchRewriter.java:256)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.rewrite(PatternMatchRewriter.java:93)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.patternMatcherRewriteRun(JavaSymbolicExecutor.java:107)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:134)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:118)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T43 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)

    Concurrent write in thread T51 (locks held: {})
 ---->  at org.kframework.backend.java.kil.KItem.computeSort(KItem.java:243)
        at org.kframework.backend.java.kil.KItem.sort(KItem.java:640)
        at org.kframework.backend.java.symbolic.PatternMatcher.add(PatternMatcher.java:190)
        at org.kframework.backend.java.symbolic.PatternMatcher.stop(PatternMatcher.java:166)
        at org.kframework.backend.java.symbolic.AbstractUnifier.unify(AbstractUnifier.java:165)
        at org.kframework.backend.java.symbolic.PatternMatcher.unify(PatternMatcher.java:520)
        at org.kframework.backend.java.symbolic.AbstractUnifier.unify(AbstractUnifier.java:172)
        at org.kframework.backend.java.symbolic.PatternMatcher.patternMatch(PatternMatcher.java:144)
        at org.kframework.backend.java.symbolic.PatternMatcher.patternMatch(PatternMatcher.java:135)
        at org.kframework.backend.java.symbolic.PatternMatcher.match(PatternMatcher.java:117)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.getMatchingResults(PatternMatchRewriter.java:146)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.computeRewriteStep(PatternMatchRewriter.java:256)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.rewrite(PatternMatchRewriter.java:93)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.patternMatcherRewriteRun(JavaSymbolicExecutor.java:107)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:134)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:118)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T51 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}

Data race on field org.kframework.backend.java.kil.KItem.sort: {{{
    Concurrent write in thread T43 (locks held: {})
 ---->  at org.kframework.backend.java.kil.KItem.computeSort(KItem.java:241)
        at org.kframework.backend.java.kil.KItem.sort(KItem.java:640)
        at org.kframework.backend.java.symbolic.PatternMatcher.add(PatternMatcher.java:190)
        at org.kframework.backend.java.symbolic.PatternMatcher.stop(PatternMatcher.java:166)
        at org.kframework.backend.java.symbolic.AbstractUnifier.unify(AbstractUnifier.java:165)
        at org.kframework.backend.java.symbolic.PatternMatcher.unify(PatternMatcher.java:520)
        at org.kframework.backend.java.symbolic.AbstractUnifier.unify(AbstractUnifier.java:172)
        at org.kframework.backend.java.symbolic.PatternMatcher.patternMatch(PatternMatcher.java:144)
        at org.kframework.backend.java.symbolic.PatternMatcher.patternMatch(PatternMatcher.java:135)
        at org.kframework.backend.java.symbolic.PatternMatcher.match(PatternMatcher.java:117)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.getMatchingResults(PatternMatchRewriter.java:146)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.computeRewriteStep(PatternMatchRewriter.java:256)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.rewrite(PatternMatchRewriter.java:93)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.patternMatcherRewriteRun(JavaSymbolicExecutor.java:107)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:134)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:118)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T43 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)

    Concurrent write in thread T51 (locks held: {})
 ---->  at org.kframework.backend.java.kil.KItem.computeSort(KItem.java:241)
        at org.kframework.backend.java.kil.KItem.sort(KItem.java:640)
        at org.kframework.backend.java.symbolic.PatternMatcher.add(PatternMatcher.java:190)
        at org.kframework.backend.java.symbolic.PatternMatcher.stop(PatternMatcher.java:166)
        at org.kframework.backend.java.symbolic.AbstractUnifier.unify(AbstractUnifier.java:165)
        at org.kframework.backend.java.symbolic.PatternMatcher.unify(PatternMatcher.java:520)
        at org.kframework.backend.java.symbolic.AbstractUnifier.unify(AbstractUnifier.java:172)
        at org.kframework.backend.java.symbolic.PatternMatcher.patternMatch(PatternMatcher.java:144)
        at org.kframework.backend.java.symbolic.PatternMatcher.patternMatch(PatternMatcher.java:135)
        at org.kframework.backend.java.symbolic.PatternMatcher.match(PatternMatcher.java:117)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.getMatchingResults(PatternMatchRewriter.java:146)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.computeRewriteStep(PatternMatchRewriter.java:256)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.rewrite(PatternMatchRewriter.java:93)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.patternMatcherRewriteRun(JavaSymbolicExecutor.java:107)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:134)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:118)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T51 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}
```

**Comment by yilongli** [comment]
Probably fixed recently. I am not getting these race reports anymore.
