### ISSUE TITLE
lack of synchronization when using the thread-unsafe cloning library

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1539]
Reported by RV-Predict:

```
Data race on field java.util.LinkedList.$state: {{{
    Concurrent write in thread T43 (locks held: {})
 ---->  at com.rits.cloning.Cloner.addAll(Cloner.java:594)
        at com.rits.cloning.Cloner.allFields(Cloner.java:608)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:496)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:485)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.deepClone(Cloner.java:323)
        at org.kframework.backend.java.symbolic.DeepCloner.clone(DeepCloner.java:30)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.constructNewSubjectTerm(PatternMatchRewriter.java:299)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.computeRewriteStep(PatternMatchRewriter.java:262)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.rewrite(PatternMatchRewriter.java:93)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.patternMatcherRewriteRun(JavaSymbolicExecutor.java:107)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:134)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:118)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T43 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)

    Concurrent read in thread T57 (locks held: {})
 ---->  at com.rits.cloning.Cloner.cloneInternal(Cloner.java:497)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:485)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:514)
        at com.rits.cloning.Cloner.deepClone(Cloner.java:323)
        at org.kframework.backend.java.symbolic.DeepCloner.clone(DeepCloner.java:30)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.constructNewSubjectTerm(PatternMatchRewriter.java:299)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.computeRewriteStep(PatternMatchRewriter.java:262)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.rewrite(PatternMatchRewriter.java:93)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.patternMatcherRewriteRun(JavaSymbolicExecutor.java:107)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:134)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:118)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T57 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}
```

**Comment by yilongli** [comment]
This is unfortunately a false positive. The cloning library is indeed thread-safe:
https://github.com/kostaskougios/cloning/blob/master/wiki/Usage.md

After reading the source code of [Cloner.java](https://github.com/kostaskougios/cloning/blob/f7a225ff9b397220503633fdd66bc3ad9ba936a6/src/main/java/com/rits/cloning/Cloner.java), I conclude that the RV-Predict output the false positive because it missed the HB edge between `ConcurrentHashMap fieldsCache.put & get`. This was only fixed recently.

**Comment by dwightguth** [comment]
You sure? I saw this one earlier today, was the code merged into master
only that recently?

**Comment by yilongli** [comment]
No, it was supposed to be fixed earlier. I will run it again.

**Comment by yilongli** [comment]
The HB edge is actually between `putIfAbsent` and `get`. RV-Predict missed to intercept `putIfAbsent` and a few other methods in `Map` introduced in Java 8. Just fixed.
