### ISSUE TITLE
data race on field org.kframework.backend.java.kil.Term.mutable

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1540]
Reported by RV-Predict:

```
Data race on field org.kframework.backend.java.kil.Term.mutable: {{{
    Concurrent write in thread T57 (locks held: {})
 ---->  at org.kframework.backend.java.kil.Term.isMutable(Term.java:87)
        at org.kframework.backend.java.symbolic.DeepCloner$FastTermCloner.fastClone(DeepCloner.java:44)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:460)
        at com.rits.cloning.Cloner.deepClone(Cloner.java:323)
        at org.kframework.backend.java.symbolic.DeepCloner.clone(DeepCloner.java:30)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.constructNewSubjectTerm(PatternMatchRewriter.java:299)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.computeRewriteStep(PatternMatchRewriter.java:262)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.rewrite(PatternMatchRewriter.java:93)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.patternMatcherRewriteRun(JavaSymbolicExecutor.java:107)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:134)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:118)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T57 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)

    Concurrent write in thread T43 (locks held: {})
 ---->  at org.kframework.backend.java.kil.Term.isMutable(Term.java:87)
        at org.kframework.backend.java.symbolic.DeepCloner$FastTermCloner.fastClone(DeepCloner.java:44)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:460)
        at com.rits.cloning.Cloner.deepClone(Cloner.java:323)
        at org.kframework.backend.java.symbolic.DeepCloner.clone(DeepCloner.java:30)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.constructNewSubjectTerm(PatternMatchRewriter.java:299)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.computeRewriteStep(PatternMatchRewriter.java:262)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.rewrite(PatternMatchRewriter.java:93)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.patternMatcherRewriteRun(JavaSymbolicExecutor.java:107)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:134)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:118)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T43 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}
```

**Comment by yilongli** [comment]
Another report:

```
Data race on field org.kframework.backend.java.kil.Term.mutable: {{{
    Concurrent write in thread T51 (locks held: {})
 ---->  at org.kframework.backend.java.kil.Term.isMutable(Term.java:87)
        at org.kframework.backend.java.kil.KItem.computeMutability(KItem.java:673)
        at org.kframework.backend.java.kil.Term.isMutable(Term.java:87)
        at org.kframework.backend.java.symbolic.EliminateUnsafeSharingTransformer$SharedMutableTermCopier.transform(EliminateUnsafeSharingTransformer.java:46)
        at org.kframework.backend.java.symbolic.LocalTransformer.transform(LocalTransformer.java:110)
        at org.kframework.backend.java.kil.KItem.accept(KItem.java:688)
        at org.kframework.backend.java.symbolic.CombinedLocalTransformer.transformAll(CombinedLocalTransformer.java:48)
        at org.kframework.backend.java.symbolic.CombinedLocalTransformer.transform(CombinedLocalTransformer.java:123)
        at org.kframework.backend.java.kil.KItem.accept(KItem.java:688)
        at org.kframework.backend.java.symbolic.PrePostTransformer.transform(PrePostTransformer.java:130)
        at org.kframework.backend.java.kil.KItem.accept(KItem.java:688)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:57)
        at org.kframework.backend.java.symbolic.PrePostTransformer.transform(PrePostTransformer.java:63)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:288)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:57)
        at org.kframework.backend.java.symbolic.PrePostTransformer.transform(PrePostTransformer.java:63)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:288)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:57)
        at org.kframework.backend.java.symbolic.PrePostTransformer.transform(PrePostTransformer.java:63)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:288)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:57)
        at org.kframework.backend.java.symbolic.PrePostTransformer.transform(PrePostTransformer.java:63)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:288)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:57)
        at org.kframework.backend.java.symbolic.PrePostTransformer.transform(PrePostTransformer.java:63)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:288)
        at org.kframework.backend.java.symbolic.EliminateUnsafeSharingTransformer.transformTerm(EliminateUnsafeSharingTransformer.java:26)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.rewrite(PatternMatchRewriter.java:72)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.patternMatcherRewriteRun(JavaSymbolicExecutor.java:107)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:134)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:118)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T51 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)

    Concurrent read in thread T43 (locks held: {})
 ---->  at org.kframework.backend.java.kil.Term.isMutable(Term.java:89)
        at org.kframework.backend.java.kil.KItem.computeMutability(KItem.java:673)
        at org.kframework.backend.java.kil.Term.isMutable(Term.java:87)
        at org.kframework.backend.java.kil.KCollection.computeMutability(KCollection.java:85)
        at org.kframework.backend.java.kil.Term.isMutable(Term.java:87)
        at org.kframework.backend.java.kil.KItem.computeMutability(KItem.java:673)
        at org.kframework.backend.java.kil.Term.isMutable(Term.java:87)
        at org.kframework.backend.java.kil.KCollection.computeMutability(KCollection.java:85)
        at org.kframework.backend.java.kil.Term.isMutable(Term.java:87)
        at org.kframework.backend.java.kil.KItem.computeMutability(KItem.java:673)
        at org.kframework.backend.java.kil.Term.isMutable(Term.java:87)
        at org.kframework.backend.java.symbolic.EliminateUnsafeSharingTransformer$SharedMutableTermCopier.transform(EliminateUnsafeSharingTransformer.java:46)
        at org.kframework.backend.java.symbolic.LocalTransformer.transform(LocalTransformer.java:110)
        at org.kframework.backend.java.kil.KItem.accept(KItem.java:688)
        at org.kframework.backend.java.symbolic.CombinedLocalTransformer.transformAll(CombinedLocalTransformer.java:48)
        at org.kframework.backend.java.symbolic.CombinedLocalTransformer.transform(CombinedLocalTransformer.java:123)
        at org.kframework.backend.java.kil.KItem.accept(KItem.java:688)
        at org.kframework.backend.java.symbolic.PrePostTransformer.transform(PrePostTransformer.java:130)
        at org.kframework.backend.java.kil.KItem.accept(KItem.java:688)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:57)
        at org.kframework.backend.java.symbolic.PrePostTransformer.transform(PrePostTransformer.java:63)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:288)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:57)
        at org.kframework.backend.java.symbolic.PrePostTransformer.transform(PrePostTransformer.java:63)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:288)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:57)
        at org.kframework.backend.java.symbolic.PrePostTransformer.transform(PrePostTransformer.java:63)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:288)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:57)
        at org.kframework.backend.java.symbolic.PrePostTransformer.transform(PrePostTransformer.java:63)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:288)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:57)
        at org.kframework.backend.java.symbolic.PrePostTransformer.transform(PrePostTransformer.java:63)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:288)
        at org.kframework.backend.java.symbolic.EliminateUnsafeSharingTransformer.transformTerm(EliminateUnsafeSharingTransformer.java:26)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.rewrite(PatternMatchRewriter.java:72)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.patternMatcherRewriteRun(JavaSymbolicExecutor.java:107)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:134)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:118)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T43 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}
```

**Comment by yilongli** [comment]
The fix was incorrect because `org.kframework.backend.java.kil` classes are not supposed to be thread-safe!

**Comment by dwightguth** [comment]
@yilongli this relates to the fact that Definition objects are shared across multiple requests. I did this because it creates a significant performance savings over multiple requests when the definition does not have to be reloaded and its lazy information recomputed after each request.

**Comment by yilongli** [comment]
Yes, I am aware of that. But only the immutable terms inside the Definition object should be shared between threads. Apparently, that is broken somehow.
