### ISSUE TITLE
data race on field org.kframework.backend.java.kil.JavaSymbolicObject.hashCode

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1541]
Reported by RV-Predict:

```
Data race on field org.kframework.backend.java.kil.JavaSymbolicObject.hashCode: {{{
    Concurrent read in thread T51 (locks held: {})
 ---->  at org.kframework.backend.java.kil.Term.hashCode(Term.java:229)
        at org.kframework.backend.java.kil.GlobalContext.builtins(GlobalContext.java:68)
        at org.kframework.backend.java.kil.GlobalContext$$Lambda$88.get(Unknown:n/a)
        at org.kframework.backend.java.kil.KItem$KItemOperations.isEvaluable(KItem.java:358)
        at org.kframework.backend.java.kil.KItem.isEvaluable(KItem.java:253)
        at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:308)
        at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:261)
        at org.kframework.backend.java.symbolic.Evaluator.transform(Evaluator.java:27)
        at org.kframework.backend.java.kil.KItem.accept(KItem.java:688)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:191)
        at org.kframework.backend.java.kil.KList.accept(KList.java:152)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:133)
        at org.kframework.backend.java.symbolic.Evaluator.transform(Evaluator.java:27)
        at org.kframework.backend.java.kil.KItem.accept(KItem.java:688)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:191)
        at org.kframework.backend.java.kil.KList.accept(KList.java:152)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:133)
        at org.kframework.backend.java.symbolic.Evaluator.transform(Evaluator.java:27)
        at org.kframework.backend.java.kil.KItem.accept(KItem.java:688)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:191)
        at org.kframework.backend.java.kil.KList.accept(KList.java:152)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:133)
        at org.kframework.backend.java.symbolic.Evaluator.transform(Evaluator.java:27)
        at org.kframework.backend.java.kil.KItem.accept(KItem.java:688)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:191)
        at org.kframework.backend.java.kil.KList.accept(KList.java:152)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:133)
        at org.kframework.backend.java.symbolic.Evaluator.transform(Evaluator.java:27)
        at org.kframework.backend.java.kil.KItem.accept(KItem.java:688)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:191)
        at org.kframework.backend.java.kil.KList.accept(KList.java:152)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:133)
        at org.kframework.backend.java.symbolic.Evaluator.transform(Evaluator.java:27)
        at org.kframework.backend.java.kil.KItem.accept(KItem.java:688)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:57)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:288)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:57)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:288)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:57)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:288)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:57)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:288)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:57)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:288)
        at org.kframework.backend.java.symbolic.Evaluator.evaluate(Evaluator.java:22)
        at org.kframework.backend.java.kil.Term.evaluate(Term.java:102)
        at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.expandAndEvaluate(KILtoBackendJavaKILTransformer.java:139)
        at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transformAndEval(KILtoBackendJavaKILTransformer.java:134)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.getJavaKilTerm(JavaSymbolicExecutor.java:82)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:131)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:118)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T51 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)

    Concurrent write in thread T43 (locks held: {})
 ---->  at org.kframework.backend.java.kil.Term.hashCode(Term.java:233)
        at org.kframework.backend.java.kil.GlobalContext.builtins(GlobalContext.java:68)
        at org.kframework.backend.java.kil.GlobalContext$$Lambda$88.get(Unknown:n/a)
        at org.kframework.backend.java.kil.KItem$KItemOperations.isEvaluable(KItem.java:358)
        at org.kframework.backend.java.kil.KItem.isEvaluable(KItem.java:253)
        at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:308)
        at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:261)
        at org.kframework.backend.java.symbolic.Evaluator.transform(Evaluator.java:27)
        at org.kframework.backend.java.kil.KItem.accept(KItem.java:688)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:191)
        at org.kframework.backend.java.kil.KList.accept(KList.java:152)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:133)
        at org.kframework.backend.java.symbolic.Evaluator.transform(Evaluator.java:27)
        at org.kframework.backend.java.kil.KItem.accept(KItem.java:688)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:191)
        at org.kframework.backend.java.kil.KList.accept(KList.java:152)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:133)
        at org.kframework.backend.java.symbolic.Evaluator.transform(Evaluator.java:27)
        at org.kframework.backend.java.kil.KItem.accept(KItem.java:688)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:191)
        at org.kframework.backend.java.kil.KList.accept(KList.java:152)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:133)
        at org.kframework.backend.java.symbolic.Evaluator.transform(Evaluator.java:27)
        at org.kframework.backend.java.kil.KItem.accept(KItem.java:688)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:191)
        at org.kframework.backend.java.kil.KList.accept(KList.java:152)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:133)
        at org.kframework.backend.java.symbolic.Evaluator.transform(Evaluator.java:27)
        at org.kframework.backend.java.kil.KItem.accept(KItem.java:688)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:57)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:288)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:57)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:288)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:57)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:288)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:57)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:288)
        at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:57)
        at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:288)
        at org.kframework.backend.java.symbolic.Evaluator.evaluate(Evaluator.java:22)
        at org.kframework.backend.java.kil.Term.evaluate(Term.java:102)
        at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.expandAndEvaluate(KILtoBackendJavaKILTransformer.java:139)
        at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transformAndEval(KILtoBackendJavaKILTransformer.java:134)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.getJavaKilTerm(JavaSymbolicExecutor.java:82)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:131)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:118)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T43 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}
```

**Comment by yilongli** [comment]
Benign data race: racey single check.
