### ISSUE TITLE
data race on com.google.common.cache.LocalCache$2.$state during dependency injection

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1542]
Reported by RV-Predict:

```
Data race on field com.google.common.cache.LocalCache$2.$state: {{{
    Concurrent write in thread T52 (locks held: {})
 ---->  at com.google.common.cache.LocalCache$Segment.recordRead(LocalCache.java:2544)
        at com.google.common.cache.LocalCache$Segment.getLiveValue(LocalCache.java:2740)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2183)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830)
        at com.google.inject.internal.Annotations$AnnotationChecker.hasAnnotations(Annotations.java:237)
        at com.google.inject.internal.Annotations.isBindingAnnotation(Annotations.java:301)
        at com.google.inject.Key.ensureIsBindingAnnotation(Key.java:402)
        at com.google.inject.Key.strategyFor(Key.java:389)
        at com.google.inject.Key.get(Key.java:251)
        at org.kframework.main.Main.seedInjector(Main.java:127)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:106)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T52 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)

    Concurrent write in thread T57 (locks held: {})
 ---->  at com.google.common.cache.LocalCache$Segment.recordRead(LocalCache.java:2544)
        at com.google.common.cache.LocalCache$Segment.getLiveValue(LocalCache.java:2740)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2183)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830)
        at com.google.inject.internal.Annotations$AnnotationChecker.hasAnnotations(Annotations.java:237)
        at com.google.inject.internal.Annotations.isBindingAnnotation(Annotations.java:301)
        at com.google.inject.Key.ensureIsBindingAnnotation(Key.java:402)
        at com.google.inject.Key.strategyFor(Key.java:389)
        at com.google.inject.Key.get(Key.java:251)
        at org.kframework.main.Main.seedInjector(Main.java:127)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:106)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T57 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}
```

**Comment by yilongli** [comment]
This is a false positive. The custom [DISCARDING_QUEUE](http://grepcode.com/file/repo1.maven.org/maven2/com.google.guava/guava/18.0/com/google/common/cache/LocalCache.java#LocalCache.0DISCARDING_QUEUE) is a trivial immutable class. RV-Predict treats it as a normal `Queue` implementation during mocking and concludes that it's not thread-safe.
