### ISSUE TITLE
data race on field org.kframework.kompile.KompileOptions.files

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1543]
Reported by RV-Predict:

```
Data race on field org.kframework.kompile.KompileOptions.files: {{{
    Concurrent write in thread T57 (locks held: {Monitor@6f030508})
 ---->  at org.kframework.kompile.KompileOptions.setFiles(KompileOptions.java:40)
        at org.kframework.utils.inject.DefinitionLoadingModule$$FastClassByGuice$$6c55efa6.invoke(<generated>:n/a)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:230)
        at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:148)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at org.kframework.utils.inject.SimpleScope$2.get(SimpleScope.java:99)
        - locked Monitor@6f030508 at org.kframework.utils.inject.SimpleScope$2.get(SimpleScope.java:95) 
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.ExposedKeyFactory.get(ExposedKeyFactory.java:54)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:94)
        at com.google.inject.throwingproviders.ThrowingProviderBinder$SecondaryBinder$3.get(ThrowingProviderBinder.java:292)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:94)
        at com.google.inject.throwingproviders.ThrowingProviderBinder$SecondaryBinder$2$1.invoke(ThrowingProviderBinder.java:275)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:116)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T57 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)

    Concurrent write in thread T43 (locks held: {Monitor@6412ee6d})
 ---->  at org.kframework.kompile.KompileOptions.setFiles(KompileOptions.java:40)
        at org.kframework.utils.inject.DefinitionLoadingModule$$FastClassByGuice$$6c55efa6.invoke(<generated>:n/a)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:230)
        at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:148)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at org.kframework.utils.inject.SimpleScope$2.get(SimpleScope.java:99)
        - locked Monitor@6412ee6d at org.kframework.utils.inject.SimpleScope$2.get(SimpleScope.java:95) 
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.ExposedKeyFactory.get(ExposedKeyFactory.java:54)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:94)
        at com.google.inject.throwingproviders.ThrowingProviderBinder$SecondaryBinder$3.get(ThrowingProviderBinder.java:292)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:94)
        at com.google.inject.throwingproviders.ThrowingProviderBinder$SecondaryBinder$2$1.invoke(ThrowingProviderBinder.java:275)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:116)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T43 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}
```

**Comment by Bhargee** [comment]
The two stacktraces are identical modulo monitor object hashes and thread IDs, so it doesn't make sense that the same object is created and has setFiles called in two different threads. The opacity of the thread injection sort of throws me off, but I think this is a false positive.

**Comment by dwightguth** [comment]
@yilongli I think this is a false positive too... Both of these seem to be happening in the main request thread, each one of which should have its own Injector. So I don't see how two different injectors could end up each creating a KompileOptions object and somehow having it be the same object to race on.

**Comment by yilongli** [comment]
@dwightguth @Bhargee While RV-Predict may miss some HB edges which result in false positives, it's very unlikely for RV-Predict to log incorrect memory location. I added the following line of code at [`KompileOptions.setFiles`](https://github.com/kframework/k/blob/master/kernel/src/main/java/org/kframework/kompile/KompileOptions.java#L40) to verify my conjecture:
`System.err.println(this + " accessed by " + Thread.currentThread() + " " + Thread.currentThread().getId() + ", files = " + files);`

Then I run ktest in kserver mode and get the following output:

```
org.kframework.kompile.KompileOptions@1d94a58b accessed by Thread[NGSession 8: 127.0.0.1: org.kframework.main.Main,5,main] 45, files = org.kframework.utils.inject.SimpleScope$2@44cdf5e8 
...
org.kframework.kompile.KompileOptions@1d94a58b accessed by Thread[NGSession 5: 127.0.0.1: org.kframework.main.Main,5,main] 35, files = org.kframework.utils.inject.SimpleScope$2@44cdf5e8 
...
org.kframework.kompile.KompileOptions@1d94a58b accessed by Thread[NGSession 7: 127.0.0.1: org.kframework.main.Main,5,main] 38, files = org.kframework.utils.inject.SimpleScope$2@44cdf5e8 
```

It appears that `KompileOptions` is created as a singleton but somehow Guice decides to call `setFiles` on it every time you request an instance of `KompileOptions`.

**Comment by dwightguth** [comment]
You are correct, this is a real race, my bad. The issue is that for each program in the same definition, we were accessing the same KompileOptoins object which had been serialized to a file and deserialized again. I have a patch that should take care of this issue if you are interested.

**Comment by yilongli** [comment]
Yes, please go head to submit the patch. I am not familiar enough with the code to fix this. Thanks!

**Comment by yilongli** [comment]
I got another race report on it:

```
Data race on field org.kframework.kompile.KompileOptions.files: {{{
    Concurrent write in thread T42 (locks held: {})
 ---->  at org.kframework.kompile.KompileOptions.setFiles(KompileOptions.java:45)
        at org.kframework.utils.inject.DefinitionLoadingModule.kompileOptions(DefinitionLoadingModule.java:78)
        at org.kframework.utils.inject.DefinitionLoadingModule$$FastClassByGuice$$6c55efa6.invoke(<generated>:n/a)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:230)
        at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:148)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.getPatternMatchRewriter(JavaSymbolicExecutor.java:237)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.patternMatcherRewriteRun(JavaSymbolicExecutor.java:107)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:134)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:131)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
    T42 is created by T13
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)

    Concurrent write in thread T35 (locks held: {})
 ---->  at org.kframework.kompile.KompileOptions.setFiles(KompileOptions.java:45)
        at org.kframework.utils.inject.DefinitionLoadingModule.kompileOptions(DefinitionLoadingModule.java:78)
        at org.kframework.utils.inject.DefinitionLoadingModule$$FastClassByGuice$$6c55efa6.invoke(<generated>:n/a)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:230)
        at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:148)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.getPatternMatchRewriter(JavaSymbolicExecutor.java:237)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.patternMatcherRewriteRun(JavaSymbolicExecutor.java:107)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:134)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:131)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
    T35 is created by T13
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}
```

@dwightguth what do you think?
