### ISSUE TITLE
data race on field org.kframework.parser.concrete.DefinitionLocalKParser.resourceDomain

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1544]
Reported by RV-Predict:

```
Data race on field org.kframework.parser.concrete.DefinitionLocalKParser.resourceDomain: {{{
    Concurrent write in thread T52 (locks held: {Monitor@4ef3191c})
 ---->  at org.kframework.parser.concrete.DefinitionLocalKParser.init(DefinitionLocalKParser.java:58)
        at org.kframework.parser.concrete.DefinitionLocalKParser.ParseProgramString(DefinitionLocalKParser.java:119)
        at org.kframework.parser.ProgramLoader.loadPgmAst(ProgramLoader.java:89)
        at org.kframework.parser.ProgramLoader.loadPgmAst(ProgramLoader.java:109)
        at org.kframework.parser.ProgramLoader.processPgm(ProgramLoader.java:164)
        at org.kframework.krun.RunProcess.runParser(RunProcess.java:132)
        at org.kframework.krun.InitialConfigurationProvider.get(InitialConfigurationProvider.java:89)
        at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:73)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:63)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at org.kframework.utils.inject.SimpleScope$2.get(SimpleScope.java:99)
        - locked Monitor@4ef3191c at org.kframework.utils.inject.SimpleScope$2.get(SimpleScope.java:95) 
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.ExposedKeyFactory.get(ExposedKeyFactory.java:54)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:94)
        at com.google.inject.throwingproviders.ThrowingProviderBinder$SecondaryBinder$3.get(ThrowingProviderBinder.java:292)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:94)
        at com.google.inject.throwingproviders.ThrowingProviderBinder$SecondaryBinder$2$1.invoke(ThrowingProviderBinder.java:275)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:116)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T52 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)

    Concurrent read in thread T43 (locks held: {Monitor@6412ee6d})
 ---->  at org.kframework.parser.concrete.DefinitionLocalKParser.init(DefinitionLocalKParser.java:58)
        at org.kframework.parser.concrete.DefinitionLocalKParser.ParseProgramString(DefinitionLocalKParser.java:119)
        at org.kframework.parser.ProgramLoader.loadPgmAst(ProgramLoader.java:89)
        at org.kframework.parser.ProgramLoader.loadPgmAst(ProgramLoader.java:109)
        at org.kframework.parser.ProgramLoader.processPgm(ProgramLoader.java:164)
        at org.kframework.krun.RunProcess.runParser(RunProcess.java:132)
        at org.kframework.krun.InitialConfigurationProvider.get(InitialConfigurationProvider.java:89)
        at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:73)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:63)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at org.kframework.utils.inject.SimpleScope$2.get(SimpleScope.java:99)
        - locked Monitor@6412ee6d at org.kframework.utils.inject.SimpleScope$2.get(SimpleScope.java:95) 
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.ExposedKeyFactory.get(ExposedKeyFactory.java:54)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:94)
        at com.google.inject.throwingproviders.ThrowingProviderBinder$SecondaryBinder$3.get(ThrowingProviderBinder.java:292)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:94)
        at com.google.inject.throwingproviders.ThrowingProviderBinder$SecondaryBinder$2$1.invoke(ThrowingProviderBinder.java:275)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:116)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T43 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}
```

**Comment by Bhargee** [comment]
As in  #1543, the two stacktraces are identical modulo monitor hashes and thread IDs. Again, I'm not sure what the dependency injection is doing exactly, but I don't see why two separate threads doing the same things on two different (?) objects would be in contention. Unless the dependency injection is operating between threads (I don't know how it works), I'd classify this as a false positive. @yilongli, thoughts?

**Comment by yilongli** [comment]
This one is real. Two threads are accessing the static field `DefinitionLocalKParser.resourceDomain` concurrently.
