### ISSUE TITLE
lack of synchronization when using the thread-unsafe spoofax library

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1545]
Reported by RV-Predict:

```
Data race on field org.spoofax.jsglr.client.Frame.framesCreated: {{{
    Concurrent write in thread T72 (locks held: {})
 ---->  at org.spoofax.jsglr.client.Frame.<init>(Frame.java:40)
        at org.spoofax.jsglr.client.SGLR.newStack(SGLR.java:888)
        at org.spoofax.jsglr.client.SGLR.initActiveStacks(SGLR.java:248)
        at org.spoofax.jsglr.client.SGLR.initParseVariables(SGLR.java:373)
        at org.spoofax.jsglr.client.SGLR.parse(SGLR.java:293)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.doParse(STRSGLR_parse_string_pt.java:145)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.call(STRSGLR_parse_string_pt.java:99)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.jsglr_parse_string_1_3.invoke(jsglr_parse_string_1_3.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.parse_string_1_3_override.invoke(parse_string_1_3_override.java:n/a)
        at org.strategoxt.stratego_sglr.parse_string_1_2.invoke(parse_string_1_2.java:n/a)
        at org.kframework.parser.concrete.lib.java$Parse$String$Pgm_0_0.invoke(java$Parse$String$Pgm_0_0.java:39)
        at org.strategoxt.lang.Strategy.invokeDynamic(Strategy.java:n/a)
        at org.strategoxt.lang.StackSaver$1.call(StackSaver.java:n/a)
    T72 is created by T51
        at org.strategoxt.lang.StackSaver.invokeStackFriendly(StackSaver.java:n/a)

    Concurrent read in thread T71 (locks held: {})
 ---->  at org.spoofax.jsglr.client.Frame.<init>(Frame.java:40)
        at org.spoofax.jsglr.client.SGLR.newStack(SGLR.java:888)
        at org.spoofax.jsglr.client.SGLR.addNewStack(SGLR.java:786)
        at org.spoofax.jsglr.client.SGLR.reducer(SGLR.java:710)
        at org.spoofax.jsglr.client.SGLR.reduceAllPaths(SGLR.java:666)
        at org.spoofax.jsglr.client.SGLR.doReductions(SGLR.java:621)
        at org.spoofax.jsglr.client.SGLR.actor(SGLR.java:532)
        at org.spoofax.jsglr.client.SGLR.parseCharacter(SGLR.java:478)
        at org.spoofax.jsglr.client.SGLR.doParseStep(SGLR.java:364)
        at org.spoofax.jsglr.client.SGLR.sglrParse(SGLR.java:308)
        at org.spoofax.jsglr.client.SGLR.parse(SGLR.java:297)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.doParse(STRSGLR_parse_string_pt.java:145)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.call(STRSGLR_parse_string_pt.java:99)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.jsglr_parse_string_1_3.invoke(jsglr_parse_string_1_3.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.parse_string_1_3_override.invoke(parse_string_1_3_override.java:n/a)
        at org.strategoxt.stratego_sglr.parse_string_1_2.invoke(parse_string_1_2.java:n/a)
        at org.kframework.parser.concrete.lib.java$Parse$String$Pgm_0_0.invoke(java$Parse$String$Pgm_0_0.java:39)
        at org.strategoxt.lang.Strategy.invokeDynamic(Strategy.java:n/a)
        at org.strategoxt.lang.StackSaver$1.call(StackSaver.java:n/a)
    T71 is created by T43
        at org.strategoxt.lang.StackSaver.invokeStackFriendly(StackSaver.java:n/a)
}}}

Data race on field org.spoofax.jsglr.client.PooledPathList.maxRemembered: {{{
    Concurrent read in thread T71 (locks held: {Monitor@4e49f554})
 ---->  at org.spoofax.jsglr.client.PooledPathList.reset(PooledPathList.java:107)
        - locked Monitor@4e49f554 at org.spoofax.jsglr.client.PathListPool.endCreate(PathListPool.java:58) 
        at org.spoofax.jsglr.client.SGLR.doReductions(SGLR.java:624)
        at org.spoofax.jsglr.client.SGLR.actor(SGLR.java:532)
        at org.spoofax.jsglr.client.SGLR.parseCharacter(SGLR.java:478)
        at org.spoofax.jsglr.client.SGLR.doParseStep(SGLR.java:364)
        at org.spoofax.jsglr.client.SGLR.sglrParse(SGLR.java:308)
        at org.spoofax.jsglr.client.SGLR.parse(SGLR.java:297)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.doParse(STRSGLR_parse_string_pt.java:145)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.call(STRSGLR_parse_string_pt.java:99)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.jsglr_parse_string_1_3.invoke(jsglr_parse_string_1_3.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.parse_string_1_3_override.invoke(parse_string_1_3_override.java:n/a)
        at org.strategoxt.stratego_sglr.parse_string_1_2.invoke(parse_string_1_2.java:n/a)
        at org.kframework.parser.concrete.lib.java$Parse$String$Pgm_0_0.invoke(java$Parse$String$Pgm_0_0.java:39)
        at org.strategoxt.lang.Strategy.invokeDynamic(Strategy.java:n/a)
        at org.strategoxt.lang.StackSaver$1.call(StackSaver.java:n/a)
    T71 is created by T43
        at org.strategoxt.lang.StackSaver.invokeStackFriendly(StackSaver.java:n/a)

    Concurrent write in thread T72 (locks held: {})
 ---->  at org.spoofax.jsglr.client.PooledPathList.resetPerformanceCounters(PooledPathList.java:102)
        at org.spoofax.jsglr.client.imploder.TreeBuilder.reset(TreeBuilder.java:166)
        at org.spoofax.jsglr.client.imploder.TreeBuilder.initializeInput(TreeBuilder.java:117)
        at org.spoofax.jsglr.client.SGLR.initParseVariables(SGLR.java:380)
        at org.spoofax.jsglr.client.SGLR.parse(SGLR.java:293)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.doParse(STRSGLR_parse_string_pt.java:145)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.call(STRSGLR_parse_string_pt.java:99)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.jsglr_parse_string_1_3.invoke(jsglr_parse_string_1_3.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.parse_string_1_3_override.invoke(parse_string_1_3_override.java:n/a)
        at org.strategoxt.stratego_sglr.parse_string_1_2.invoke(parse_string_1_2.java:n/a)
        at org.kframework.parser.concrete.lib.java$Parse$String$Pgm_0_0.invoke(java$Parse$String$Pgm_0_0.java:39)
        at org.strategoxt.lang.Strategy.invokeDynamic(Strategy.java:n/a)
        at org.strategoxt.lang.StackSaver$1.call(StackSaver.java:n/a)
    T72 is created by T51
        at org.strategoxt.lang.StackSaver.invokeStackFriendly(StackSaver.java:n/a)
}}}

Data race on field org.spoofax.jsglr.client.Link.linksCreated: {{{
    Concurrent write in thread T74 (locks held: {})
 ---->  at org.spoofax.jsglr.client.Link.<init>(Link.java:37)
        at org.spoofax.jsglr.client.Frame.addLink(Frame.java:132)
        at org.spoofax.jsglr.client.SGLR.shifter(SGLR.java:448)
        at org.spoofax.jsglr.client.SGLR.doParseStep(SGLR.java:365)
        at org.spoofax.jsglr.client.SGLR.sglrParse(SGLR.java:308)
        at org.spoofax.jsglr.client.SGLR.parse(SGLR.java:297)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.doParse(STRSGLR_parse_string_pt.java:145)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.call(STRSGLR_parse_string_pt.java:99)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.jsglr_parse_string_1_3.invoke(jsglr_parse_string_1_3.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.parse_string_1_3_override.invoke(parse_string_1_3_override.java:n/a)
        at org.strategoxt.stratego_sglr.parse_string_1_2.invoke(parse_string_1_2.java:n/a)
        at org.kframework.parser.concrete.lib.java$Parse$String$Pgm_0_0.invoke(java$Parse$String$Pgm_0_0.java:39)
        at org.strategoxt.lang.Strategy.invokeDynamic(Strategy.java:n/a)
        at org.strategoxt.lang.StackSaver$1.call(StackSaver.java:n/a)
    T74 is created by T57
        at org.strategoxt.lang.StackSaver.invokeStackFriendly(StackSaver.java:n/a)

    Concurrent read in thread T71 (locks held: {})
 ---->  at org.spoofax.jsglr.client.Link.<init>(Link.java:37)
        at org.spoofax.jsglr.client.Frame.addLink(Frame.java:132)
        at org.spoofax.jsglr.client.SGLR.reducer(SGLR.java:731)
        at org.spoofax.jsglr.client.SGLR.reduceAllPaths(SGLR.java:666)
        at org.spoofax.jsglr.client.SGLR.doReductions(SGLR.java:621)
        at org.spoofax.jsglr.client.SGLR.actor(SGLR.java:532)
        at org.spoofax.jsglr.client.SGLR.parseCharacter(SGLR.java:478)
        at org.spoofax.jsglr.client.SGLR.doParseStep(SGLR.java:364)
        at org.spoofax.jsglr.client.SGLR.sglrParse(SGLR.java:308)
        at org.spoofax.jsglr.client.SGLR.parse(SGLR.java:297)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.doParse(STRSGLR_parse_string_pt.java:145)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.call(STRSGLR_parse_string_pt.java:99)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.jsglr_parse_string_1_3.invoke(jsglr_parse_string_1_3.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.parse_string_1_3_override.invoke(parse_string_1_3_override.java:n/a)
        at org.strategoxt.stratego_sglr.parse_string_1_2.invoke(parse_string_1_2.java:n/a)
        at org.kframework.parser.concrete.lib.java$Parse$String$Pgm_0_0.invoke(java$Parse$String$Pgm_0_0.java:39)
        at org.strategoxt.lang.Strategy.invokeDynamic(Strategy.java:n/a)
        at org.strategoxt.lang.StackSaver$1.call(StackSaver.java:n/a)
    T71 is created by T43
        at org.strategoxt.lang.StackSaver.invokeStackFriendly(StackSaver.java:n/a)
}}}

Data race on field org.spoofax.jsglr.client.PooledPathList.maxAllocated: {{{
    Concurrent read in thread T71 (locks held: {Monitor@4e49f554})
 ---->  at org.spoofax.jsglr.client.PooledPathList.reset(PooledPathList.java:108)
        at org.spoofax.jsglr.client.PathListPool.endCreate(PathListPool.java:59)
        - locked Monitor@4e49f554 at org.spoofax.jsglr.client.PathListPool.endCreate(PathListPool.java:58) 
        at org.spoofax.jsglr.client.SGLR.doReductions(SGLR.java:624)
        at org.spoofax.jsglr.client.SGLR.actor(SGLR.java:532)
        at org.spoofax.jsglr.client.SGLR.parseCharacter(SGLR.java:478)
        at org.spoofax.jsglr.client.SGLR.doParseStep(SGLR.java:364)
        at org.spoofax.jsglr.client.SGLR.sglrParse(SGLR.java:308)
        at org.spoofax.jsglr.client.SGLR.parse(SGLR.java:297)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.doParse(STRSGLR_parse_string_pt.java:145)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.call(STRSGLR_parse_string_pt.java:99)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.jsglr_parse_string_1_3.invoke(jsglr_parse_string_1_3.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.parse_string_1_3_override.invoke(parse_string_1_3_override.java:n/a)
        at org.strategoxt.stratego_sglr.parse_string_1_2.invoke(parse_string_1_2.java:n/a)
        at org.kframework.parser.concrete.lib.java$Parse$String$Pgm_0_0.invoke(java$Parse$String$Pgm_0_0.java:39)
        at org.strategoxt.lang.Strategy.invokeDynamic(Strategy.java:n/a)
        at org.strategoxt.lang.StackSaver$1.call(StackSaver.java:n/a)
    T71 is created by T43
        at org.strategoxt.lang.StackSaver.invokeStackFriendly(StackSaver.java:n/a)

    Concurrent write in thread T73 (locks held: {})
 ---->  at org.spoofax.jsglr.client.PooledPathList.resetPerformanceCounters(PooledPathList.java:103)
        at org.spoofax.jsglr.client.SGLR.initParseVariables(SGLR.java:381)
        at org.spoofax.jsglr.client.SGLR.parse(SGLR.java:293)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.doParse(STRSGLR_parse_string_pt.java:145)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.call(STRSGLR_parse_string_pt.java:99)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.jsglr_parse_string_1_3.invoke(jsglr_parse_string_1_3.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.parse_string_1_3_override.invoke(parse_string_1_3_override.java:n/a)
        at org.strategoxt.stratego_sglr.parse_string_1_2.invoke(parse_string_1_2.java:n/a)
        at org.kframework.parser.concrete.lib.java$Parse$String$Pgm_0_0.invoke(java$Parse$String$Pgm_0_0.java:39)
        at org.strategoxt.lang.Strategy.invokeDynamic(Strategy.java:n/a)
        at org.strategoxt.lang.StackSaver$1.call(StackSaver.java:n/a)
    T73 is created by T52
        at org.strategoxt.lang.StackSaver.invokeStackFriendly(StackSaver.java:n/a)
}}}

Data race on field org.spoofax.jsglr.client.PooledPathList.maxAllocated: {{{
    Concurrent write in thread T74 (locks held: {Monitor@7e8901e6})
 ---->  at org.spoofax.jsglr.client.PooledPathList.reset(PooledPathList.java:108)
        at org.spoofax.jsglr.client.PathListPool.endCreate(PathListPool.java:59)
        - locked Monitor@7e8901e6 at org.spoofax.jsglr.client.PathListPool.endCreate(PathListPool.java:58) 
        at org.spoofax.jsglr.client.SGLR.doReductions(SGLR.java:624)
        at org.spoofax.jsglr.client.SGLR.actor(SGLR.java:532)
        at org.spoofax.jsglr.client.SGLR.parseCharacter(SGLR.java:478)
        at org.spoofax.jsglr.client.SGLR.doParseStep(SGLR.java:364)
        at org.spoofax.jsglr.client.SGLR.sglrParse(SGLR.java:308)
        at org.spoofax.jsglr.client.SGLR.parse(SGLR.java:297)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.doParse(STRSGLR_parse_string_pt.java:145)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.call(STRSGLR_parse_string_pt.java:99)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.jsglr_parse_string_1_3.invoke(jsglr_parse_string_1_3.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.parse_string_1_3_override.invoke(parse_string_1_3_override.java:n/a)
        at org.strategoxt.stratego_sglr.parse_string_1_2.invoke(parse_string_1_2.java:n/a)
        at org.kframework.parser.concrete.lib.java$Parse$String$Pgm_0_0.invoke(java$Parse$String$Pgm_0_0.java:39)
        at org.strategoxt.lang.Strategy.invokeDynamic(Strategy.java:n/a)
        at org.strategoxt.lang.StackSaver$1.call(StackSaver.java:n/a)
    T74 is created by T57
        at org.strategoxt.lang.StackSaver.invokeStackFriendly(StackSaver.java:n/a)

    Concurrent read in thread T72 (locks held: {Monitor@78e5996d})
 ---->  at org.spoofax.jsglr.client.PooledPathList.reset(PooledPathList.java:108)
        at org.spoofax.jsglr.client.PathListPool.endCreate(PathListPool.java:59)
        - locked Monitor@78e5996d at org.spoofax.jsglr.client.PathListPool.endCreate(PathListPool.java:58) 
        at org.spoofax.jsglr.client.SGLR.doReductions(SGLR.java:624)
        at org.spoofax.jsglr.client.SGLR.actor(SGLR.java:532)
        at org.spoofax.jsglr.client.SGLR.parseCharacter(SGLR.java:478)
        at org.spoofax.jsglr.client.SGLR.doParseStep(SGLR.java:364)
        at org.spoofax.jsglr.client.SGLR.sglrParse(SGLR.java:308)
        at org.spoofax.jsglr.client.SGLR.parse(SGLR.java:297)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.doParse(STRSGLR_parse_string_pt.java:145)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.call(STRSGLR_parse_string_pt.java:99)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.jsglr_parse_string_1_3.invoke(jsglr_parse_string_1_3.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.parse_string_1_3_override.invoke(parse_string_1_3_override.java:n/a)
        at org.strategoxt.stratego_sglr.parse_string_1_2.invoke(parse_string_1_2.java:n/a)
        at org.kframework.parser.concrete.lib.java$Parse$String$Pgm_0_0.invoke(java$Parse$String$Pgm_0_0.java:39)
        at org.strategoxt.lang.Strategy.invokeDynamic(Strategy.java:n/a)
        at org.strategoxt.lang.StackSaver$1.call(StackSaver.java:n/a)
    T72 is created by T51
        at org.strategoxt.lang.StackSaver.invokeStackFriendly(StackSaver.java:n/a)
}}}

Data race on field org.spoofax.jsglr.client.PooledPathList.maxRemembered: {{{
    Concurrent write in thread T74 (locks held: {Monitor@7e8901e6})
 ---->  at org.spoofax.jsglr.client.PooledPathList.reset(PooledPathList.java:107)
        at org.spoofax.jsglr.client.PathListPool.endCreate(PathListPool.java:59)
        - locked Monitor@7e8901e6 at org.spoofax.jsglr.client.PathListPool.endCreate(PathListPool.java:58) 
        at org.spoofax.jsglr.client.SGLR.doReductions(SGLR.java:624)
        at org.spoofax.jsglr.client.SGLR.actor(SGLR.java:532)
        at org.spoofax.jsglr.client.SGLR.parseCharacter(SGLR.java:478)
        at org.spoofax.jsglr.client.SGLR.doParseStep(SGLR.java:364)
        at org.spoofax.jsglr.client.SGLR.sglrParse(SGLR.java:308)
        at org.spoofax.jsglr.client.SGLR.parse(SGLR.java:297)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.doParse(STRSGLR_parse_string_pt.java:145)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.call(STRSGLR_parse_string_pt.java:99)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.jsglr_parse_string_1_3.invoke(jsglr_parse_string_1_3.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.parse_string_1_3_override.invoke(parse_string_1_3_override.java:n/a)
        at org.strategoxt.stratego_sglr.parse_string_1_2.invoke(parse_string_1_2.java:n/a)
        at org.kframework.parser.concrete.lib.java$Parse$String$Pgm_0_0.invoke(java$Parse$String$Pgm_0_0.java:39)
        at org.strategoxt.lang.Strategy.invokeDynamic(Strategy.java:n/a)
        at org.strategoxt.lang.StackSaver$1.call(StackSaver.java:n/a)
    T74 is created by T57
        at org.strategoxt.lang.StackSaver.invokeStackFriendly(StackSaver.java:n/a)

    Concurrent read in thread T72 (locks held: {Monitor@78e5996d})
 ---->  at org.spoofax.jsglr.client.PooledPathList.reset(PooledPathList.java:107)
        - locked Monitor@78e5996d at org.spoofax.jsglr.client.PathListPool.endCreate(PathListPool.java:58) 
        at org.spoofax.jsglr.client.SGLR.doReductions(SGLR.java:624)
        at org.spoofax.jsglr.client.SGLR.actor(SGLR.java:532)
        at org.spoofax.jsglr.client.SGLR.parseCharacter(SGLR.java:478)
        at org.spoofax.jsglr.client.SGLR.doParseStep(SGLR.java:364)
        at org.spoofax.jsglr.client.SGLR.sglrParse(SGLR.java:308)
        at org.spoofax.jsglr.client.SGLR.parse(SGLR.java:297)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.doParse(STRSGLR_parse_string_pt.java:145)
        at org.spoofax.interpreter.library.jsglr.STRSGLR_parse_string_pt.call(STRSGLR_parse_string_pt.java:99)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.Context.invokePrimitive(Context.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.jsglr_parse_string_1_3.invoke(jsglr_parse_string_1_3.java:n/a)
        at org.strategoxt.lang.compat.override.jsglr_parser_compat.parse_string_1_3_override.invoke(parse_string_1_3_override.java:n/a)
        at org.strategoxt.stratego_sglr.parse_string_1_2.invoke(parse_string_1_2.java:n/a)
        at org.kframework.parser.concrete.lib.java$Parse$String$Pgm_0_0.invoke(java$Parse$String$Pgm_0_0.java:39)
        at org.strategoxt.lang.Strategy.invokeDynamic(Strategy.java:n/a)
        at org.strategoxt.lang.StackSaver$1.call(StackSaver.java:n/a)
    T72 is created by T51
        at org.strategoxt.lang.StackSaver.invokeStackFriendly(StackSaver.java:n/a)
}}}
```

**Comment by yilongli** [comment]
I wonder if it's worth the effort for me to investigate the race reports related to the use of spoofax library. Is this part of the code going to be removed very soon?

**Comment by yilongli** [comment]
@radumereuta @dwightguth

**Comment by dwightguth** [comment]
Not really worth dealing with; this code goes away in K 4.0.
