### ISSUE TITLE
possible data race on field org.kframework.ktest.Test.TaskQueue.lastTestFinished

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1546]
I am not sure if this one is real because I remember RV-Predict couldn't recognize the synchronization construct used by ktest. I will try to fix RV-Predict if this turns out to be a false alarm.

```
Data race on field org.kframework.ktest.Test.TaskQueue.lastTestFinished: {{{
    Concurrent write in thread T23 (locks held: {})
 ---->  at org.kframework.ktest.Test.TaskQueue.access$502(TaskQueue.java:33)
        at org.kframework.ktest.Proc.handlePgmResult(Proc.java:359)
        at org.kframework.ktest.Proc.run(Proc.java:197)
        at org.kframework.ktest.Test.TaskQueue$4.run(TaskQueue.java:341)
    T23 is created by n/a

    Concurrent read in thread T14 (locks held: {})
 ---->  at org.kframework.ktest.Test.TaskQueue.getLastTestFinished(TaskQueue.java:150)
        at org.kframework.ktest.KTestFrontEnd.run(KTestFrontEnd.java:73)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T14 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}
```

**Comment by Bhargee** [comment]
What is "TaskQueue.access$502"? I think the legitimacy of this race rests on that and the thread safety of ThreadPoolExecutor (and I assume it is, since it's in Java's concurrency package).

**Comment by dwightguth** [comment]
@yilongli looks like you are missing some stack frames again. access is like, a field read or write, but Proc.java:359 doesn't actually call anything relating to TaskQueue. Similarly, KTestFrontEnd.java:73 does not call TaskQueue.getLastTestFinished.

**Comment by yilongli** [comment]
@Bhargee "access$502" is a synthetic method generated by javac to handle field read/write from an inner class, or something alike.

@dwightguth you are right. I will fix the missing stack frames first.

**Comment by yilongli** [comment]
It turns out that I already fixed the incorrect stack frames recently. Here is the correct stacktraces:

```
Data race on field org.kframework.ktest.Test.TaskQueue.lastTestFinished: {{{
    Concurrent write in thread T20 (locks held: {})
 ---->  at org.kframework.ktest.Test.TaskQueue.access$502(TaskQueue.java:33)
        at org.kframework.ktest.Test.TaskQueue$4.run(TaskQueue.java:342)
    T20 is created by n/a

    Concurrent read in thread T14 (locks held: {})
 ---->  at org.kframework.ktest.Test.TaskQueue.getLastTestFinished(TaskQueue.java:150)
        at org.kframework.ktest.Test.TestSuite.run(TestSuite.java:49)
        at org.kframework.ktest.KTestFrontEnd.run(KTestFrontEnd.java:73)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T14 is created by T12
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}
```

**Comment by yilongli** [comment]
@dwightguth I think this one is real. `KTestQueueItem` are submitted to the common `ThreadPoolExecutor tpe` in `TaskQueue` and, thus, can run concurrently. They access `long lastTestFinished` without sychronization. While `lastTestFinished` is probably not used for synchronization purpose, reads and writes on `long` are not atomic. Declaring it as volatile should fix the problem.
