### ISSUE TITLE
--debug option of krun not recognized

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#1553]
Running K through kweb.  I just kompiled `tutorial/1_k/5_types/lesson_9.5/lambda.k`, where I added the attribute `[strict]` to the function type construct at line 23.  Then I ran krun with the options below, where I added `--debug` because a previous error message asked me to do so.  After adding it and getting the trace below, it still tells me at the end of the message below to add it.  It should not, because I've added it.

```
Running command: krun ../lesson_7/tests/exponential-type.lambda --symbolic-execution --debug
java.lang.UnsupportedOperationException: missing SMTLib translation for '_->_
    at org.kframework.backend.java.symbolic.KILtoSMTLib.transform(KILtoSMTLib.java:409)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:702)
    at org.kframework.backend.java.symbolic.KILtoSMTLib.transform(KILtoSMTLib.java:367)
    at org.kframework.backend.java.symbolic.ConjunctiveFormula.accept(ConjunctiveFormula.java:663)
    at org.kframework.backend.java.symbolic.KILtoSMTLib.translateConstraint(KILtoSMTLib.java:142)
    at org.kframework.backend.java.symbolic.SMTOperations.checkUnsat(SMTOperations.java:40)
    at org.kframework.backend.java.symbolic.ConjunctiveFormula.checkUnsat(ConjunctiveFormula.java:468)
    at org.kframework.backend.java.kil.ConstrainedTerm.unify(ConstrainedTerm.java:202)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.computeRewriteStep(SymbolicRewriter.java:166)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.rewrite(SymbolicRewriter.java:75)
    at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.conventionalRewriteRun(JavaSymbolicExecutor.java:114)
    at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:137)
    at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
    at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:168)
    at org.kframework.krun.tools.Executor$Tool.run(Executor.java:124)
    at org.kframework.krun.tools.Executor$Tool.run(Executor.java:88)
    at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
    at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:83)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:51)
    at org.kframework.main.Main.runApplication(Main.java:110)
    at org.kframework.main.Main.runApplication(Main.java:100)
    at org.kframework.main.Main.main(Main.java:52)
java.lang.UnsupportedOperationException: missing SMTLib translation for isKResult
    at org.kframework.backend.java.symbolic.KILtoSMTLib.transform(KILtoSMTLib.java:409)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:702)
    at org.kframework.backend.java.symbolic.KILtoSMTLib.transform(KILtoSMTLib.java:444)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:702)
    at org.kframework.backend.java.symbolic.KILtoSMTLib.transform(KILtoSMTLib.java:444)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:702)
    at org.kframework.backend.java.symbolic.KILtoSMTLib.transform(KILtoSMTLib.java:366)
    at org.kframework.backend.java.symbolic.ConjunctiveFormula.accept(ConjunctiveFormula.java:663)
    at org.kframework.backend.java.symbolic.KILtoSMTLib.translateConstraint(KILtoSMTLib.java:142)
    at org.kframework.backend.java.symbolic.SMTOperations.checkUnsat(SMTOperations.java:40)
    at org.kframework.backend.java.symbolic.ConjunctiveFormula.checkUnsat(ConjunctiveFormula.java:468)
    at org.kframework.backend.java.kil.ConstrainedTerm.unify(ConstrainedTerm.java:202)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.computeRewriteStep(SymbolicRewriter.java:166)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.rewrite(SymbolicRewriter.java:75)
    at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.conventionalRewriteRun(JavaSymbolicExecutor.java:114)
    at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:137)
    at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
    at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:168)
    at org.kframework.krun.tools.Executor$Tool.run(Executor.java:124)
    at org.kframework.krun.tools.Executor$Tool.run(Executor.java:88)
    at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
    at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:83)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:51)
    at org.kframework.main.Main.runApplication(Main.java:110)
    at org.kframework.main.Main.runApplication(Main.java:100)
    at org.kframework.main.Main.main(Main.java:52)
:/k/lib/native/linux64:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
java.lang.UnsatisfiedLinkError: /k/lib/native/linux64/libz3java.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /k/lib/native/linux64/libz3.so)
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1847)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1119)
    at com.microsoft.z3.Native.<clinit>(Native.java:10)
    at com.microsoft.z3.Context.<init>(Context.java:24)
    at org.kframework.backend.java.util.Z3Wrapper.checkQueryWithLibrary(Z3Wrapper.java:62)
    at org.kframework.backend.java.util.Z3Wrapper.checkQuery(Z3Wrapper.java:55)
    at org.kframework.backend.java.symbolic.SMTOperations.checkUnsat(SMTOperations.java:41)
    at org.kframework.backend.java.symbolic.ConjunctiveFormula.checkUnsat(ConjunctiveFormula.java:468)
    at org.kframework.backend.java.kil.ConstrainedTerm.unify(ConstrainedTerm.java:202)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.computeRewriteStep(SymbolicRewriter.java:166)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.rewrite(SymbolicRewriter.java:75)
    at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.conventionalRewriteRun(JavaSymbolicExecutor.java:114)
    at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:137)
    at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
    at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:168)
    at org.kframework.krun.tools.Executor$Tool.run(Executor.java:124)
    at org.kframework.krun.tools.Executor$Tool.run(Executor.java:88)
    at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
    at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:83)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:51)
    at org.kframework.main.Main.runApplication(Main.java:110)
    at org.kframework.main.Main.runApplication(Main.java:100)
    at org.kframework.main.Main.main(Main.java:52)
java.lang.UnsatisfiedLinkError: /k/lib/native/linux64/libz3java.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /k/lib/native/linux64/libz3.so)
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1847)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1119)
    at com.microsoft.z3.Native.<clinit>(Native.java:10)
    at com.microsoft.z3.Context.<init>(Context.java:24)
    at org.kframework.backend.java.util.Z3Wrapper.checkQueryWithLibrary(Z3Wrapper.java:62)
    at org.kframework.backend.java.util.Z3Wrapper.checkQuery(Z3Wrapper.java:55)
    at org.kframework.backend.java.symbolic.SMTOperations.checkUnsat(SMTOperations.java:41)
    at org.kframework.backend.java.symbolic.ConjunctiveFormula.checkUnsat(ConjunctiveFormula.java:468)
    at org.kframework.backend.java.kil.ConstrainedTerm.unify(ConstrainedTerm.java:202)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.computeRewriteStep(SymbolicRewriter.java:166)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.rewrite(SymbolicRewriter.java:75)
    at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.conventionalRewriteRun(JavaSymbolicExecutor.java:114)
    at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:137)
    at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
    at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:168)
    at org.kframework.krun.tools.Executor$Tool.run(Executor.java:124)
    at org.kframework.krun.tools.Executor$Tool.run(Executor.java:88)
    at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
    at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:83)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:51)
    at org.kframework.main.Main.runApplication(Main.java:110)
    at org.kframework.main.Main.runApplication(Main.java:100)
    at org.kframework.main.Main.main(Main.java:52)
[Error] Internal: Uncaught exception thrown of type UnsatisfiedLinkError.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
```

**Comment by omarz1** [comment]
Try `--debugger`
