### ISSUE TITLE
kore pipeline: configuration variable parser doesn't work for string values

### ISSUE THREAD

**Issue by daejunpark** [kframework/k-legacy#1566]
Given:

```
$ cat test.k
require "domains.k"

module TEST-SYNTAX
  imports STRING
  syntax Stmt ::= "run"
endmodule

module TEST
  imports TEST-SYNTAX
  configuration <T> <k> $PGM:K </k> <c> $ABC:String </c> </T>
endmodule

$ cat 1.text
run
```

Running `krun --kore` with the configuration variable option gives the following error:

```
$ krun --kore -cABC="abc" 1.test
org.kframework.utils.errorsystem.ParseFailedException: [Error] Critical: Parser returned a non-zero exit code: 113
Stdout:

Stderr:
[Error] Inner Parser: Parse error: unexpected end of file.
    Source(<command line: -e>)
    Location(1,4,1,5)

    at org.kframework.krun.KRun.externalParse(KRun.java:179)
    at org.kframework.krun.KRun.parseConfigVars(KRun.java:149)
    at org.kframework.krun.KRun.run(KRun.java:64)
    at org.kframework.krun.KRunFrontEnd$NewKRunFrontEnd.run(KRunFrontEnd.java:107)
    at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:123)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
    at org.kframework.main.Main.runApplication(Main.java:109)
    at org.kframework.main.Main.runApplication(Main.java:99)
    at org.kframework.main.Main.main(Main.java:51)
[Error] Critical: Parser returned a non-zero exit code: 113
Stdout:

Stderr:
[Error] Inner Parser: Parse error: unexpected end of file.
    Source(<command line: -e>)
    Location(1,4,1,5)
```

Which boils down into:

```
$ KRUN_SORT=K KRUN_COMPILED_DEF=`pwd` kast --kore -m LANGUAGE-PARSING -e "abc"
[Error] Inner Parser: Parse error: unexpected end of file.
    Source(<command line: -e>)
    Location(1,4,1,5)
```

Tested in the current master commit: ce65e384026ddb71d3f1358db26750e572d113c3

NOTE: I suspect that the enclosing quote is stripped somewhere.

**Comment by dwightguth** [comment]
If you are running `krun --kore -cABC="abc" 1.test` from the shell, then this is expected behavior. Double quotes are a shell metacharacter used to separate words in a command, and so what you are actually running is the command [krun, --kore, -cABC=abc, 1.test]. Try the following command:

`krun --kore -cABC=\"abc\" 1.test`

**Comment by daejunpark** [comment]
I made mistake in writing a github msg. What I wanted is "\"abc\"", which still doesn't work.

**Comment by dwightguth** [comment]
Can you confirm whether the problem is occurring in krun or kast?

**Comment by radumereuta** [comment]
I tried this:

```
d:\work\test>kast --kore --sort String a.test
#token("\"abc\"","String")
d:\work\test>cat a.test
"abc"
```

Worked as expected on windows. Then I tried this:

```
d:\work\test>kast --kore -e "\"abc\"" --sort String
[Error] Inner Parser: Parse error: unexpected character 'a'.
        Source(<command line: -e>)
        Location(1,1,1,2)
```

So as @dwightguth noticed, I think it's a problem of how to transmit double quotes from command line, since the shell seems to evaluate them and strip them somehow.

**Comment by daejunpark** [comment]
I don't think it is a command line issue, since I checked the proper value is used in a process builder. I suspect the option `-e` may do something wrong.
