### ISSUE TITLE
[kore] Parsing failed for List with empty separator

### ISSUE THREAD

**Issue by daejunpark** [kframework/k-legacy#1575]
_[Already reported to @radumereuta but just for tracking purpose.]_

For the following definition minimized from IMP++:

```
  1 require "domains.k"                                                                                                               
  2                                                                                                                                   
  3 module T-SYNTAX                                                                                                                   
  4   syntax BExp                                                                                                                     
  5   syntax Block ::= "{" Stmts "}"                                                                                                  
  6   syntax Stmt  ::= Block                                                                                                          
  7                  | "if" "(" BExp ")" Block "else" Block                                                                           
  8                  | "while" "(" BExp ")" Block                                                                                     
  9   syntax Stmts ::= List{Stmt,""}
 10 endmodule                                                                                                                         
 11                                                                                                                                   
 12 module T                                                                                                                          
 13   imports T-SYNTAX
 14   configuration <T> <k> $PGM:K </k> </T>
 15   rule while (B) S => if (B) {S while (B) S} else {.Stmts}  [structural]
 16 endmodule
```

Parsing got stuck at line 15 since it failed to recognize `S` and `while (B) S` are separated by `""`.

```
org.kframework.utils.errorsystem.KEMException: [Error] Compiler: Had 1 parsing errors.
    at org.kframework.utils.errorsystem.KEMException.create(KEMException.java:97)
    at org.kframework.utils.errorsystem.KEMException.compilerError(KEMException.java:63)
    at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:254)
    at org.kframework.kompile.Kompile.run(Kompile.java:125)
    at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:89)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
    at org.kframework.main.Main.runApplication(Main.java:109)
    at org.kframework.main.Main.runApplication(Main.java:99)
    at org.kframework.main.Main.main(Main.java:51)
[Error] Compiler: Had 1 parsing errors.
[Error] Inner Parser: Parse error: unexpected character '}'.
    Source(/Users/daejunpark/kore/tmp/././t.k)
    Location(15,44,15,45)
```

Notes:
- If we have `{S S}` instead of `{S while (B) S}`, it works.
- If we have `List{Stmt, ","}` instead of `""` as the list separator, it works.

**Comment by bmmoore** [comment]
Did you try parsing with `kast --kore -s Stmts`? I saw that working on a similar example, even if `kast --kore` failed. This may be related to #1589

**Comment by bmmoore** [comment]
I wonder if the empty string is getting an automatic follow restriction.
