### ISSUE TITLE
several data races inside org.fusesource.jansi.AnsiOutputStream

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1599]
I get a bunch of race reports inside the class `AnsiOutputStream` when I accidentally do a ktest on an out-dated kompiled definition:

```
Data race on field org.fusesource.jansi.AnsiOutputStream.pos: {{{
    Concurrent write in thread T22 (locks held: {})
 ---->  at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:117)
        at com.martiansoftware.nailgun.ThreadLocalPrintStream.print(ThreadLocalPrintStream.java:156)
        at org.kframework.ktest.Proc.handlePgmResult(Proc.java:387)
        at org.kframework.ktest.Proc.run(Proc.java:197)
        at org.kframework.ktest.Test.TaskQueue$4.run(TaskQueue.java:341)
    T22 is created by T15
        at com.runtimeverification.rvpredict.runtime.java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:1010)

    Concurrent read in thread T23 (locks held: {})
 ---->  at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:195)
        at com.martiansoftware.nailgun.ThreadLocalPrintStream.print(ThreadLocalPrintStream.java:156)
        at org.kframework.ktest.Proc.handlePgmResult(Proc.java:387)
        at org.kframework.ktest.Proc.run(Proc.java:197)
        at org.kframework.ktest.Test.TaskQueue$4.run(TaskQueue.java:341)
    T23 is created by T15
        at com.runtimeverification.rvpredict.runtime.java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:1010)
}}}

Data race on field org.fusesource.jansi.AnsiOutputStream.state: {{{
    Concurrent write in thread T23 (locks held: {})
 ---->  at org.fusesource.jansi.AnsiOutputStream.reset(AnsiOutputStream.java:212)
        at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:125)
        at com.martiansoftware.nailgun.ThreadLocalPrintStream.print(ThreadLocalPrintStream.java:156)
        at org.kframework.ktest.Proc.handlePgmResult(Proc.java:387)
        at org.kframework.ktest.Proc.run(Proc.java:197)
        at org.kframework.ktest.Test.TaskQueue$4.run(TaskQueue.java:341)
    T23 is created by T15
        at com.runtimeverification.rvpredict.runtime.java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:1010)

    Concurrent read in thread T22 (locks held: {})
 ---->  at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:76)
        at com.martiansoftware.nailgun.ThreadLocalPrintStream.print(ThreadLocalPrintStream.java:156)
        at org.kframework.ktest.Proc.handlePgmResult(Proc.java:387)
        at org.kframework.ktest.Proc.run(Proc.java:197)
        at org.kframework.ktest.Test.TaskQueue$4.run(TaskQueue.java:341)
    T22 is created by T15
        at com.runtimeverification.rvpredict.runtime.java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:1010)
}}}

Data race on field org.fusesource.jansi.AnsiOutputStream.state: {{{
    Concurrent read in thread T22 (locks held: {})
 ---->  at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:76)
        at com.martiansoftware.nailgun.ThreadLocalPrintStream.print(ThreadLocalPrintStream.java:156)
        at org.kframework.ktest.Proc.handlePgmResult(Proc.java:387)
        at org.kframework.ktest.Proc.run(Proc.java:197)
        at org.kframework.ktest.Test.TaskQueue$4.run(TaskQueue.java:341)
    T22 is created by T15
        at com.runtimeverification.rvpredict.runtime.java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:1010)

    Concurrent write in thread T23 (locks held: {})
 ---->  at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:80)
        at com.martiansoftware.nailgun.ThreadLocalPrintStream.print(ThreadLocalPrintStream.java:156)
        at org.kframework.ktest.Proc.handlePgmResult(Proc.java:387)
        at org.kframework.ktest.Proc.run(Proc.java:197)
        at org.kframework.ktest.Test.TaskQueue$4.run(TaskQueue.java:341)
    T23 is created by T15
        at com.runtimeverification.rvpredict.runtime.java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:1010)
}}}

Data race on field org.fusesource.jansi.AnsiOutputStream.state: {{{
    Concurrent write in thread T23 (locks held: {})
 ---->  at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:104)
        at com.martiansoftware.nailgun.ThreadLocalPrintStream.print(ThreadLocalPrintStream.java:156)
        at org.kframework.ktest.Proc.handlePgmResult(Proc.java:387)
        at org.kframework.ktest.Proc.run(Proc.java:197)
        at org.kframework.ktest.Test.TaskQueue$4.run(TaskQueue.java:341)
    T23 is created by T15
        at com.runtimeverification.rvpredict.runtime.java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:1010)

    Concurrent read in thread T22 (locks held: {})
 ---->  at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:76)
        at com.martiansoftware.nailgun.ThreadLocalPrintStream.print(ThreadLocalPrintStream.java:156)
        at org.kframework.ktest.Proc.handlePgmResult(Proc.java:387)
        at org.kframework.ktest.Proc.run(Proc.java:197)
        at org.kframework.ktest.Test.TaskQueue$4.run(TaskQueue.java:341)
    T22 is created by T15
        at com.runtimeverification.rvpredict.runtime.java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:1010)
}}}

Data race on field org.fusesource.jansi.AnsiOutputStream.state: {{{
    Concurrent read in thread T22 (locks held: {})
 ---->  at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:76)
        at com.martiansoftware.nailgun.ThreadLocalPrintStream.print(ThreadLocalPrintStream.java:156)
        at org.kframework.ktest.Proc.handlePgmResult(Proc.java:387)
        at org.kframework.ktest.Proc.run(Proc.java:197)
        at org.kframework.ktest.Test.TaskQueue$4.run(TaskQueue.java:341)
    T22 is created by T15
        at com.runtimeverification.rvpredict.runtime.java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:1010)

    Concurrent write in thread T23 (locks held: {})
 ---->  at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:89)
        at com.martiansoftware.nailgun.ThreadLocalPrintStream.print(ThreadLocalPrintStream.java:156)
        at org.kframework.ktest.Proc.handlePgmResult(Proc.java:387)
        at org.kframework.ktest.Proc.run(Proc.java:197)
        at org.kframework.ktest.Test.TaskQueue$4.run(TaskQueue.java:341)
    T23 is created by T15
        at com.runtimeverification.rvpredict.runtime.java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:1010)
}}}

Data race on field org.fusesource.jansi.AnsiOutputStream.pos: {{{
    Concurrent read in thread T23 (locks held: {})
 ---->  at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:195)
        at com.martiansoftware.nailgun.ThreadLocalPrintStream.print(ThreadLocalPrintStream.java:156)
        at org.kframework.ktest.Proc.handlePgmResult(Proc.java:387)
        at org.kframework.ktest.Proc.run(Proc.java:197)
        at org.kframework.ktest.Test.TaskQueue$4.run(TaskQueue.java:341)
    T23 is created by T15
        at com.runtimeverification.rvpredict.runtime.java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:1010)

    Concurrent write in thread T22 (locks held: {})
 ---->  at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:79)
        at com.martiansoftware.nailgun.ThreadLocalPrintStream.print(ThreadLocalPrintStream.java:156)
        at org.kframework.ktest.Proc.handlePgmResult(Proc.java:387)
        at org.kframework.ktest.Proc.run(Proc.java:197)
        at org.kframework.ktest.Test.TaskQueue$4.run(TaskQueue.java:341)
    T22 is created by T15
        at com.runtimeverification.rvpredict.runtime.java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:1010)
}}}

Data race on field org.fusesource.jansi.AnsiOutputStream.pos: {{{
    Concurrent read in thread T23 (locks held: {})
 ---->  at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:195)
        at com.martiansoftware.nailgun.ThreadLocalPrintStream.print(ThreadLocalPrintStream.java:156)
        at org.kframework.ktest.Proc.handlePgmResult(Proc.java:387)
        at org.kframework.ktest.Proc.run(Proc.java:197)
        at org.kframework.ktest.Test.TaskQueue$4.run(TaskQueue.java:341)
    T23 is created by T15
        at com.runtimeverification.rvpredict.runtime.java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:1010)

    Concurrent write in thread T22 (locks held: {})
 ---->  at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:98)
        at com.martiansoftware.nailgun.ThreadLocalPrintStream.print(ThreadLocalPrintStream.java:156)
        at org.kframework.ktest.Proc.handlePgmResult(Proc.java:387)
        at org.kframework.ktest.Proc.run(Proc.java:197)
        at org.kframework.ktest.Test.TaskQueue$4.run(TaskQueue.java:341)
    T22 is created by T15
        at com.runtimeverification.rvpredict.runtime.java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:1010)
}}}

Data race on field org.fusesource.jansi.AnsiOutputStream.pos: {{{
    Concurrent write in thread T22 (locks held: {})
 ---->  at org.fusesource.jansi.AnsiOutputStream.reset(AnsiOutputStream.java:209)
        at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:125)
        at com.martiansoftware.nailgun.ThreadLocalPrintStream.print(ThreadLocalPrintStream.java:156)
        at org.kframework.ktest.Proc.handlePgmResult(Proc.java:387)
        at org.kframework.ktest.Proc.run(Proc.java:197)
        at org.kframework.ktest.Test.TaskQueue$4.run(TaskQueue.java:341)
    T22 is created by T15
        at com.runtimeverification.rvpredict.runtime.java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:1010)

    Concurrent read in thread T23 (locks held: {})
 ---->  at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:195)
        at com.martiansoftware.nailgun.ThreadLocalPrintStream.print(ThreadLocalPrintStream.java:156)
        at org.kframework.ktest.Proc.handlePgmResult(Proc.java:387)
        at org.kframework.ktest.Proc.run(Proc.java:197)
        at org.kframework.ktest.Test.TaskQueue$4.run(TaskQueue.java:341)
    T23 is created by T15
        at com.runtimeverification.rvpredict.runtime.java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:1010)
}}}

Data race on field org.fusesource.jansi.AnsiOutputStream.pos: {{{
    Concurrent read in thread T23 (locks held: {})
 ---->  at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:195)
        at com.martiansoftware.nailgun.ThreadLocalPrintStream.print(ThreadLocalPrintStream.java:156)
        at org.kframework.ktest.Proc.handlePgmResult(Proc.java:387)
        at org.kframework.ktest.Proc.run(Proc.java:197)
        at org.kframework.ktest.Test.TaskQueue$4.run(TaskQueue.java:341)
    T23 is created by T15
        at com.runtimeverification.rvpredict.runtime.java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:1010)

    Concurrent write in thread T22 (locks held: {})
 ---->  at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:87)
        at com.martiansoftware.nailgun.ThreadLocalPrintStream.print(ThreadLocalPrintStream.java:156)
        at org.kframework.ktest.Proc.handlePgmResult(Proc.java:387)
        at org.kframework.ktest.Proc.run(Proc.java:197)
        at org.kframework.ktest.Test.TaskQueue$4.run(TaskQueue.java:341)
    T22 is created by T15
        at com.runtimeverification.rvpredict.runtime.java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:1010)
}}}
```

I think the problem is that Nailgun's `ThreadLocalPrintStream` is using `InheritableThreadLocal` to store [streams](https://github.com/martylamb/nailgun/blob/master/nailgun-server/src/main/java/com/martiansoftware/nailgun/ThreadLocalPrintStream.java#L40), but we didn't take that into account when [setting up the output streams](https://github.com/kframework/k/blob/1a8cf3556b2b98dc3090b9af295668c524d65958/kernel/src/main/java/org/kframework/kserver/KServerFrontEnd.java#L96). What do you think? @dwightguth

**Comment by dwightguth** [comment]
So, it's possible this is the cause, but I'm not entirely sure what to do about it because it's fairly important for functional correctness that multiple threads corresponding to the same nailgun request access the same output stream object. Do you have a suggestion?

**Comment by yilongli** [comment]
Maybe we can implement a thread-safe wrapper that extends PrintStream (or OutputStream?) and then put the AnsiOutputStream inside?
