### ISSUE TITLE
data race on org.kframework.kil.KLabelConstant.cache

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1601]
This one is particularly harmful:

```
Data race on field java.util.HashMap.$state: {{{
    Concurrent write in thread T50 (locks held: {Monitor@73aaa78b})
 ---->  at org.kframework.kil.KLabelConstant.of(KLabelConstant.java:60)
        at org.kframework.compile.transformers.FlattenTerms$FlattenKSyntax.visit(FlattenTerms.java:128)
        at org.kframework.kil.TermCons.accept(TermCons.java:112)
        at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:103)
        at org.kframework.compile.transformers.FlattenTerms$FlattenKSyntax.visit(FlattenTerms.java:121)
        at org.kframework.kil.TermCons.accept(TermCons.java:112)
        at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:103)
        at org.kframework.compile.transformers.FlattenTerms$FlattenKSyntax.visit(FlattenTerms.java:121)
        at org.kframework.kil.TermCons.accept(TermCons.java:112)
        at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:103)
        at org.kframework.compile.transformers.FlattenTerms$FlattenKSyntax.visit(FlattenTerms.java:121)
        at org.kframework.kil.TermCons.accept(TermCons.java:112)
        at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:103)
        at org.kframework.compile.transformers.FlattenTerms$FlattenKSyntax.visit(FlattenTerms.java:121)
        at org.kframework.kil.TermCons.accept(TermCons.java:112)
        at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:103)
        at org.kframework.compile.transformers.FlattenTerms.visit(FlattenTerms.java:54)
        at org.kframework.kil.TermCons.accept(TermCons.java:112)
        at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:103)
        at org.kframework.parser.ProgramLoader.loadPgmAst(ProgramLoader.java:105)
        at org.kframework.parser.ProgramLoader.loadPgmAst(ProgramLoader.java:111)
        at org.kframework.parser.ProgramLoader.processPgm(ProgramLoader.java:169)
        at org.kframework.krun.RunProcess.runParser(RunProcess.java:132)
        at org.kframework.krun.InitialConfigurationProvider.get(InitialConfigurationProvider.java:89)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
        at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:73)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:63)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at org.kframework.utils.inject.SimpleScope$2.get(SimpleScope.java:99)
        - locked Monitor@73aaa78b at org.kframework.utils.inject.SimpleScope$2.get(SimpleScope.java:95) 
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.ExposedKeyFactory.get(ExposedKeyFactory.java:54)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:94)
        at com.google.inject.throwingproviders.ThrowingProviderBinder$SecondaryBinder$3.get(ThrowingProviderBinder.java:292)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:94)
        at com.google.inject.throwingproviders.ThrowingProviderBinder$SecondaryBinder$2$1.invoke(ThrowingProviderBinder.java:275)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:129)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
    T50 is created by T13
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)

    Concurrent read in thread T48 (locks held: {Monitor@5e894af0})
 ---->  at org.kframework.kil.KLabelConstant.of(KLabelConstant.java:60)
        at org.kframework.compile.transformers.FlattenTerms$FlattenKSyntax.visit(FlattenTerms.java:128)
        at org.kframework.kil.TermCons.accept(TermCons.java:112)
        at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:103)
        at org.kframework.compile.transformers.FlattenTerms$FlattenKSyntax.visit(FlattenTerms.java:121)
        at org.kframework.kil.TermCons.accept(TermCons.java:112)
        at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:103)
        at org.kframework.compile.transformers.FlattenTerms$FlattenKSyntax.visit(FlattenTerms.java:121)
        at org.kframework.kil.TermCons.accept(TermCons.java:112)
        at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:103)
        at org.kframework.compile.transformers.FlattenTerms$FlattenKSyntax.visit(FlattenTerms.java:121)
        at org.kframework.kil.TermCons.accept(TermCons.java:112)
        at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:103)
        at org.kframework.compile.transformers.FlattenTerms$FlattenKSyntax.visit(FlattenTerms.java:121)
        at org.kframework.kil.TermCons.accept(TermCons.java:112)
        at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:103)
        at org.kframework.compile.transformers.FlattenTerms$FlattenKSyntax.visit(FlattenTerms.java:121)
        at org.kframework.kil.TermCons.accept(TermCons.java:112)
        at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:103)
        at org.kframework.compile.transformers.FlattenTerms.visit(FlattenTerms.java:54)
        at org.kframework.kil.TermCons.accept(TermCons.java:112)
        at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:103)
        at org.kframework.parser.ProgramLoader.loadPgmAst(ProgramLoader.java:105)
        at org.kframework.parser.ProgramLoader.loadPgmAst(ProgramLoader.java:111)
        at org.kframework.parser.ProgramLoader.processPgm(ProgramLoader.java:169)
        at org.kframework.krun.RunProcess.runParser(RunProcess.java:132)
        at org.kframework.krun.InitialConfigurationProvider.get(InitialConfigurationProvider.java:89)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
        at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:73)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:63)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at org.kframework.utils.inject.SimpleScope$2.get(SimpleScope.java:99)
        - locked Monitor@5e894af0 at org.kframework.utils.inject.SimpleScope$2.get(SimpleScope.java:95) 
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.ExposedKeyFactory.get(ExposedKeyFactory.java:54)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:94)
        at com.google.inject.throwingproviders.ThrowingProviderBinder$SecondaryBinder$3.get(ThrowingProviderBinder.java:292)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:94)
        at com.google.inject.throwingproviders.ThrowingProviderBinder$SecondaryBinder$2$1.invoke(ThrowingProviderBinder.java:275)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:129)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
    T48 is created by T13
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}
```

**Comment by yilongli** [comment]
One more similar report on `GenericToken.kAppCache`:

```
Data race on field java.util.HashMap.$state: {{{
    Concurrent read in thread T50 (locks held: {Monitor@73aaa78b})
 ---->  at org.kframework.kil.GenericToken.kAppOf(GenericToken.java:48)
        at org.kframework.parser.concrete.disambiguate.NormalizeASTTransformer.visit(NormalizeASTTransformer.java:59)
        at org.kframework.kil.TermCons.accept(TermCons.java:112)
        at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:95)
        at org.kframework.kil.AbstractVisitor.genericVisitList(AbstractVisitor.java:146)
        at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:793)
        at org.kframework.parser.concrete.disambiguate.NormalizeASTTransformer.visit(NormalizeASTTransformer.java:63)
        at org.kframework.kil.TermCons.accept(TermCons.java:112)
        at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:103)
        at org.kframework.parser.ProgramLoader.loadPgmAst(ProgramLoader.java:100)
        at org.kframework.parser.ProgramLoader.loadPgmAst(ProgramLoader.java:111)
        at org.kframework.parser.ProgramLoader.processPgm(ProgramLoader.java:169)
        at org.kframework.krun.RunProcess.runParser(RunProcess.java:132)
        at org.kframework.krun.InitialConfigurationProvider.get(InitialConfigurationProvider.java:89)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
        at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:73)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:63)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at org.kframework.utils.inject.SimpleScope$2.get(SimpleScope.java:99)
        - locked Monitor@73aaa78b at org.kframework.utils.inject.SimpleScope$2.get(SimpleScope.java:95) 
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.ExposedKeyFactory.get(ExposedKeyFactory.java:54)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:94)
        at com.google.inject.throwingproviders.ThrowingProviderBinder$SecondaryBinder$3.get(ThrowingProviderBinder.java:292)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:94)
        at com.google.inject.throwingproviders.ThrowingProviderBinder$SecondaryBinder$2$1.invoke(ThrowingProviderBinder.java:275)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:129)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
    T50 is created by T13
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)

    Concurrent write in thread T49 (locks held: {Monitor@5a3a1dd0})
 ---->  at org.kframework.kil.GenericToken.kAppOf(GenericToken.java:51)
        at org.kframework.parser.concrete.disambiguate.NormalizeASTTransformer.visit(NormalizeASTTransformer.java:59)
        at org.kframework.kil.TermCons.accept(TermCons.java:112)
        at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:95)
        at org.kframework.kil.AbstractVisitor.genericVisitList(AbstractVisitor.java:146)
        at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:793)
        at org.kframework.parser.concrete.disambiguate.NormalizeASTTransformer.visit(NormalizeASTTransformer.java:63)
        at org.kframework.kil.TermCons.accept(TermCons.java:112)
        at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:103)
        at org.kframework.parser.ProgramLoader.loadPgmAst(ProgramLoader.java:100)
        at org.kframework.parser.ProgramLoader.loadPgmAst(ProgramLoader.java:111)
        at org.kframework.parser.ProgramLoader.processPgm(ProgramLoader.java:169)
        at org.kframework.krun.RunProcess.runParser(RunProcess.java:132)
        at org.kframework.krun.InitialConfigurationProvider.get(InitialConfigurationProvider.java:89)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
        at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:73)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:63)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at org.kframework.utils.inject.SimpleScope$2.get(SimpleScope.java:99)
        - locked Monitor@5a3a1dd0 at org.kframework.utils.inject.SimpleScope$2.get(SimpleScope.java:95) 
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.ExposedKeyFactory.get(ExposedKeyFactory.java:54)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:94)
        at com.google.inject.throwingproviders.ThrowingProviderBinder$SecondaryBinder$3.get(ThrowingProviderBinder.java:292)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:94)
        at com.google.inject.throwingproviders.ThrowingProviderBinder$SecondaryBinder$2$1.invoke(ThrowingProviderBinder.java:275)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:129)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
    T49 is created by T13
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}
```
