### ISSUE TITLE
using non-thread-safe implementation of com.google.common.collect.Multiset without synchronization

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1602]
Two reports on this:

```
Data race on field com.google.common.collect.AbstractMultimap.values: {{{
    Concurrent read in thread T49 (locks held: {})
 ---->  at com.google.common.collect.AbstractMultimap.values(AbstractMultimap.java:173)
        at org.kframework.backend.java.symbolic.BasicVisitor.visit(BasicVisitor.java:116)
        at org.kframework.backend.java.symbolic.BasicVisitor.visitNode(BasicVisitor.java:25)
        at org.kframework.backend.java.kil.IsGroundFieldInitializer.visitNode(IsGroundFieldInitializer.java:21)
        at org.kframework.backend.java.kil.JavaSymbolicObject.isGround(JavaSymbolicObject.java:133)
        at org.kframework.backend.java.kil.JavaSymbolicObject.canSubstituteAndEvaluate(JavaSymbolicObject.java:93)
        at org.kframework.backend.java.kil.Term.substituteAndEvaluate(Term.java:132)
        at org.kframework.backend.java.symbolic.ConjunctiveFormula.simplify(ConjunctiveFormula.java:357)
        at org.kframework.backend.java.symbolic.ConjunctiveFormula.simplify(ConjunctiveFormula.java:325)
        at org.kframework.backend.java.symbolic.PatternMatcher.unify(PatternMatcher.java:558)
        at org.kframework.backend.java.symbolic.AbstractUnifier.unify(AbstractUnifier.java:172)
        at org.kframework.backend.java.symbolic.PatternMatcher.patternMatch(PatternMatcher.java:144)
        at org.kframework.backend.java.symbolic.PatternMatcher.patternMatch(PatternMatcher.java:135)
        at org.kframework.backend.java.symbolic.PatternMatcher.match(PatternMatcher.java:117)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.getMatchingResults(PatternMatchRewriter.java:146)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.computeRewriteStep(PatternMatchRewriter.java:256)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.rewrite(PatternMatchRewriter.java:93)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.patternMatcherRewriteRun(JavaSymbolicExecutor.java:107)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:134)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:131)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
    T49 is created by T13
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)

    Concurrent write in thread T54 (locks held: {})
 ---->  at com.google.common.collect.AbstractMultimap.values(AbstractMultimap.java:174)
        at org.kframework.backend.java.symbolic.BasicVisitor.visit(BasicVisitor.java:116)
        at org.kframework.backend.java.symbolic.BasicVisitor.visitNode(BasicVisitor.java:25)
        at org.kframework.backend.java.kil.IsGroundFieldInitializer.visitNode(IsGroundFieldInitializer.java:21)
        at org.kframework.backend.java.kil.JavaSymbolicObject.isGround(JavaSymbolicObject.java:133)
        at org.kframework.backend.java.kil.JavaSymbolicObject.canSubstituteAndEvaluate(JavaSymbolicObject.java:93)
        at org.kframework.backend.java.kil.Term.substituteAndEvaluate(Term.java:132)
        at org.kframework.backend.java.symbolic.ConjunctiveFormula.simplify(ConjunctiveFormula.java:357)
        at org.kframework.backend.java.symbolic.ConjunctiveFormula.simplify(ConjunctiveFormula.java:325)
        at org.kframework.backend.java.symbolic.PatternMatcher.unify(PatternMatcher.java:558)
        at org.kframework.backend.java.symbolic.AbstractUnifier.unify(AbstractUnifier.java:172)
        at org.kframework.backend.java.symbolic.PatternMatcher.patternMatch(PatternMatcher.java:144)
        at org.kframework.backend.java.symbolic.PatternMatcher.patternMatch(PatternMatcher.java:135)
        at org.kframework.backend.java.symbolic.PatternMatcher.match(PatternMatcher.java:117)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.getMatchingResults(PatternMatchRewriter.java:146)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.computeRewriteStep(PatternMatchRewriter.java:256)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.rewrite(PatternMatchRewriter.java:93)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.patternMatcherRewriteRun(JavaSymbolicExecutor.java:107)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:134)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:131)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
    T54 is created by T13
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}

Data race on field com.google.common.collect.AbstractMultimap.values: {{{
    Concurrent write in thread T49 (locks held: {})
 ---->  at com.google.common.collect.AbstractMultimap.values(AbstractMultimap.java:174)
        at org.kframework.backend.java.symbolic.BasicVisitor.visit(BasicVisitor.java:116)
        at org.kframework.backend.java.symbolic.BasicVisitor.visitNode(BasicVisitor.java:25)
        at org.kframework.backend.java.kil.IsGroundFieldInitializer.visitNode(IsGroundFieldInitializer.java:21)
        at org.kframework.backend.java.kil.JavaSymbolicObject.isGround(JavaSymbolicObject.java:133)
        at org.kframework.backend.java.kil.JavaSymbolicObject.canSubstituteAndEvaluate(JavaSymbolicObject.java:93)
        at org.kframework.backend.java.kil.Term.substituteAndEvaluate(Term.java:132)
        at org.kframework.backend.java.symbolic.ConjunctiveFormula.simplify(ConjunctiveFormula.java:357)
        at org.kframework.backend.java.symbolic.ConjunctiveFormula.simplify(ConjunctiveFormula.java:325)
        at org.kframework.backend.java.symbolic.PatternMatcher.unify(PatternMatcher.java:558)
        at org.kframework.backend.java.symbolic.AbstractUnifier.unify(AbstractUnifier.java:172)
        at org.kframework.backend.java.symbolic.PatternMatcher.patternMatch(PatternMatcher.java:144)
        at org.kframework.backend.java.symbolic.PatternMatcher.patternMatch(PatternMatcher.java:135)
        at org.kframework.backend.java.symbolic.PatternMatcher.match(PatternMatcher.java:117)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.getMatchingResults(PatternMatchRewriter.java:146)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.computeRewriteStep(PatternMatchRewriter.java:256)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.rewrite(PatternMatchRewriter.java:93)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.patternMatcherRewriteRun(JavaSymbolicExecutor.java:107)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:134)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:131)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
    T49 is created by T13
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)

    Concurrent write in thread T54 (locks held: {})
 ---->  at com.google.common.collect.AbstractMultimap.values(AbstractMultimap.java:174)
        at org.kframework.backend.java.symbolic.BasicVisitor.visit(BasicVisitor.java:116)
        at org.kframework.backend.java.symbolic.BasicVisitor.visitNode(BasicVisitor.java:25)
        at org.kframework.backend.java.kil.IsGroundFieldInitializer.visitNode(IsGroundFieldInitializer.java:21)
        at org.kframework.backend.java.kil.JavaSymbolicObject.isGround(JavaSymbolicObject.java:133)
        at org.kframework.backend.java.kil.JavaSymbolicObject.canSubstituteAndEvaluate(JavaSymbolicObject.java:93)
        at org.kframework.backend.java.kil.Term.substituteAndEvaluate(Term.java:132)
        at org.kframework.backend.java.symbolic.ConjunctiveFormula.simplify(ConjunctiveFormula.java:357)
        at org.kframework.backend.java.symbolic.ConjunctiveFormula.simplify(ConjunctiveFormula.java:325)
        at org.kframework.backend.java.symbolic.PatternMatcher.unify(PatternMatcher.java:558)
        at org.kframework.backend.java.symbolic.AbstractUnifier.unify(AbstractUnifier.java:172)
        at org.kframework.backend.java.symbolic.PatternMatcher.patternMatch(PatternMatcher.java:144)
        at org.kframework.backend.java.symbolic.PatternMatcher.patternMatch(PatternMatcher.java:135)
        at org.kframework.backend.java.symbolic.PatternMatcher.match(PatternMatcher.java:117)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.getMatchingResults(PatternMatchRewriter.java:146)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.computeRewriteStep(PatternMatchRewriter.java:256)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.rewrite(PatternMatchRewriter.java:93)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.patternMatcherRewriteRun(JavaSymbolicExecutor.java:107)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:134)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:131)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
    T54 is created by T13
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}
```

@dwightguth please confirm

**Comment by dwightguth** [comment]
I am looking at this method and it looks like a benign race to me:

```
@Override
  public Collection<V> values() {
    Collection<V> result = values;
    return (result == null) ? values = createValues() : result;
  }
```

**Comment by yilongli** [comment]
Good catch. I didn't look into the implementation, but the `HashMultiset` is non-thread-safe in general. So I believe if I run it enough times, this issue will pop up on other fields inside `AbstractMultimap`. BTW, Guava also provides [`ConcurrentHashMultimap`](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/ConcurrentHashMultiset.html) and `Multimaps.synchronizedMultimap`.

**Comment by yilongli** [comment]
I think `CellCollection` should be confined to one thread or one rewriter. It doesn't make sense to share mutable terms between threads.

**Comment by yilongli** [comment]
@dwightguth I think you are right. This is a benign race. On the higher level, `AbstractMultimap.values()` can be seen as a read on the content of the multimap.

**Comment by grosu** [comment]
@yilongli , please make sure you explain somewhere how people can easily tell RV-Predict to not report such benign races over and over again, once they find out that a race is benign.  I think, ideally, they would like to have some config file for RV-Predict in which they write the options once and for all, without having to repeat them over and over again.  Maybe you already have that, I haven't played with RV-Predict lately (but I will, soon).

**Comment by yilongli** [comment]
Yes, there is an option called `--suppress` where you can supply regular expression patterns to suppress benign races. It's in the help menu and the documentation.

**Comment by yilongli** [comment]
And yes, we will have a config file for that.
