### ISSUE TITLE
data race on field org.kframework.backend.java.kil.CellCollection$Cell.content

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1606]
I got this race report when testing kool-typed-static. At first I thought it would be an easy fix, but then I realized that it shows that we are sharing mutable terms (i.e., `CellCollection` & `CellCollection$Cell`) between several kruns. Isn't problematic? How does it happen? @andreistefanescu @dwightguth What do you think?

```
Data race on field org.kframework.backend.java.kil.CellCollection$Cell.content: {{{
    Concurrent read in thread T300 (locks held: {})
 ---->  at org.kframework.backend.java.kil.CellCollection$Cell.content(CellCollection.java:45)
        at org.kframework.backend.java.symbolic.SymbolicUnifier.unify(SymbolicUnifier.java:512)
        at org.kframework.backend.java.symbolic.AbstractUnifier.unify(AbstractUnifier.java:172)
        at org.kframework.backend.java.symbolic.SymbolicUnifier.unify(SymbolicUnifier.java:608)
        at org.kframework.backend.java.symbolic.AbstractUnifier.unify(AbstractUnifier.java:172)
        at org.kframework.backend.java.symbolic.SymbolicUnifier.symbolicUnify(SymbolicUnifier.java:70)
        at org.kframework.backend.java.symbolic.SymbolicUnifier.symbolicUnify(SymbolicUnifier.java:61)
        at org.kframework.backend.java.kil.ConstrainedTerm.unify(ConstrainedTerm.java:190)
        at org.kframework.backend.java.symbolic.SymbolicRewriter.computeRewriteStepByRule(SymbolicRewriter.java:206)
        at org.kframework.backend.java.symbolic.SymbolicRewriter.lambda$computeRewriteStep$68(SymbolicRewriter.java:154)
        at org.kframework.backend.java.symbolic.SymbolicRewriter$$Lambda$198.apply(Unknown:n/a)
        at org.kframework.backend.java.symbolic.SymbolicRewriter.computeRewriteStep(SymbolicRewriter.java:163)
        at org.kframework.backend.java.symbolic.SymbolicRewriter.rewrite(SymbolicRewriter.java:80)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.conventionalRewriteRun(JavaSymbolicExecutor.java:114)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:137)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:131)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
    T300 is created by T13
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)

    Concurrent write in thread T289 (locks held: {})
 ---->  at org.kframework.backend.java.kil.CellCollection$Cell.setContent(CellCollection.java:49)
        at org.kframework.backend.java.rewritemachine.KAbstractRewriteMachine.rewrite(KAbstractRewriteMachine.java:98)
        at org.kframework.backend.java.rewritemachine.KAbstractRewriteMachine.rewrite(KAbstractRewriteMachine.java:64)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.computeRewriteStep(PatternMatchRewriter.java:232)
        at org.kframework.backend.java.symbolic.PatternMatchRewriter.rewrite(PatternMatchRewriter.java:93)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.patternMatcherRewriteRun(JavaSymbolicExecutor.java:107)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:134)
        at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
        at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
        at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
        at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
        at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:131)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
    T289 is created by T13
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}
```

**Comment by yilongli** [comment]
Related to #1602.

**Comment by dwightguth** [comment]
So the only terms that should be shared between krun invocations are terms that are part of the Definition object. If they are being written to then something funny is going on.

**Comment by yilongli** [comment]
Yes, that is the problem, though I am not sure how this happens. Can you please work on this problem? It's responsible for a whole bunch of races on java kil classes. It would be just hiding the problem if I patch those classes directly to avoid data races.
