### ISSUE TITLE
Uncaught NullPointerException when running a file compiled with kcc

### ISSUE THREAD

**Issue by edgar-pek** [kframework/k-legacy#1626]
Reproducing the error:
kcc -s https://github.com/edgar-pek/OpenPilot4K/blob/master/imu_airspeed-inlined_calls.c
DEBUG=1 TRACE=1 ./a.out
Output:
rule <generatedTop><global>_22254:Bag</global><T><exec><threads><thread><k>'loadObj((# <global>_22252:Bag</global>)(.KList)) ~> _22253:K</k>_22258:Bag</thread>_22257:Bag</threads>_22256:Bag</exec>_22255:Bag</T></generatedTop> => <generatedTop><global>_22252:Bag</global><T><exec><threads><thread><k>_22253:K</k>_22258:Bag</thread>_22257:Bag</threads>_22256:Bag</exec>_22255:Bag</T></generatedTop> requires ['_=/=Bag_((# _22252:Bag)(.KList),, (# .Bag)(.KList))] ensures [] [Location: Location(169,6,172,22), Source(./language/common/dynamic.k)]
java.lang.NullPointerException
    at org.kframework.backend.java.symbolic.Equality.toK(Equality.java:140)
    at org.kframework.backend.java.symbolic.ConjunctiveFormula.lambda$getKComponents$36(ConjunctiveFormula.java:727)
    at org.kframework.backend.java.symbolic.ConjunctiveFormula$$Lambda$62/1739628084.apply(Unknown Source)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
    at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
    at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at org.kframework.backend.java.symbolic.ConjunctiveFormula.getKComponents(ConjunctiveFormula.java:729)
    at org.kframework.backend.java.kil.CollectionInternalRepresentation.toKore(CollectionInternalRepresentation.java:14)
    at org.kframework.backend.java.symbolic.ConjunctiveFormula.toKore(ConjunctiveFormula.java:719)
    at org.kframework.backend.java.symbolic.ConjunctiveFormula.toString(ConjunctiveFormula.java:769)
    at java.lang.String.valueOf(String.java:2982)
    at java.lang.StringBuilder.append(StringBuilder.java:131)
    at org.kframework.backend.java.kil.Rule.toString(Rule.java:614)
    at java.lang.String.valueOf(String.java:2982)
    at java.io.PrintStream.println(PrintStream.java:821)
    at org.kframework.backend.java.symbolic.PatternMatchRewriter.computeRewriteStep(PatternMatchRewriter.java:239)
    at org.kframework.backend.java.symbolic.PatternMatchRewriter.rewrite(PatternMatchRewriter.java:93)
    at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.patternMatcherRewriteRun(JavaSymbolicExecutor.java:107)
    at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:134)
    at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
    at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
    at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
    at org.kframework.krun.tools.Executor$Tool.run(Executor.java:89)
    at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
    at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:118)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
    at org.kframework.main.Main.runApplication(Main.java:109)
    at org.kframework.main.Main.runApplication(Main.java:99)
    at org.kframework.main.Main.main(Main.java:51)
java.lang.NullPointerException
    at org.kframework.backend.java.symbolic.Equality.toK(Equality.java:140)
    at org.kframework.backend.java.symbolic.ConjunctiveFormula.lambda$getKComponents$36(ConjunctiveFormula.java:727)
    at org.kframework.backend.java.symbolic.ConjunctiveFormula$$Lambda$62/1739628084.apply(Unknown Source)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
    at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
    at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at org.kframework.backend.java.symbolic.ConjunctiveFormula.getKComponents(ConjunctiveFormula.java:729)
    at org.kframework.backend.java.kil.CollectionInternalRepresentation.toKore(CollectionInternalRepresentation.java:14)
    at org.kframework.backend.java.symbolic.ConjunctiveFormula.toKore(ConjunctiveFormula.java:719)
    at org.kframework.backend.java.symbolic.ConjunctiveFormula.toString(ConjunctiveFormula.java:769)
    at java.lang.String.valueOf(String.java:2982)
    at java.lang.StringBuilder.append(StringBuilder.java:131)
    at org.kframework.backend.java.kil.Rule.toString(Rule.java:614)
    at java.lang.String.valueOf(String.java:2982)
    at java.io.PrintStream.println(PrintStream.java:821)
    at org.kframework.backend.java.symbolic.PatternMatchRewriter.computeRewriteStep(PatternMatchRewriter.java:239)
    at org.kframework.backend.java.symbolic.PatternMatchRewriter.rewrite(PatternMatchRewriter.java:93)
    at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.patternMatcherRewriteRun(JavaSymbolicExecutor.java:107)
    at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.javaRewriteEngineRun(JavaSymbolicExecutor.java:134)
    at org.kframework.backend.java.symbolic.JavaSymbolicExecutor.run(JavaSymbolicExecutor.java:73)
    at org.kframework.krun.tools.Executor$Tool.execute(Executor.java:169)
    at org.kframework.krun.tools.Executor$Tool.run(Executor.java:125)
    at org.kframework.krun.tools.Executor$Tool.run(Executor.java:89)
    at org.kframework.transformation.TransformationCompositionProvider$2.run(TransformationCompositionProvider.java:120)
    at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:118)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
    at org.kframework.main.Main.runApplication(Main.java:109)
    at org.kframework.main.Main.runApplication(Main.java:99)
    at org.kframework.main.Main.main(Main.java:51)
[Error] Internal: Uncaught exception thrown of type NullPointerException.

**Comment by andreistefanescu** [comment]
This is a known (to me) bug in the implementation of `toString` for collections. I plan to fix it as part of the transition to kore. For now, I suggest to bypass it (for example, print only the location instead of the entire rule, or wrap the line throwing the exception in a try-catch block).
