### ISSUE TITLE
Is z3 a requirement for K?

### ISSUE THREAD

**Issue by cos** [kframework/k-legacy#1676]
`mvn package` throws this:

```
Running org.kframework.backend.java.symbolic.UseSMTTest
/Users/cos/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.053 sec <<< FAILURE! - in org.kframework.backend.java.symbolic.UseSMTTest
testGetModel(org.kframework.backend.java.symbolic.UseSMTTest)  Time elapsed: 0.039 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: no z3java in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1119)
    at com.microsoft.z3.Native.<clinit>(Native.java:10)
    at com.microsoft.z3.Context.<init>(Context.java:24)
    at org.kframework.backend.java.symbolic.UseSMT.checkSat(UseSMT.java:44)
    at org.kframework.backend.java.symbolic.UseSMTTest.testGetModel(UseSMTTest.java:52)
```

**Comment by cos** [comment]
@dwightguth, @andreistefanescu ?

**Comment by andreistefanescu** [comment]
The `--prove` relies in it. I'm not sure if it should be a dependence.

**Comment by dwightguth** [comment]
Can you reproduce this on a clean checkout of master? the maven surefire
plugin should be automatically configured to run this unit test with the
correct java.library.path option.
