### ISSUE TITLE
NoSuchMethodException on minimal input file

### ISSUE THREAD

**Issue by bmmoore** [kframework/k-legacy#1689]
Trying to kompile as kore a minimal file

```
module TEST-SYNTAX
endmodule
module TEST
endmodule
```

produces a `NoSuchMethodError`. It looks like it's trying to add items to an immutable set.

```
brandon@brandon:~/test/k/minimal-file$ kompile --debug --kore test.k
java.lang.NoSuchMethodError: scala.collection.immutable.Set.$plus(Ljava/lang/Object;)Lscala/collection/SetLike;
        at org.kframework.kompile.Kompile.lambda$parseDefinition$76(Kompile.java:224)
        at org.kframework.kompile.Kompile$$Lambda$36/1722570594.apply(Unknown Source)
        at org.kframework.definition.DefinitionTransformer$$anonfun$from$2.apply(transformers.scala:55)
        at org.kframework.definition.DefinitionTransformer$$anonfun$from$2.apply(transformers.scala:55)
        at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:47)
        at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:42)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:901)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:42)
        at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:63)
        at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:227)
        at org.kframework.kompile.Kompile.run(Kompile.java:126)
        at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:89)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.main.Main.runApplication(Main.java:99)
        at org.kframework.main.Main.main(Main.java:51)
java.lang.NoSuchMethodError: scala.collection.immutable.Set.$plus(Ljava/lang/Object;)Lscala/collection/SetLike;
        at org.kframework.kompile.Kompile.lambda$parseDefinition$76(Kompile.java:224)
        at org.kframework.kompile.Kompile$$Lambda$36/1722570594.apply(Unknown Source)
        at org.kframework.definition.DefinitionTransformer$$anonfun$from$2.apply(transformers.scala:55)
        at org.kframework.definition.DefinitionTransformer$$anonfun$from$2.apply(transformers.scala:55)
        at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:47)
        at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:42)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:901)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:42)
        at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:63)
        at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:227)
        at org.kframework.kompile.Kompile.run(Kompile.java:126)
        at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:89)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.main.Main.runApplication(Main.java:99)
        at org.kframework.main.Main.main(Main.java:51)
[Error] Internal: Uncaught exception thrown of type NoSuchMethodError.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
```

**Comment by bmmoore** [comment]
Looks like it happens if you have no configuration
