### ISSUE TITLE
two potential data races inside dk.brics.automaton.Automaton

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1795]
Reported by RV-Predict:

```
Data race on field dk.brics.automaton.Automaton.minimization: {{{
    Concurrent write in thread T34 (locks held: {})
 ---->  at dk.brics.automaton.Automaton.setMinimization(Unknown:n/a)
        at org.kframework.parser.concrete2kore.kernel.KSyntax2GrammarStatesFilter.getGrammar(KSyntax2GrammarStatesFilter.java:39)
        at org.kframework.parser.concrete2kore.ParseInModule.getGrammar(ParseInModule.java:93)
        at org.kframework.parser.concrete2kore.ParseInModule.parseStringTerm(ParseInModule.java:127)
        at org.kframework.parser.concrete2kore.ParseInModule.parseString(ParseInModule.java:101)
        at org.kframework.kompile.Kompile.performParse(Kompile.java:496)
        at org.kframework.kompile.Kompile.lambda$resolveConfig$69(Kompile.java:355)
        at org.kframework.kompile.Kompile$$Lambda$186.apply(Unknown:n/a)
        at org.kframework.kompile.Kompile.resolveConfig(Kompile.java:370)
        at org.kframework.kompile.Kompile.lambda$parseDefinition$61(Kompile.java:320)
        at org.kframework.kompile.Kompile$$Lambda$158.apply(Unknown:n/a)
        at org.kframework.definition.DefinitionTransformer$$anonfun$from$2.apply(transformers.scala:67)
        at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:55)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:901)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:50)
        at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:77)
        at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:320)
        at org.kframework.kompile.Kompile.run(Kompile.java:138)
        at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:88)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T34 is created by T13
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)

    Concurrent write in thread T42 (locks held: {})
 ---->  at dk.brics.automaton.Automaton.setMinimization(Unknown:n/a)
        at org.kframework.parser.concrete2kore.kernel.KSyntax2GrammarStatesFilter.getGrammar(KSyntax2GrammarStatesFilter.java:39)
        at org.kframework.parser.concrete2kore.ParseInModule.getGrammar(ParseInModule.java:93)
        at org.kframework.parser.concrete2kore.ParseInModule.parseStringTerm(ParseInModule.java:127)
        at org.kframework.parser.concrete2kore.ParseInModule.parseString(ParseInModule.java:101)
        at org.kframework.kompile.Kompile.performParse(Kompile.java:496)
        at org.kframework.kompile.Kompile.lambda$resolveConfig$69(Kompile.java:355)
        at org.kframework.kompile.Kompile$$Lambda$186.apply(Unknown:n/a)
    T42 is created by T30
        at java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1488)
}}}

Data race on field dk.brics.automaton.State.next_id: {{{
    Concurrent write in thread T42 (locks held: {Monitor@85ed10b})
 ---->  at dk.brics.automaton.State.<init>(Unknown:n/a)
        at dk.brics.automaton.Automaton.<init>(Unknown:n/a)
        at dk.brics.automaton.BasicAutomata.makeEmpty(Unknown:n/a)
        at dk.brics.automaton.BasicAutomata.makeStringUnion(Unknown:n/a)
        at org.kframework.definition.Terminal.followPattern$lzycompute(outer.scala:315)
        - locked Monitor@85ed10b at org.kframework.definition.Terminal.followPattern$lzycompute(outer.scala:314) 
        at org.kframework.definition.Terminal.followPattern(outer.scala:314)
        at org.kframework.parser.concrete2kore.kernel.KSyntax2GrammarStatesFilter.processProductions(KSyntax2GrammarStatesFilter.java:115)
        at org.kframework.parser.concrete2kore.kernel.KSyntax2GrammarStatesFilter.lambda$getGrammar$105(KSyntax2GrammarStatesFilter.java:51)
        at org.kframework.parser.concrete2kore.kernel.KSyntax2GrammarStatesFilter$$Lambda$194.accept(Unknown:n/a)
        at org.kframework.parser.concrete2kore.ParseInModule.getGrammar(ParseInModule.java:93)
        at org.kframework.parser.concrete2kore.ParseInModule.parseStringTerm(ParseInModule.java:127)
        at org.kframework.parser.concrete2kore.ParseInModule.parseString(ParseInModule.java:101)
        at org.kframework.kompile.Kompile.performParse(Kompile.java:496)
        at org.kframework.kompile.Kompile.lambda$resolveConfig$69(Kompile.java:355)
        at org.kframework.kompile.Kompile$$Lambda$186.apply(Unknown:n/a)
    T42 is created by T30
        at java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1488)

    Concurrent read in thread T34 (locks held: {Monitor@85ed850})
 ---->  at dk.brics.automaton.State.<init>(Unknown:n/a)
        at dk.brics.automaton.Automaton.<init>(Unknown:n/a)
        at dk.brics.automaton.BasicAutomata.makeString(Unknown:n/a)
        at org.kframework.definition.Terminal.pattern$lzycompute(outer.scala:313)
        - locked Monitor@85ed850 at org.kframework.definition.Terminal.pattern$lzycompute(outer.scala:313) 
        at org.kframework.definition.Terminal.pattern(outer.scala:313)
        at org.kframework.parser.concrete2kore.kernel.KSyntax2GrammarStatesFilter.processProductions(KSyntax2GrammarStatesFilter.java:114)
        at org.kframework.parser.concrete2kore.kernel.KSyntax2GrammarStatesFilter.lambda$getGrammar$105(KSyntax2GrammarStatesFilter.java:51)
        at org.kframework.parser.concrete2kore.kernel.KSyntax2GrammarStatesFilter$$Lambda$194.accept(Unknown:n/a)
        at org.kframework.parser.concrete2kore.ParseInModule.getGrammar(ParseInModule.java:93)
        at org.kframework.parser.concrete2kore.ParseInModule.parseStringTerm(ParseInModule.java:127)
        at org.kframework.parser.concrete2kore.ParseInModule.parseString(ParseInModule.java:101)
        at org.kframework.kompile.Kompile.performParse(Kompile.java:496)
        at org.kframework.kompile.Kompile.lambda$resolveConfig$69(Kompile.java:355)
        at org.kframework.kompile.Kompile$$Lambda$186.apply(Unknown:n/a)
        at org.kframework.kompile.Kompile.resolveConfig(Kompile.java:370)
        at org.kframework.kompile.Kompile.lambda$parseDefinition$61(Kompile.java:320)
        at org.kframework.kompile.Kompile$$Lambda$158.apply(Unknown:n/a)
        at org.kframework.definition.DefinitionTransformer$$anonfun$from$2.apply(transformers.scala:67)
        at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:55)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:901)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:50)
        at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:77)
        at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:320)
        at org.kframework.kompile.Kompile.run(Kompile.java:138)
        at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:88)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:109)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:119)
        at org.kframework.main.Main.nailMain(Main.java:70)
    T34 is created by T13
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}
```

Looks like `dk.brics.automaton.Automaton` is non-thread-safe and should be protected by a lock. Please confirm.

**Comment by bmmoore** [comment]
Those are both static fields. If there are not any other races we probably already protect the instances well enough, so this looks a bit hard to fix.

RV-Predict should be changed to say "race on static field".

**Comment by yilongli** [comment]
But it must be fixed, right?

**Comment by bmmoore** [comment]
The counter definintely needs to be fixed. I'm not sure about the minimization setting - it looks like all writes are writing the same constant, trying to override the default setting - assuming such a write happens before every use of minimization, do you if Java guarantees good behaivor in that case?

**Comment by yilongli** [comment]
yes, it's ok to write the same constant concurrently

**Comment by bmmoore** [comment]
Ok. I'm not sure if every path that might minimize is guarded by such a write - maybe we should hoist it all the way to some super-early code. The constant we are writing is different from the initial value of the field. If writing the same constant is safe has long as every read happens-after a write of the constant, is this then a false positive in RV-Predict?

That `next_id`field looks like it might require forking the package - here's the relevant code, and that's the only constructor of State. Do you see any was to fix this without changing the package?

```
int id;
static int next_id;

public State() {
    this.resetTransitions();
    this.id = next_id++;
}
```

**Comment by yilongli** [comment]
Yes, it's better to hoist the code that calls `setMinimization`. It's not a false positive in RV-Predict. It's a data race, but a benign one w.r.t the JMM.

Maybe this package is just not designed to be thread-safe. Could you just synchronize from our side?

**Comment by bmmoore** [comment]
I worry because I think most of the parallelism in kompile is parsing rule bodies in multiple threads, and parsing definitely at least runs automata.

Hopefully only regex construction would need to be synchronized on `State.class` to fix the `next_id` race, but I don't have time to look into the code closely enough to see whether that's actually true.

**Comment by dwightguth** [comment]
I think it's better to try to fix the package than to try to synchronize. I mean, we can try that, but I suspect we will see serious performance losses from lock contention.

Probably use an AtomicInt for next_id and hoist setMinimization before the thread creation (static initializer maybe?)

**Comment by bmmoore** [comment]
Fixing the package is a cleaner solution, but _if_ it's safe to put a global lock only around parser generation and not around actually parsing input, then I think it wouldn't hurt performance too badly.

**Comment by dwightguth** [comment]
Alright. Well, time it and see. Test with the C semantics before and after
the change.
