### ISSUE TITLE
krun throws an exception when unrecognized option

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#18]
fslwork$ krun -abc
Error while parsing commandline:Unrecognized option: -abc
Exception in thread "main" java.lang.NullPointerException
    at org.kframework.krun.Main.execute_Krun(Main.java:802)
    at org.kframework.main.Main.main(Main.java:78)
fslwork$ 

For uniformity with other errors, I think it should only say:

fslwork$ krun -abc
[Error] Unrecognized option: -abc
fslwork$

**Comment by daejunpark** [comment]
This problem was fixed together with cleaning options.
