### ISSUE TITLE
Building K fails on OS X El Capitan

### ISSUE THREAD

**Issue by msaxena2** [kframework/k-legacy#1813]
calling mvn package on OS X El Capitan fails with the following error message:

```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, <<< FAILURE! - in org.kframework.backend.java.symbolic.UseSMTTest
testGetModel(org.kframework.backend.java.symbolic.UseSMTTest)    <<< ERROR!
java.lang.UnsatisfiedLinkError: no z3java in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at com.microsoft.z3.Native.<clinit>(Native.java:10)
    at com.microsoft.z3.Context.<init>(Context.java:24)
    at org.kframework.backend.java.symbolic.UseSMT.checkSat(UseSMT.java:44)
    at org.kframework.backend.java.symbolic.UseSMTTest.testGetModel(UseSMTTest.java:52)
```

**Comment by dlucanu** [comment]
I had a similar experience:

```
...
Running org.kframework.backend.java.symbolic.UseSMTTest
/Users/dlucanu/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.143 sec <<< FAILURE! - in org.kframework.backend.java.symbolic.UseSMTTest
testGetModel(org.kframework.backend.java.symbolic.UseSMTTest)  Time elapsed: 0.118 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: no z3java in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at com.microsoft.z3.Native.<clinit>(Native.java:10)
    at com.microsoft.z3.Context.<init>(Context.java:24)
    at org.kframework.backend.java.symbolic.UseSMT.checkSat(UseSMT.java:44)
    at org.kframework.backend.java.symbolic.UseSMTTest.testGetModel(UseSMTTest.java:52)
```

**Comment by kheradmand** [comment]
@msaxena2  I have similar experience. Any progress on that? Any idea what to do meanwhile ?

**Comment by msaxena2** [comment]
@kheradmand Turn off system Integrity Protection on OS X. That solves the
issue.
