### ISSUE TITLE
Uncaught NPE in Java Backend's SymbolicRewriter 

### ISSUE THREAD

**Issue by msaxena2** [kframework/k-legacy#1820]
This issue deals with changes intended to be introduced by PR #1786 . The NPE occurs when the Symbolic Rewriter tries to perform a match (using call to the FastRuleMatcher's mainMatch() method). The NPE occurs as the Automaton rule object in the Definition is null. 
The stack Trace:

```
java.lang.NullPointerException
    at org.kframework.backend.java.symbolic.SymbolicRewriter.fastComputeRewriteStep(SymbolicRewriter.java:177)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.rewrite(SymbolicRewriter.java:84)
    at org.kframework.backend.java.symbolic.InitializeRewriter$SymbolicRewriterGlue.execute(InitializeRewriter.java:126)
    at org.kframework.backend.java.symbolic.InitializeRewriter$SymbolicRewriterGlue.executeAndMatch(InitializeRewriter.java:149)
    at org.kframework.krun.modes.KRunExecutionMode.execute(KRunExecutionMode.java:63)
    at org.kframework.krun.KRun.run(KRun.java:73)
    at org.kframework.krun.KRunFrontEnd$NewKRunFrontEnd.run(KRunFrontEnd.java:112)
    at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:128)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
    at org.kframework.main.Main.runApplication(Main.java:109)
    at org.kframework.main.Main.runApplication(Main.java:99)
    at org.kframework.main.Main.main(Main.java:51)
java.lang.NullPointerException
    at org.kframework.backend.java.symbolic.SymbolicRewriter.fastComputeRewriteStep(SymbolicRewriter.java:177)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.rewrite(SymbolicRewriter.java:84)
    at org.kframework.backend.java.symbolic.InitializeRewriter$SymbolicRewriterGlue.execute(InitializeRewriter.java:126)
    at org.kframework.backend.java.symbolic.InitializeRewriter$SymbolicRewriterGlue.executeAndMatch(InitializeRewriter.java:149)
    at org.kframework.krun.modes.KRunExecutionMode.execute(KRunExecutionMode.java:63)
    at org.kframework.krun.KRun.run(KRun.java:73)
    at org.kframework.krun.KRunFrontEnd$NewKRunFrontEnd.run(KRunFrontEnd.java:112)
    at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:128)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
    at org.kframework.main.Main.runApplication(Main.java:109)
    at org.kframework.main.Main.runApplication(Main.java:99)
    at org.kframework.main.Main.main(Main.java:51)
[Error] Internal: Uncaught exception thrown of type NullPointerException.
```

**Comment by cos** [comment]
should be fixed by https://github.com/kframework/k/commit/e013265ce251064b3a15a3e3267ff3ccfd19e5b1

@msaxena2, please reopen if it still doesn't work.
