### ISSUE TITLE
doing krun without specifying a program results in an AssertionError

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1834]
```
$ krun --debug
java.lang.AssertionError: unexpected concatenated termorg.kframework.backend.java.kil.Bottom@37ed010a
    at org.kframework.backend.java.kil.KList$Builder.concatenate(KList.java:192)
    at org.kframework.backend.java.rewritemachine.KAbstractRewriteMachine.construct(KAbstractRewriteMachine.java:196)
    at org.kframework.backend.java.util.RewriteEngineUtils.evaluateConditions(RewriteEngineUtils.java:129)
    at org.kframework.backend.java.util.RewriteEngineUtils.lambda$evaluateConditions$93(RewriteEngineUtils.java:165)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at org.kframework.backend.java.util.RewriteEngineUtils.evaluateConditions(RewriteEngineUtils.java:167)
    at org.kframework.backend.java.symbolic.PatternMatcher.match(PatternMatcher.java:121)
    at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:437)
    at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:302)
    at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:254)
    at org.kframework.backend.java.rewritemachine.KAbstractRewriteMachine.construct(KAbstractRewriteMachine.java:237)
    at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:458)
    at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:302)
    at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:254)
    at org.kframework.backend.java.symbolic.Evaluator.transform(Evaluator.java:27)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:698)
    at org.kframework.backend.java.symbolic.Evaluator.evaluate(Evaluator.java:22)
    at org.kframework.backend.java.kil.Term.evaluate(Term.java:103)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.expandAndEvaluate(KILtoBackendJavaKILTransformer.java:139)
    at org.kframework.backend.java.symbolic.InitializeRewriter$SymbolicRewriterGlue.execute(InitializeRewriter.java:125)
    at org.kframework.krun.modes.KRunExecutionMode.execute(KRunExecutionMode.java:70)
    at org.kframework.krun.KRun.run(KRun.java:75)
    at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:91)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
    at org.kframework.main.Main.runApplication(Main.java:109)
    at org.kframework.main.Main.runApplication(Main.java:99)
    at org.kframework.main.Main.main(Main.java:51)
java.lang.AssertionError: unexpected concatenated termorg.kframework.backend.java.kil.Bottom@37ed010a
    at org.kframework.backend.java.kil.KList$Builder.concatenate(KList.java:192)
    at org.kframework.backend.java.rewritemachine.KAbstractRewriteMachine.construct(KAbstractRewriteMachine.java:196)
    at org.kframework.backend.java.util.RewriteEngineUtils.evaluateConditions(RewriteEngineUtils.java:129)
    at org.kframework.backend.java.util.RewriteEngineUtils.lambda$evaluateConditions$93(RewriteEngineUtils.java:165)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at org.kframework.backend.java.util.RewriteEngineUtils.evaluateConditions(RewriteEngineUtils.java:167)
    at org.kframework.backend.java.symbolic.PatternMatcher.match(PatternMatcher.java:121)
    at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:437)
    at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:302)
    at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:254)
    at org.kframework.backend.java.rewritemachine.KAbstractRewriteMachine.construct(KAbstractRewriteMachine.java:237)
    at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:458)
    at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:302)
    at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:254)
    at org.kframework.backend.java.symbolic.Evaluator.transform(Evaluator.java:27)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:698)
    at org.kframework.backend.java.symbolic.Evaluator.evaluate(Evaluator.java:22)
    at org.kframework.backend.java.kil.Term.evaluate(Term.java:103)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.expandAndEvaluate(KILtoBackendJavaKILTransformer.java:139)
    at org.kframework.backend.java.symbolic.InitializeRewriter$SymbolicRewriterGlue.execute(InitializeRewriter.java:125)
    at org.kframework.krun.modes.KRunExecutionMode.execute(KRunExecutionMode.java:70)
    at org.kframework.krun.KRun.run(KRun.java:75)
    at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:91)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
    at org.kframework.main.Main.runApplication(Main.java:109)
    at org.kframework.main.Main.runApplication(Main.java:99)
    at org.kframework.main.Main.main(Main.java:51)
[Error] Internal: Uncaught exception thrown of type AssertionError.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
```

**Comment by dwightguth** [comment]
We need to re-add the check that throws an error if not all configuration variables have been specified.
