### ISSUE TITLE
CircularityException

### ISSUE THREAD

**Issue by kheradmand** [kframework/k-legacy#1847]
```
require "domains.k"

module BOOLOP-SYNTAX
    syntax And ::=  "and"
    syntax Or ::= "or"
endmodule


module TEST
    imports DOMAINS-SYNTAX
    imports BOOLOP-SYNTAX

    syntax LTLFormula ::=
          Id
         > LTLFormula And LTLFormula  [left]
         > LTLFormula Or LTLFormula  [left]
endmodule
```

`kast -s LTLFormula -e "x and x"` gives me:

```
[Error] Internal: Uncaught exception thrown of type CircularityException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
```

Here is the stack trace:

```
org.kframework.CircularityException: ___ < ___
    at org.kframework.POSet.org$kframework$POSet$$constructAndThrowCycleException(POSet.scala:46)
    at org.kframework.POSet$$anonfun$4.apply(POSet.scala:29)
    at org.kframework.POSet$$anonfun$4.apply(POSet.scala:25)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
    at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
    at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at org.kframework.POSet.transitiveClosure(POSet.scala:25)
    at org.kframework.POSet.<init>(POSet.scala:54)
    at org.kframework.POSet$.apply(POSet.scala:130)
    at org.kframework.definition.Module.priorities$lzycompute(outer.scala:176)
    at org.kframework.definition.Module.priorities(outer.scala:176)
    at org.kframework.parser.concrete2kore.ParseInModule.parseStringTerm(ParseInModule.java:160)
    at org.kframework.parser.concrete2kore.ParseInModule.parseString(ParseInModule.java:101)
    at org.kframework.parser.concrete2kore.ParseInModule.parseString(ParseInModule.java:87)
    at org.kframework.kompile.CompiledDefinition.lambda$getParser$a68fb235$1(CompiledDefinition.java:89)
    at org.kframework.kast.KastFrontEnd.run(KastFrontEnd.java:105)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
    at org.kframework.main.Main.runApplication(Main.java:109)
    at org.kframework.main.Main.runApplication(Main.java:99)
    at org.kframework.main.Main.main(Main.java:51)
org.kframework.CircularityException: ___ < ___
    at org.kframework.POSet.org$kframework$POSet$$constructAndThrowCycleException(POSet.scala:46)
    at org.kframework.POSet$$anonfun$4.apply(POSet.scala:29)
    at org.kframework.POSet$$anonfun$4.apply(POSet.scala:25)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
    at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
    at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at org.kframework.POSet.transitiveClosure(POSet.scala:25)
    at org.kframework.POSet.<init>(POSet.scala:54)
    at org.kframework.POSet$.apply(POSet.scala:130)
    at org.kframework.definition.Module.priorities$lzycompute(outer.scala:176)
    at org.kframework.definition.Module.priorities(outer.scala:176)
    at org.kframework.parser.concrete2kore.ParseInModule.parseStringTerm(ParseInModule.java:160)
    at org.kframework.parser.concrete2kore.ParseInModule.parseString(ParseInModule.java:101)
    at org.kframework.parser.concrete2kore.ParseInModule.parseString(ParseInModule.java:87)
    at org.kframework.kompile.CompiledDefinition.lambda$getParser$a68fb235$1(CompiledDefinition.java:89)
    at org.kframework.kast.KastFrontEnd.run(KastFrontEnd.java:105)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
    at org.kframework.main.Main.runApplication(Main.java:109)
    at org.kframework.main.Main.runApplication(Main.java:99)
    at org.kframework.main.Main.main(Main.java:51)
```

If I change it to something like this:

```
...
       > LTLFormula "and" LTLFormula  [left]
```

It works fine.

**Comment by kheradmand** [comment]
Manual klabel fixed the problem

**Comment by kheradmand** [comment]
@k-oncall my problem was solved but you may want to look at this

**Comment by dwightguth** [comment]
We should probably add a friendly error message for this if we are going to assume that priorities cannot have cycles.
