### ISSUE TITLE
Unexpected exception thrown by the new ktest.

### ISSUE THREAD

**Issue by traiansf** [kframework/k-legacy#192]
I marked this as critical, as it is needed for my students' homework which is due next week.

Steps to reproduce:
cd tutorial/1_k/4_imp++/lesson_5/exercises/no-duplicate-declarations/tests
cp ../../../imp.k .
ktest config.xml 

It should compile and fail all tests (as the exercise is not yet solved) except nodups-0.imp 
Instead of that, after compilation it throws an exception
k/tutorial/1_k/4_imp++/lesson_5/exercises/no-duplicate-declarations/tests$ ktest config.xml --skip "pdf" -v
Kompile the language definitions...(1 in total)
Done with [C:\Users\Traian\Documents\k\bin\kompile.bat c:\Users\Traian\Documents\k\tutorial\1_k\4_imp++\lesson_5\exercises\no-duplicate-declarations\tests\imp.k](time
11028 ms)
Exception in thread "main" java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 3
c:\Users\Traian\Documents\k\tutorial\1_k\4_imp++\lesson_5\exercises\no-duplicate-declarations\tests
   ^
        at java.util.regex.Pattern.error(Pattern.java:1924)
        at java.util.regex.Pattern.escape(Pattern.java:2416)
        at java.util.regex.Pattern.atom(Pattern.java:2164)
        at java.util.regex.Pattern.sequence(Pattern.java:2097)
        at java.util.regex.Pattern.expr(Pattern.java:1964)
        at java.util.regex.Pattern.compile(Pattern.java:1665)
        at java.util.regex.Pattern.<init>(Pattern.java:1337)
        at java.util.regex.Pattern.compile(Pattern.java:1022)
        at java.lang.String.replaceFirst(String.java:2119)
        at org.kframework.ktest.Test.TestSuite.makeRelative(TestSuite.java:407)
        at org.kframework.ktest.Test.TestSuite.runKompileSteps(TestSuite.java:204)
        at org.kframework.ktest.Test.TestSuite.run(TestSuite.java:102)
        at org.kframework.ktest.KTest.run(KTest.java:49)
        at org.kframework.ktest.KTest.main(KTest.java:92)
        at org.kframework.main.Main.main(Main.java:57)

I assigned it to Omer as the exception is thrown from the code he recently pushed.

**Comment by osa1** [comment]
Interesting, it works fine on my system. Apparently this is because Windows style file paths(`\` character), I'll check.

**Comment by osa1** [comment]
@traiansf I pushed a change, can you please try it on a Windows system?

**Comment by traiansf** [comment]
Seems to work now. Thanks a lot! I guess we can consider it fixed, for now.

2013/12/4 Ömer Sinan Ağacan notifications@github.com

**Comment by osa1** [comment]
The problem was Java's `String.replaceFirst` expects only regex as text to replace, while other `replace` methods also have variants that take `CharSequence` argument as text to replace. This became a problem in Windows, because I'm working on file paths and `\` character in file paths of Windows causes problems because for example in `\folder`, `\f` is not a valid regex escape sequence.
