### ISSUE TITLE
kompile error with Windows

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#2015]
Could this be related to #1992, which @dwightguth fixed recently?

```
D:\github\grosu\k\k-distribution\tutorial\1_k\1_lambda\lesson_2>kompile lambda.k
[Error] Critical: Could not find 'required' file: substitution.k
        Source(D:\github\grosu\k\k-distribution\tutorial\1_k\1_lambda\lesson_2\lambda.k)
        Location(3,1,3,24)
D:\github\grosu\k\k-distribution\tutorial\1_k\1_lambda\lesson_2>
```

**Comment by dwightguth** [comment]
To be clear it successfully finds domains.k?

**Comment by grosu** [comment]
I think it does, because everything works if I remove the requires, the imports, and the rewrite rule from:

https://github.com/kframework/k/blob/master/k-distribution/tutorial/1_k/1_lambda/lesson_2/lambda.k

So it is OK with the Id sort defined in domains.k

**Comment by dwightguth** [comment]
That's quite baffling. They're in the same directory, I can't think of any reason why it would be able to find one but not the other. Can you show me the contents of the k-distribution/target/release/k/include/builtin directory for the version of K that is on your path?

**Comment by grosu** [comment]
They are both there:

```
D:\github\grosu\k\k-distribution\tutorial\1_k\1_lambda\lesson_2>ls D:\github\grosu\k\k-distribution/target/release/k/include/builtin
README.txt  domains.k  e-kore.k  kast.k  misc.k  prelude.k  substitution.k  unification.k
```

But note that domains.k is now added automatically, which substitution.k is required manually.  Maybe different code for building the paths is used in the two cases.

**Comment by dwightguth** [comment]
I doubt that's it but if you want to test just add domains.k manually and see if it finds it. It won't harm anything to be required twice I don't think.

**Comment by grosu** [comment]
Looks like that's the problem, indeed.  Lesson 1 works fine without explicit require domains.k, but as soon as I add it,

```
require "domains.k"

module LAMBDA
  syntax Val ::= Id
               | "lambda" Id "." Exp
  syntax Exp ::= Val
               | Exp Exp      [left]
               | "(" Exp ")"  [bracket]
endmodule
```

I get a similar error:

```
D:\github\grosu\k\k-distribution\tutorial\1_k\1_lambda\lesson_1>kompile lambda.k
[Error] Critical: Could not find 'required' file: domains.k
        Source(D:\github\grosu\k\k-distribution\tutorial\1_k\1_lambda\lesson_1\lambda.k)
        Location(3,1,3,19)
```

**Comment by dwightguth** [comment]
Can I see `--debug`? I just realized this error message doesn't look right and I want to make sure you have the right version of the tool.

**Comment by grosu** [comment]
```
D:\github\grosu\k\k-distribution\tutorial\1_k\1_lambda\lesson_2>kompile --version
K framework version 4.0-SNAPSHOT
Git revision: 5842f2a
Git branch: nailgun-passwd
Build date: Thu Oct 29 16:54:46 CDT 2015
D:\github\grosu\k\k-distribution\tutorial\1_k\1_lambda\lesson_2>kompile lambda.k --debug
org.kframework.utils.errorsystem.KEMException: [Error] Critical: Could not find 'required' file: substitution.k
        Source(D:\github\grosu\k\k-distribution\tutorial\1_k\1_lambda\lesson_2\lambda.k)
        Location(3,1,3,24)
        at org.kframework.utils.errorsystem.KExceptionManager.create(KExceptionManager.java:166)
        at org.kframework.utils.errorsystem.KExceptionManager.criticalError(KExceptionManager.java:60)
        at org.kframework.parser.generator.OuterParser.slurp2(OuterParser.java:110)
        at org.kframework.parser.generator.OuterParser.slurp(OuterParser.java:67)
        at org.kframework.parser.DefinitionLoader.parseDefinition(DefinitionLoader.java:104)
        at org.kframework.parser.DefinitionLoader.loadDefinition(DefinitionLoader.java:88)
        at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:117)
        at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:96)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:112)
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:146)
        at org.kframework.main.Main.nailMain(Main.java:73)
        at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:331)
[Error] Critical: Could not find 'required' file: substitution.k
        Source(D:\github\grosu\k\k-distribution\tutorial\1_k\1_lambda\lesson_2\lambda.k)
        Location(3,1,3,24)
D:\github\grosu\k\k-distribution\tutorial\1_k\1_lambda\lesson_2>
```

**Comment by dwightguth** [comment]
Are you sure you're not using K 3.6? This is the stack trace I would expect from the old KIL pipeline.

**Comment by grosu** [comment]
In case others run into the same issue: I just happened to have a kserver started from antique K3.6 times.  All I had to do was to run stop-kserver.  Thanks @dwightguth
