### ISSUE TITLE
java.lang.AssertionError: unexpected concatenated termorg.kframework.backend.java.kil.Bottom@107f4980

### ISSUE THREAD

**Issue by egunter** [kframework/k-legacy#2154]
I will give you may files, but it doesn't accept .k files, so I have renamed then .txt files.

[arith.txt](https://github.com/kframework/k/files/166406/arith.txt)
[bool.txt](https://github.com/kframework/k/files/166407/bool.txt)
[arithbool.txt](https://github.com/kframework/k/files/166408/arithbool.txt)
[simp3.txt](https://github.com/kframework/k/files/166412/simp3.txt)
[test.txt](https://github.com/kframework/k/files/166413/test.txt)
# 
# stack trace below here

bash-3.2$ krun test.simpl3
[Error] Internal: Uncaught exception thrown of type AssertionError.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
bash-3.2$ krun --debug test.simpl3
java.lang.AssertionError: unexpected concatenated termorg.kframework.backend.java.kil.Bottom@107f4980
    at org.kframework.backend.java.kil.KList$Builder.concatenate(KList.java:192)
    at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:305)
    at org.kframework.backend.java.symbolic.SubstituteAndEvaluateTransformer.transform(SubstituteAndEvaluateTransformer.java:124)
    at org.kframework.backend.java.kil.KList.accept(KList.java:152)
    at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:208)
    at org.kframework.backend.java.symbolic.SubstituteAndEvaluateTransformer.transform(SubstituteAndEvaluateTransformer.java:115)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:743)
    at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:301)
    at org.kframework.backend.java.symbolic.SubstituteAndEvaluateTransformer.transform(SubstituteAndEvaluateTransformer.java:124)
    at org.kframework.backend.java.kil.KList.accept(KList.java:152)
    at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:208)
    at org.kframework.backend.java.symbolic.SubstituteAndEvaluateTransformer.transform(SubstituteAndEvaluateTransformer.java:115)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:743)
    at org.kframework.backend.java.kil.Term.substituteAndEvaluate(Term.java:115)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.buildRHS(SymbolicRewriter.java:391)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.buildRHS(SymbolicRewriter.java:411)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.buildRHS(SymbolicRewriter.java:411)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.fastComputeRewriteStep(SymbolicRewriter.java:273)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.computeRewriteStep(SymbolicRewriter.java:108)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.rewrite(SymbolicRewriter.java:88)
    at org.kframework.backend.java.symbolic.InitializeRewriter$SymbolicRewriterGlue.execute(InitializeRewriter.java:137)
    at org.kframework.krun.modes.KRunExecutionMode.execute(KRunExecutionMode.java:70)
    at org.kframework.krun.KRun.run(KRun.java:86)
    at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:97)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
    at org.kframework.main.Main.runApplication(Main.java:110)
    at org.kframework.main.Main.runApplication(Main.java:100)
    at org.kframework.main.Main.main(Main.java:52)
java.lang.AssertionError: unexpected concatenated termorg.kframework.backend.java.kil.Bottom@107f4980
    at org.kframework.backend.java.kil.KList$Builder.concatenate(KList.java:192)
    at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:305)
    at org.kframework.backend.java.symbolic.SubstituteAndEvaluateTransformer.transform(SubstituteAndEvaluateTransformer.java:124)
    at org.kframework.backend.java.kil.KList.accept(KList.java:152)
    at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:208)
    at org.kframework.backend.java.symbolic.SubstituteAndEvaluateTransformer.transform(SubstituteAndEvaluateTransformer.java:115)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:743)
    at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:301)
    at org.kframework.backend.java.symbolic.SubstituteAndEvaluateTransformer.transform(SubstituteAndEvaluateTransformer.java:124)
    at org.kframework.backend.java.kil.KList.accept(KList.java:152)
    at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:208)
    at org.kframework.backend.java.symbolic.SubstituteAndEvaluateTransformer.transform(SubstituteAndEvaluateTransformer.java:115)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:743)
    at org.kframework.backend.java.kil.Term.substituteAndEvaluate(Term.java:115)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.buildRHS(SymbolicRewriter.java:391)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.buildRHS(SymbolicRewriter.java:411)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.buildRHS(SymbolicRewriter.java:411)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.fastComputeRewriteStep(SymbolicRewriter.java:273)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.computeRewriteStep(SymbolicRewriter.java:108)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.rewrite(SymbolicRewriter.java:88)
    at org.kframework.backend.java.symbolic.InitializeRewriter$SymbolicRewriterGlue.execute(InitializeRewriter.java:137)
    at org.kframework.krun.modes.KRunExecutionMode.execute(KRunExecutionMode.java:70)
    at org.kframework.krun.KRun.run(KRun.java:86)
    at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:97)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
    at org.kframework.main.Main.runApplication(Main.java:110)
    at org.kframework.main.Main.runApplication(Main.java:100)
    at org.kframework.main.Main.main(Main.java:52)
[Error] Internal: Uncaught exception thrown of type AssertionError.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
bash-3.2$

**Comment by andreistefanescu** [comment]
The exception is generated by applying this rule

```
  rule <k> lvalue Id => ref(!L) ...</k>
       <loc> Loc:Map (.Map => Id |-> Loc[!L]) </loc>
       requires (notBool(Id in keys(Loc)))
```

on the term

```
<T> <k> ( lvalue x ) ~> #freezerassign__1 ( 0 ) ~> #freezer_;_1 ( ( y := 0 ) ; ( z := 0 ) ; skip ) </k> <loc> .Map </loc> <mem> .Map </mem> </T>
```

by the fact that lookup `Loc[!L]` returns bottom (since `!L` is fresh, the map is always undefined for it).

I will add a patch to have a meaningful error message. In the meantime, is this information enough to fix the rule?

**Comment by egunter** [comment]
Dear Andrei,
   I've already fixed it.  When I sent the bug report, I had assumed it 
was another problem.  I had an event in class when I used concrete 
syntax for assignment (A := B) and it would not parse the rule (if I 
remember, it kept insisting it need parentheses, but when I but them it 
it complained about having them), but when switched to (_:=_(A,B)) it 
seemed happy.  I added the offending rule this evening without looking 
at what I had written (the Loc[] should not have been there), and I 
moved the rule above it and some others and used concrete syntax.  I was 
testing if the new location would impact the parsing issue when I got 
the message that there was a bug that I should report, and so I did.  
I'm not sure I can reproduce the parsing problem, I will send you my 
file.  I sort of assume there will be a type error or something like 
that at the bottom of it, but moving the rule seems to have fixed the 
problem, which feels wrong to me.  Anyway, thank you for the feedback.
---Elsa
