### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by egunter** [kframework/k-legacy#2167]
bash-3.2$ kompile --debug mp2.k
java.lang.NullPointerException
    at scala.collection.convert.Wrappers$SetWrapper$$anon$4.<init>(Wrappers.scala:115)
    at scala.collection.convert.Wrappers$SetWrapper.iterator(Wrappers.scala:114)
    at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
    at org.kframework.Collections$.mutable(collections.scala:28)
    at org.kframework.Collections.mutable(collections.scala)
    at org.kframework.kore.compile.SortCells.nthArgSort(SortCells.java:858)
    at org.kframework.kore.compile.SortCells.access$800(SortCells.java:58)
    at org.kframework.kore.compile.SortCells$3.apply(SortCells.java:563)
    at org.kframework.kore.compile.SortCells$3.apply(SortCells.java:548)
    at org.kframework.kore.KTransformer$class.apply(transformers.scala:11)
    at org.kframework.kore.AbstractKTransformer.apply(transformers.scala:112)
    at org.kframework.kore.TransformK.apply(TransformK.java:39)
    at org.kframework.kore.TransformK.apply(TransformK.java:13)
    at org.kframework.kore.KTransformer$class.apply(transformers.scala:12)
    at org.kframework.kore.AbstractKTransformer.apply(transformers.scala:112)
    at org.kframework.kore.TransformK.apply(TransformK.java:63)
    at org.kframework.kore.TransformK.apply(TransformK.java:13)
    at org.kframework.kore.KTransformer$class.apply(transformers.scala:15)
    at org.kframework.kore.AbstractKTransformer.apply(transformers.scala:112)
    at org.kframework.kore.TransformK.apply(TransformK.java:21)
    at org.kframework.kore.compile.SortCells$3.apply(SortCells.java:551)
    at org.kframework.kore.compile.SortCells$3.apply(SortCells.java:548)
    at org.kframework.kore.KTransformer$class.apply(transformers.scala:11)
    at org.kframework.kore.AbstractKTransformer.apply(transformers.scala:112)
    at org.kframework.kore.compile.SortCells.resolveIncompleteCellFragment(SortCells.java:674)
    at org.kframework.kore.compile.SortCells.sortCells(SortCells.java:91)
    at org.kframework.kore.compile.SortCells.sortCells(SortCells.java:110)
    at org.kframework.kore.compile.ConcretizeCells.concretize(ConcretizeCells.java:66)
    at org.kframework.kore.compile.ConcretizeCells$$Lambda$153/526318751.apply(Unknown Source)
    at org.kframework.definition.ModuleTransformer$$anonfun$fromSentenceTransformer$1.apply(transformers.scala:16)
    at org.kframework.definition.ModuleTransformer$$anonfun$fromSentenceTransformer$1.apply(transformers.scala:16)
    at org.kframework.definition.ModuleTransformer$$anonfun$fromSentenceTransformer$2$$anonfun$3.apply(transformers.scala:22)
    at org.kframework.definition.ModuleTransformer$$anonfun$fromSentenceTransformer$2$$anonfun$3.apply(transformers.scala:20)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
    at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
    at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
    at scala.collection.SetLike$class.map(SetLike.scala:92)
    at scala.collection.AbstractSet.map(Set.scala:47)
    at org.kframework.definition.ModuleTransformer$$anonfun$fromSentenceTransformer$2.apply(transformers.scala:20)
    at org.kframework.definition.ModuleTransformer$$anonfun$fromSentenceTransformer$2.apply(transformers.scala:19)
    at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:73)
    at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:70)
    at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:901)
    at org.kframework.definition.ModuleTransformer.apply(transformers.scala:70)
    at org.kframework.definition.ModuleTransformer.apply(transformers.scala:66)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
    at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
    at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
    at scala.collection.SetLike$class.map(SetLike.scala:92)
    at scala.collection.AbstractSet.map(Set.scala:47)
    at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:115)
    at org.kframework.kore.compile.ConcretizeCells.transformDefinition(ConcretizeCells.java:46)
    at org.kframework.kompile.Kompile$$Lambda$125/1957193053.apply(Unknown Source)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at org.kframework.kompile.Kompile.lambda$defaultSteps$110(Kompile.java:156)
    at org.kframework.kompile.Kompile$$Lambda$120/1817055393.apply(Unknown Source)
    at org.kframework.backend.java.symbolic.JavaBackend.lambda$null$5ca3f9c9$1(JavaBackend.java:84)
    at org.kframework.backend.java.symbolic.JavaBackend$$Lambda$108/1826494455.apply(Unknown Source)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at org.kframework.backend.java.symbolic.JavaBackend.lambda$steps$164(JavaBackend.java:99)
    at org.kframework.backend.java.symbolic.JavaBackend$$Lambda$15/1904783235.apply(Unknown Source)
    at org.kframework.kompile.Kompile.run(Kompile.java:120)
    at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:69)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
    at org.kframework.main.Main.runApplication(Main.java:110)
    at org.kframework.main.Main.runApplication(Main.java:100)
    at org.kframework.main.Main.main(Main.java:52)
java.lang.NullPointerException
    at scala.collection.convert.Wrappers$SetWrapper$$anon$4.<init>(Wrappers.scala:115)
    at scala.collection.convert.Wrappers$SetWrapper.iterator(Wrappers.scala:114)
    at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
    at org.kframework.Collections$.mutable(collections.scala:28)
    at org.kframework.Collections.mutable(collections.scala)
    at org.kframework.kore.compile.SortCells.nthArgSort(SortCells.java:858)
    at org.kframework.kore.compile.SortCells.access$800(SortCells.java:58)
    at org.kframework.kore.compile.SortCells$3.apply(SortCells.java:563)
    at org.kframework.kore.compile.SortCells$3.apply(SortCells.java:548)
    at org.kframework.kore.KTransformer$class.apply(transformers.scala:11)
    at org.kframework.kore.AbstractKTransformer.apply(transformers.scala:112)
    at org.kframework.kore.TransformK.apply(TransformK.java:39)
    at org.kframework.kore.TransformK.apply(TransformK.java:13)
    at org.kframework.kore.KTransformer$class.apply(transformers.scala:12)
    at org.kframework.kore.AbstractKTransformer.apply(transformers.scala:112)
    at org.kframework.kore.TransformK.apply(TransformK.java:63)
    at org.kframework.kore.TransformK.apply(TransformK.java:13)
    at org.kframework.kore.KTransformer$class.apply(transformers.scala:15)
    at org.kframework.kore.AbstractKTransformer.apply(transformers.scala:112)
    at org.kframework.kore.TransformK.apply(TransformK.java:21)
    at org.kframework.kore.compile.SortCells$3.apply(SortCells.java:551)
    at org.kframework.kore.compile.SortCells$3.apply(SortCells.java:548)
    at org.kframework.kore.KTransformer$class.apply(transformers.scala:11)
    at org.kframework.kore.AbstractKTransformer.apply(transformers.scala:112)
    at org.kframework.kore.compile.SortCells.resolveIncompleteCellFragment(SortCells.java:674)
    at org.kframework.kore.compile.SortCells.sortCells(SortCells.java:91)
    at org.kframework.kore.compile.SortCells.sortCells(SortCells.java:110)
    at org.kframework.kore.compile.ConcretizeCells.concretize(ConcretizeCells.java:66)
    at org.kframework.kore.compile.ConcretizeCells$$Lambda$153/526318751.apply(Unknown Source)
    at org.kframework.definition.ModuleTransformer$$anonfun$fromSentenceTransformer$1.apply(transformers.scala:16)
    at org.kframework.definition.ModuleTransformer$$anonfun$fromSentenceTransformer$1.apply(transformers.scala:16)
    at org.kframework.definition.ModuleTransformer$$anonfun$fromSentenceTransformer$2$$anonfun$3.apply(transformers.scala:22)
    at org.kframework.definition.ModuleTransformer$$anonfun$fromSentenceTransformer$2$$anonfun$3.apply(transformers.scala:20)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
    at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
    at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
    at scala.collection.SetLike$class.map(SetLike.scala:92)
    at scala.collection.AbstractSet.map(Set.scala:47)
    at org.kframework.definition.ModuleTransformer$$anonfun$fromSentenceTransformer$2.apply(transformers.scala:20)
    at org.kframework.definition.ModuleTransformer$$anonfun$fromSentenceTransformer$2.apply(transformers.scala:19)
    at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:73)
    at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:70)
    at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:901)
    at org.kframework.definition.ModuleTransformer.apply(transformers.scala:70)
    at org.kframework.definition.ModuleTransformer.apply(transformers.scala:66)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
    at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
    at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
    at scala.collection.SetLike$class.map(SetLike.scala:92)
    at scala.collection.AbstractSet.map(Set.scala:47)
    at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:115)
    at org.kframework.kore.compile.ConcretizeCells.transformDefinition(ConcretizeCells.java:46)
    at org.kframework.kompile.Kompile$$Lambda$125/1957193053.apply(Unknown Source)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at org.kframework.kompile.Kompile.lambda$defaultSteps$110(Kompile.java:156)
    at org.kframework.kompile.Kompile$$Lambda$120/1817055393.apply(Unknown Source)
    at org.kframework.backend.java.symbolic.JavaBackend.lambda$null$5ca3f9c9$1(JavaBackend.java:84)
    at org.kframework.backend.java.symbolic.JavaBackend$$Lambda$108/1826494455.apply(Unknown Source)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
    at org.kframework.backend.java.symbolic.JavaBackend.lambda$steps$164(JavaBackend.java:99)
    at org.kframework.backend.java.symbolic.JavaBackend$$Lambda$15/1904783235.apply(Unknown Source)
    at org.kframework.kompile.Kompile.run(Kompile.java:120)
    at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:69)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
    at org.kframework.main.Main.runApplication(Main.java:110)
    at org.kframework.main.Main.runApplication(Main.java:100)
    at org.kframework.main.Main.main(Main.java:52)
[Error] Internal: Uncaught exception thrown of type NullPointerException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
bash-3.2$ 
[mp2-k.txt](https://github.com/kframework/k/files/216363/mp2-k.txt)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/148313234996210/148313550259854)

**Comment by egunter** [comment]
Adding "imports TOP-CONFIG" to module mp2  fixes the problem.
---Elsa

**Comment by cos** [comment]
It's likely the configuration was declared in a module which was not (transitively) imported. We'll have to improve the error message. Thank you!

**Comment by omarzd** [comment]
@cos. Just curious. I'm wondering if you can you reproduce this in order to test it.

**Comment by cos** [comment]
If the problem is what I think it is, simply refer to a non-existent cell within a rule. E.g.:

```
rule <neverDefined> 0 </neverDefined>
```

**Comment by HelenRouty** [comment]
Hello, we tried to reproduce this bug but could not. What we did is: `kompile --debug k-distribution/tutorial/1_k/2_imp/lesson_4/mp2.k`. mp2.k is renamed after mp2-k.txt downloaded from this page. We deleted the  TOP-CONFIG module and added a line:  `rule <neverDefined> 0 </neverDefined>` in module MP2. However, we only got an expected error `Parse error: unexpected character '<'. `  If we replaced the rule with `rule <k> 0 </k>`. Then there won't be any error. Could you give us more specific instructions on how to reproduce the NullPointerException error?

Also, what is the expected result after fixing this error?

Thank you!

**Comment by cos** [comment]
Great, it seems the bug is already fixed then.
