### ISSUE TITLE
java.lang.AssertionError: assertion failed

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#2176]
Hello. I have an interesting case here. My project worked correctly on K3.5 and K3.6. However, in the latest master of K4.0, I am getting a `java.lang.AssertionError` on `kompile`. I spent a couple of hours minimizing the project into the following code to pinpoint the cause of the problem:

```
module TEST-SYNTAX

  syntax Pgm ::= Call
  syntax Call ::= Id "(" Call ")"    [strict(2)]  

endmodule

module TEST
  imports TEST-SYNTAX
  imports KCELLS

  configuration   
    <T>
      <threads>
        <thread multiplicity="*">
          <k> 0 </k>  
          <publish> .List </publish>  
        </thread>
      </threads> 
    </T>


  syntax Bool ::= anyCall(Bag) [function]
  rule anyCall(_:Bag) => true

  rule
    <threads>
      (A:Bag => .Bag)
      <thread>...
        <k> _ => .K </k>
      ...</thread>      
    </threads>
    when anyCall(A)

endmodule
```

It will `kompile` successfully if we remove either of `[strict(2)]`, the side condition `when anyCall(A)`, or the `<thread>` cell in that rule.

And here's the error trace:

```
java.lang.AssertionError: assertion failed
  at scala.Predef$.assert(Predef.scala:151)
  at org.kframework.kore.compile.AssocCommToAssoc.convert(AssocCommToAssoc.scala:81)
  at org.kframework.kore.compile.AssocCommToAssoc.apply(AssocCommToAssoc.scala:58)
  at org.kframework.kore.compile.AssocCommToAssoc$$anonfun$apply$4.apply(AssocCommToAssoc.scala:60)
  at org.kframework.kore.compile.AssocCommToAssoc$$anonfun$apply$4.apply(AssocCommToAssoc.scala:60)
  at scala.collection.immutable.List.map(List.scala:273)
  at org.kframework.kore.compile.AssocCommToAssoc.apply(AssocCommToAssoc.scala:60)
  at org.kframework.kore.compile.AssocCommToAssoc$$anonfun$apply$4.apply(AssocCommToAssoc.scala:60)
  at org.kframework.kore.compile.AssocCommToAssoc$$anonfun$apply$4.apply(AssocCommToAssoc.scala:60)
  at scala.collection.immutable.List.map(List.scala:273)
  at org.kframework.kore.compile.AssocCommToAssoc.apply(AssocCommToAssoc.scala:60)
  at org.kframework.kore.compile.AssocCommToAssoc.apply(AssocCommToAssoc.scala:28)
  at org.kframework.kore.compile.AssocCommToAssoc$$anonfun$apply$1.apply(AssocCommToAssoc.scala:22)
  at org.kframework.kore.compile.AssocCommToAssoc$$anonfun$apply$1.apply(AssocCommToAssoc.scala:22)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
  at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
  at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
  at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
  at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
  at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
  at org.kframework.kore.compile.AssocCommToAssoc.apply(AssocCommToAssoc.scala:22)
  at org.kframework.kore.compile.AssocCommToAssoc.apply(AssocCommToAssoc.scala:13)
  at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:75)
  at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:70)
  at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:901)
  at org.kframework.definition.ModuleTransformer.apply(transformers.scala:70)
  at org.kframework.definition.ModuleTransformer.apply(transformers.scala:66)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
  at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
  at scala.collection.SetLike$class.map(SetLike.scala:92)
  at scala.collection.AbstractSet.map(Set.scala:47)
  at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:71)
  at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:70)
  at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:901)
  at org.kframework.definition.ModuleTransformer.apply(transformers.scala:70)
  at org.kframework.definition.SelectiveDefinitionTransformer.apply(transformers.scala:134)
  at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:119)
  at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:111)
  at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
  at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
  at org.kframework.backend.java.symbolic.JavaBackend.lambda$steps$0(JavaBackend.java:93)
  at org.kframework.kompile.Kompile.run(Kompile.java:120)
  at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:69)
  at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
  at org.kframework.main.Main.runApplication(Main.java:110)
  at org.kframework.main.Main.runApplication(Main.java:100)
  at org.kframework.main.Main.main(Main.java:52)
[Error] Internal: Uncaught exception thrown of type AssertionError.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
```

**Comment by omarzd** [comment]
I hope I made it clear. Can anyone explain it? Is it a bug or is it intended?

**Comment by andreistefanescu** [comment]
This is a limitation of current implementation: associative and commutative matching is compiled to associative only matching, and having a side condition on `A` is not supported. For now, maybe it's faster/simpler to refactor the rule to avoid the side condition. I believe it would look something like this:

```
rule
    <threads>
        A:Bag
        <thread>...
            <k> .K => anyCall(A) ...</k>
        ...</thread>
    </threads>
rule
    <threads>
        (A:Bag => .Bag)
        <thread>...
            <k> true ~> _ => .K ...</k>
        ...</thread>
    </threads>
```

**Comment by omarzd** [comment]
@andreistefanescu Your rules still produce the same error. You can test it yourself on my minimal example. Using `anyCall(A)` itself on a bag of threads _is_ what's causing the problem, not that it's in a side condition.

**Comment by andreistefanescu** [comment]
Ok, I will take a look over the weekend and get back to you.

**Comment by omarzd** [comment]
OK. So I made it simpler and avoided the side condition. Removing any of the following three will make it `kompile` successfully:
- The call `truth(A)` where `A` is a `Bag`.
- The `strict` attribute even though it's in a totally independent production.
- The `multiplicity="*"` for cell `thread`.

```
module TEST
  imports KCELLS

  configuration   
    <T>
      <threads>
        <thread multiplicity="*">
          <k> false </k>  
        </thread>
      </threads> 
    </T>

  syntax UnusedSort ::= Bool  [klabel(NeedKlabelForStrictness) , strict]
  syntax KResult ::= Bool
  syntax Bool ::= truth(Bag) [function]
  rule truth(_:Bag) => true

  rule
    <threads>
      (A:Bag => .Bag)
      <thread>...
        <k> _ => truth(A) </k>
      ...</thread>      
    </threads>

endmodule
```

**Comment by omarzd** [comment]
Removing `multiplicity="*"` and adding another cell next to `thread` will make another error appear:

```
[Error] Compiler: Closed parent cell missing required children [] on left hand
side and [SomeOtherCellCell] on right hand side.
  while executing phase "concretizing configuration" on sentence at
        Source(test.k)
        Location(20,5,25,15)
```
