### ISSUE TITLE
NullPointerException again

### ISSUE THREAD

**Issue by egunter** [kframework/k-legacy#2178]
bash-3.2$ krun --debug tests/intconst 
java.lang.NullPointerException
    at org.kframework.backend.java.util.Subsorts.isSubsorted(Subsorts.java:81)
    at org.kframework.backend.java.util.Subsorts.isSubsortedEq(Subsorts.java:90)
    at org.kframework.backend.java.kil.KItem.computeSort(KItem.java:212)
    at org.kframework.backend.java.kil.KItem.sort(KItem.java:695)
    at org.kframework.backend.java.kil.RuleAutomatonDisjunction.lambda$new$74(RuleAutomatonDisjunction.java:65)
    at org.kframework.backend.java.kil.RuleAutomatonDisjunction$$Lambda$81/817944369.apply(Unknown Source)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at org.kframework.backend.java.kil.RuleAutomatonDisjunction.<init>(RuleAutomatonDisjunction.java:65)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.KApply1(KOREtoBackendKIL.java:108)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.convert(KOREtoBackendKIL.java:300)
    at org.kframework.backend.java.compile.KOREtoBackendKIL$$Lambda$53/790538253.apply(Unknown Source)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.KList(KOREtoBackendKIL.java:84)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.KApply1(KOREtoBackendKIL.java:113)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.convert(KOREtoBackendKIL.java:300)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.lambda$KApply1$124(KOREtoBackendKIL.java:108)
    at org.kframework.backend.java.compile.KOREtoBackendKIL$$Lambda$78/1164344728.apply(Unknown Source)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.KApply1(KOREtoBackendKIL.java:108)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.convert(KOREtoBackendKIL.java:300)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.convertKRewrite(KOREtoBackendKIL.java:212)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.KApply1(KOREtoBackendKIL.java:103)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.convert(KOREtoBackendKIL.java:300)
    at org.kframework.backend.java.compile.KOREtoBackendKIL$$Lambda$53/790538253.apply(Unknown Source)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.KList(KOREtoBackendKIL.java:84)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.KApply1(KOREtoBackendKIL.java:113)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.convert(KOREtoBackendKIL.java:300)
    at org.kframework.backend.java.compile.KOREtoBackendKIL$$Lambda$53/790538253.apply(Unknown Source)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.KList(KOREtoBackendKIL.java:84)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.KApply1(KOREtoBackendKIL.java:113)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.convert(KOREtoBackendKIL.java:300)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.convert(KOREtoBackendKIL.java:374)
    at org.kframework.backend.java.kil.Definition.addKoreRules(Definition.java:333)
    at org.kframework.backend.java.symbolic.InitializeRewriter$InitializeDefinition.invoke(InitializeRewriter.java:216)
    at org.kframework.backend.java.symbolic.InitializeRewriter.apply(InitializeRewriter.java:94)
    at org.kframework.backend.java.symbolic.InitializeRewriter.apply(InitializeRewriter.java:51)
    at org.kframework.krun.KRun.run(KRun.java:84)
    at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:97)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
    at org.kframework.main.Main.runApplication(Main.java:110)
    at org.kframework.main.Main.runApplication(Main.java:100)
    at org.kframework.main.Main.main(Main.java:52)
java.lang.NullPointerException
    at org.kframework.backend.java.util.Subsorts.isSubsorted(Subsorts.java:81)
    at org.kframework.backend.java.util.Subsorts.isSubsortedEq(Subsorts.java:90)
    at org.kframework.backend.java.kil.KItem.computeSort(KItem.java:212)
    at org.kframework.backend.java.kil.KItem.sort(KItem.java:695)
    at org.kframework.backend.java.kil.RuleAutomatonDisjunction.lambda$new$74(RuleAutomatonDisjunction.java:65)
    at org.kframework.backend.java.kil.RuleAutomatonDisjunction$$Lambda$81/817944369.apply(Unknown Source)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at org.kframework.backend.java.kil.RuleAutomatonDisjunction.<init>(RuleAutomatonDisjunction.java:65)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.KApply1(KOREtoBackendKIL.java:108)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.convert(KOREtoBackendKIL.java:300)
    at org.kframework.backend.java.compile.KOREtoBackendKIL$$Lambda$53/790538253.apply(Unknown Source)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.KList(KOREtoBackendKIL.java:84)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.KApply1(KOREtoBackendKIL.java:113)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.convert(KOREtoBackendKIL.java:300)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.lambda$KApply1$124(KOREtoBackendKIL.java:108)
    at org.kframework.backend.java.compile.KOREtoBackendKIL$$Lambda$78/1164344728.apply(Unknown Source)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.KApply1(KOREtoBackendKIL.java:108)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.convert(KOREtoBackendKIL.java:300)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.convertKRewrite(KOREtoBackendKIL.java:212)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.KApply1(KOREtoBackendKIL.java:103)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.convert(KOREtoBackendKIL.java:300)
    at org.kframework.backend.java.compile.KOREtoBackendKIL$$Lambda$53/790538253.apply(Unknown Source)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.KList(KOREtoBackendKIL.java:84)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.KApply1(KOREtoBackendKIL.java:113)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.convert(KOREtoBackendKIL.java:300)
    at org.kframework.backend.java.compile.KOREtoBackendKIL$$Lambda$53/790538253.apply(Unknown Source)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.KList(KOREtoBackendKIL.java:84)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.KApply1(KOREtoBackendKIL.java:113)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.convert(KOREtoBackendKIL.java:300)
    at org.kframework.backend.java.compile.KOREtoBackendKIL.convert(KOREtoBackendKIL.java:374)
    at org.kframework.backend.java.kil.Definition.addKoreRules(Definition.java:333)
    at org.kframework.backend.java.symbolic.InitializeRewriter$InitializeDefinition.invoke(InitializeRewriter.java:216)
    at org.kframework.backend.java.symbolic.InitializeRewriter.apply(InitializeRewriter.java:94)
    at org.kframework.backend.java.symbolic.InitializeRewriter.apply(InitializeRewriter.java:51)
    at org.kframework.krun.KRun.run(KRun.java:84)
    at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:97)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
    at org.kframework.main.Main.runApplication(Main.java:110)
    at org.kframework.main.Main.runApplication(Main.java:100)
    at org.kframework.main.Main.main(Main.java:52)
[Error] Internal: Uncaught exception thrown of type NullPointerException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
bash-3.2$ 
[fun.k.txt](https://github.com/kframework/k/files/253725/fun.k.txt)
[final.k.txt](https://github.com/kframework/k/files/253726/final.k.txt)
[intconst.txt](https://github.com/kframework/k/files/253727/intconst.txt)

**Comment by egunter** [comment]
This one seems different from the last one. <tenv> is defined in the configuration in FUN and FUN is imported into FINAL.
---Elsa

**Comment by egunter** [comment]
If you comment out the line

  rule typecheck B:Bool => bool

then ti behaves as I would expect. In particular, it does not throw a NullPointerException.
---Elsa

**Comment by egunter** [comment]
I have distilled the code displaying the bug down to the following:

/\* File: final.k */

module FINAL-SYNTAX
  syntax Ty ::= "int" | "bool"
  syntax Exp ::= Int | Bool
endmodule

module FINAL
  imports FINAL-SYNTAX
  syntax KItem ::= "typecheck" Exp
  configuration <Top> <k> typecheck $PGM:Exp </k> </Top>
  syntax Val ::= Int | Bool
  syntax GenExp ::= Exp | "anything" GenExp  [strict(1)]

  syntax KResult ::= Ty
  rule typecheck _:Int => int
  rule typecheck _:Bool => bool
endmodule

I haven't thought of any useful reductions of this that still display the bug.
---Elsa

**Comment by cos** [comment]
We should have better error messages for this, but the problem stems from:

```
syntax KItem ::= "typecheck" Exp
```

In K 3.6 subsorting to `KItem` put `"typecheck" Exp` under the bottom sort. This is no longer true in 4.0. To solve the problem, simply make sure that the definition is properly sorted, e.g., `syntax Exp ::= "typecheck" Exp` solves the problem. I see there a `GenExp`. Was the definition intended to be as below?

```
module FINAL-SYNTAX
  syntax Ty ::= "int" | "bool"
  syntax Exp ::= Int | Bool
endmodule

module FINAL
  imports FINAL-SYNTAX
  syntax TypeCheckExp ::= "typecheck" Exp [strict(1)]
  configuration <Top> <k> typecheck $PGM:Exp </k> </Top>
  syntax Val ::= Int | Bool
  syntax GenExp ::= Exp | TypeCheckExp  

  syntax KResult ::= Ty
  rule typecheck _:Int => int
  rule typecheck _:Bool => bool
endmodule
```

That would work as well.

**Comment by cos** [comment]
I will leave this open so we eventually improve the error message. Thank you!

**Comment by egunter** [comment]
The reason for leaving typecheck Exp at type KItem is to allow the students the freedom to choose how implement it.  It may have been better to create a new syntactic category and place type check Exp in that, but I do not understand how it is a mistake to declare it an element of the almost-top sort KItem, unless you just decided this is to be a language feature from here out.  By the way where is this documented?  I have bee using it throughout the semester for entities that may be thought of as only having side effects, or in the applicative programming world as returning unit.  This is the first time it has gotten me in trouble, and the original code base found in the original fun.k has been successfully used by about a third of the class to complete the assignment this student who generated the final.k code I gave you is the first to have triggered this message.  If my code has syntactic errors in it why did it compile?  Why does it work if I remove the line about GenExp, which is doing nothing in the code executing (intentionally so, for purposes of displaying what I still maintain most firmly is a bug)?  And, if it is disallowed to declare syntactic constructs as being of type KItem, why does it appear to have been done 14 times in tutorial/2_languages/2_kool/1_untyped/kool-untyped.k?  
---Elsa

**Comment by cos** [comment]
Yes, using the `KItem` top sort is more flexible but the flexibility comes with some fragility. 

@andreistefanescu , you might be know better how to handle this: `RuleAutomatonDisjunction` still uses the old subset computation code in `org.kframework.backend.java.util.Subsorts` and fails to compute an upper bound for `Bool` and `Int`. For some reason, it doesn't like that there is no direct relation between `Val` and the `Exp` upper bound "candidate".

**Comment by cos** [comment]
`.getLUBSort` returns `null` which then breaks the `RuleAutomatonDisjunction` constructor.

**Comment by cos** [comment]
It probably shouldn't be hard to fix but it's probably better to provide a workaround instead of a fix at this point.

**Comment by andreistefanescu** [comment]
Probably the best solution is to add a check that if `.getLUBSort` returns `null`, then use "KItem" instead.

**Comment by cos** [comment]
This K binary that should fix the problem:

https://github.com/kframework/k/releases/download/untagged-91d96e2f22f24f4c96d2/k-distribution-4.0-beta.zip
