### ISSUE TITLE
Strange behavior on Windows 8

### ISSUE THREAD

**Issue by IaroslavMazur** [kframework/k-legacy#2218]
Here is my definition:

```
module EXP-SYNTAX
  syntax Ids ::= List{Id, ";"}
endmodule

module EXP
  imports EXP-SYNTAX
endmodule
```

Compiling works, but the following test fails. Here is the content I'm trying to parse:

```
a, b
```

Here is my output:

```
>kast text.exp
[Error] Internal: Uncaught exception thrown of type NoClassDefFoundError.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
```

Here is my output with --debug:

```
>kast text.exp --debug
java.lang.NoClassDefFoundError: scala/reflect/runtime/package$
        at org.kframework.meta.Reflection$.<init>(Reflection.scala:7)
        at org.kframework.meta.Reflection$.<clinit>(Reflection.scala)
        at org.kframework.meta.Down.apply(Down.scala:29)
        at org.kframework.meta.Down.apply(Down.scala:11)
        at scala.Option.map(Option.scala:146)
        at org.kframework.attributes.Att.get(Att.scala:24)
        at org.kframework.parser.concrete2kore.kernel.KSyntax2GrammarStatesFilte
r.processProductions(KSyntax2GrammarStatesFilter.java:142)
        at org.kframework.parser.concrete2kore.kernel.KSyntax2GrammarStatesFilte
r.lambda$getGrammar$92(KSyntax2GrammarStatesFilter.java:51)
        at java.util.HashMap.forEach(Unknown Source)
        at org.kframework.parser.concrete2kore.kernel.KSyntax2GrammarStatesFilte
r.getGrammar(KSyntax2GrammarStatesFilter.java:51)
        at org.kframework.parser.concrete2kore.ParseInModule.getGrammar(ParseInM
odule.java:93)
        at org.kframework.parser.concrete2kore.ParseInModule.parseStringTerm(Par
seInModule.java:127)
        at org.kframework.parser.concrete2kore.ParseInModule.parseString(ParseIn
Module.java:101)
        at org.kframework.parser.concrete2kore.ParseInModule.parseString(ParseIn
Module.java:87)
        at org.kframework.kompile.CompiledDefinition.lambda$getParser$a68fb235$1
(CompiledDefinition.java:161)
        at org.kframework.kast.KastFrontEnd.run(KastFrontEnd.java:105)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:110)
        at org.kframework.main.Main.runApplication(Main.java:100)
        at org.kframework.main.Main.main(Main.java:52)
Caused by: java.lang.ClassNotFoundException: scala.reflect.runtime.package$
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 20 more
java.lang.NoClassDefFoundError: scala/reflect/runtime/package$
        at org.kframework.meta.Reflection$.<init>(Reflection.scala:7)
        at org.kframework.meta.Reflection$.<clinit>(Reflection.scala)
        at org.kframework.meta.Down.apply(Down.scala:29)
        at org.kframework.meta.Down.apply(Down.scala:11)
        at scala.Option.map(Option.scala:146)
        at org.kframework.attributes.Att.get(Att.scala:24)
        at org.kframework.parser.concrete2kore.kernel.KSyntax2GrammarStatesFilte
r.processProductions(KSyntax2GrammarStatesFilter.java:142)
        at org.kframework.parser.concrete2kore.kernel.KSyntax2GrammarStatesFilte
r.lambda$getGrammar$92(KSyntax2GrammarStatesFilter.java:51)
        at java.util.HashMap.forEach(Unknown Source)
        at org.kframework.parser.concrete2kore.kernel.KSyntax2GrammarStatesFilte
r.getGrammar(KSyntax2GrammarStatesFilter.java:51)
        at org.kframework.parser.concrete2kore.ParseInModule.getGrammar(ParseInM
odule.java:93)
        at org.kframework.parser.concrete2kore.ParseInModule.parseStringTerm(Par
seInModule.java:127)
        at org.kframework.parser.concrete2kore.ParseInModule.parseString(ParseIn
Module.java:101)
        at org.kframework.parser.concrete2kore.ParseInModule.parseString(ParseIn
Module.java:87)
        at org.kframework.kompile.CompiledDefinition.lambda$getParser$a68fb235$1
(CompiledDefinition.java:161)
        at org.kframework.kast.KastFrontEnd.run(KastFrontEnd.java:105)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
        at org.kframework.main.Main.runApplication(Main.java:110)
        at org.kframework.main.Main.runApplication(Main.java:100)
        at org.kframework.main.Main.main(Main.java:52)
Caused by: java.lang.ClassNotFoundException: scala.reflect.runtime.package$
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 20 more
[Error] Internal: Uncaught exception thrown of type NoClassDefFoundError.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
```

OS: Windows 8.1 Pro, x64
K Framework version: 4.0.0
Java version: 

```
>java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

Kompiler version:

```
>kompile --version
K framework version 4.0.0
Git revision: d310c7a
Git branch: v4.0.0
Build date: Thu Jul 28 05:10:26 EEST 2016
```

**Comment by radumereuta** [comment]
Hi, I just tried this on `master`, revision: 1377911, and it works correctly. No ugly stack trace. I think it got fixed at one point.

On another note: you have to provide the start symbol for the programs, in the configuration:
`configuration <k> $PGM:Ids </k>`
If nothing is declared, all sorts are taken into consideration, except for list sorts, since a single element in the program is always ambiguous (single element, or the list with one element).

I tried this on win 10, x64. Let me know if the problem persists on your computer though.

**Comment by cos** [comment]
@Iaroslav-Mazur, do you still have this problem with the latest master?

**Comment by cos** [comment]
@radumereuta, shall we close this?

**Comment by andreiarusoaie** [comment]
I  know for sure that Iaroslav just switched to Linux and he doesn't have this problem anymore. If it's fixed on a newer version of K then you can probably close it.

**Comment by radumereuta** [comment]
I will take that as a yes.
