### ISSUE TITLE
ktest --- timeout does not work well, exceptions thrown

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#223]
```
fslwork$ pwd
/home/grosu/k/tutorial/1_k/1_lambda/lesson_8
fslwork$ ktest tests/config.xml --timeout 5000
Kompile the language definitions...(1 in total)
SUCCESS
Generate PDF files...(1 in total)
ERROR: [/home/grosu/k/bin/kompile --backend=pdf /home/grosu/k/tutorial/1_k/1_lambda/lesson_8/lambda.k] killed due to timeout.
FAIL
Kompiling definitions that are not yet kompiled.
Kompile the language definitions...(0 in total)
SUCCESS
Running /home/grosu/k/tutorial/1_k/1_lambda/lesson_8/lambda.k programs... (11 in total, 0 with input, 11 with output, 0 with error)
java.util.concurrent.ExecutionException: java.io.IOException: Stream closed
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:188)
    at org.kframework.ktest.Proc.run(Proc.java:147)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.IOException: Stream closed
    at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:272)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.Reader.read(Reader.java:140)
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1485)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1461)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1408)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1433)
    at org.apache.commons.io.IOUtils.toString(IOUtils.java:585)
    at org.apache.commons.io.IOUtils.toString(IOUtils.java:563)
    at org.kframework.ktest.StreamGobbler.call(Proc.java:295)
    at org.kframework.ktest.StreamGobbler.call(Proc.java:287)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    ... 3 more
java.util.concurrent.ExecutionException: java.io.IOException: Stream closed
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:188)
    at org.kframework.ktest.Proc.run(Proc.java:147)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.IOException: Stream closed
    at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:272)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.Reader.read(Reader.java:140)
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1485)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1461)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1408)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1433)
    at org.apache.commons.io.IOUtils.toString(IOUtils.java:585)
    at org.apache.commons.io.IOUtils.toString(IOUtils.java:563)
    at org.kframework.ktest.StreamGobbler.call(Proc.java:295)
    at org.kframework.ktest.StreamGobbler.call(Proc.java:287)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    ... 3 more
java.util.concurrent.ExecutionException: java.io.IOException: Stream closed
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:188)
    at org.kframework.ktest.Proc.run(Proc.java:147)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.IOException: Stream closed
    at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:272)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.Reader.read(Reader.java:140)
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1485)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1461)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1408)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1433)
    at org.apache.commons.io.IOUtils.toString(IOUtils.java:585)
    at org.apache.commons.io.IOUtils.toString(IOUtils.java:563)
    at org.kframework.ktest.StreamGobbler.call(Proc.java:295)
    at org.kframework.ktest.StreamGobbler.call(Proc.java:287)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    ... 3 more
java.util.concurrent.ExecutionException: java.io.IOException: Stream closed
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:188)
    at org.kframework.ktest.Proc.run(Proc.java:147)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.IOException: Stream closed
    at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:272)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.Reader.read(Reader.java:140)
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1485)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1461)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1408)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1433)
    at org.apache.commons.io.IOUtils.toString(IOUtils.java:585)
    at org.apache.commons.io.IOUtils.toString(IOUtils.java:563)
    at org.kframework.ktest.StreamGobbler.call(Proc.java:295)
    at org.kframework.ktest.StreamGobbler.call(Proc.java:287)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    ... 3 more
java.util.concurrent.ExecutionException: java.io.IOException: Stream closed
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:188)
    at org.kframework.ktest.Proc.run(Proc.java:147)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.IOException: Stream closed
    at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:272)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.Reader.read(Reader.java:140)
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1485)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1461)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1408)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1433)
    at org.apache.commons.io.IOUtils.toString(IOUtils.java:585)
    at org.apache.commons.io.IOUtils.toString(IOUtils.java:563)
    at org.kframework.ktest.StreamGobbler.call(Proc.java:295)
    at org.kframework.ktest.StreamGobbler.call(Proc.java:287)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    ... 3 more
java.util.concurrent.ExecutionException: java.io.IOException: Stream closed
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:188)
    at org.kframework.ktest.Proc.run(Proc.java:147)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.IOException: Stream closed
    at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:272)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.Reader.read(Reader.java:140)
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1485)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1461)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1408)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1433)
    at org.apache.commons.io.IOUtils.toString(IOUtils.java:585)
    at org.apache.commons.io.IOUtils.toString(IOUtils.java:563)
    at org.kframework.ktest.StreamGobbler.call(Proc.java:295)
    at org.kframework.ktest.StreamGobbler.call(Proc.java:287)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    ... 3 more
java.util.concurrent.ExecutionException: java.io.IOException: Stream closed
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:188)
    at org.kframework.ktest.Proc.run(Proc.java:147)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.IOException: Stream closed
    at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:272)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.Reader.read(Reader.java:140)
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1485)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1461)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1408)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1433)
    at org.apache.commons.io.IOUtils.toString(IOUtils.java:585)
    at org.apache.commons.io.IOUtils.toString(IOUtils.java:563)
    at org.kframework.ktest.StreamGobbler.call(Proc.java:295)
    at org.kframework.ktest.StreamGobbler.call(Proc.java:287)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    ... 3 more
java.util.concurrent.ExecutionException: java.io.IOException: Stream closed
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:188)
    at org.kframework.ktest.Proc.run(Proc.java:147)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.IOException: Stream closed
    at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:272)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.Reader.read(Reader.java:140)
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1485)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1461)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1408)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1433)
    at org.apache.commons.io.IOUtils.toString(IOUtils.java:585)
    at org.apache.commons.io.IOUtils.toString(IOUtils.java:563)
    at org.kframework.ktest.StreamGobbler.call(Proc.java:295)
    at org.kframework.ktest.StreamGobbler.call(Proc.java:287)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    ... 3 more
java.util.concurrent.ExecutionException: java.io.IOException: Stream closed
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:188)
    at org.kframework.ktest.Proc.run(Proc.java:147)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.IOException: Stream closed
    at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:272)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.Reader.read(Reader.java:140)
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1485)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1461)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1408)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1433)
    at org.apache.commons.io.IOUtils.toString(IOUtils.java:585)
    at org.apache.commons.io.IOUtils.toString(IOUtils.java:563)
    at org.kframework.ktest.StreamGobbler.call(Proc.java:295)
    at org.kframework.ktest.StreamGobbler.call(Proc.java:287)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    ... 3 more
java.util.concurrent.ExecutionException: java.io.IOException: Stream closed
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:188)
    at org.kframework.ktest.Proc.run(Proc.java:147)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.IOException: Stream closed
    at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:272)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.Reader.read(Reader.java:140)
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1485)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1461)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1408)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1433)
    at org.apache.commons.io.IOUtils.toString(IOUtils.java:585)
    at org.apache.commons.io.IOUtils.toString(IOUtils.java:563)
    at org.kframework.ktest.StreamGobbler.call(Proc.java:295)
    at org.kframework.ktest.StreamGobbler.call(Proc.java:287)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    ... 3 more
FAIL

FAIL (see details above)
----------------------------
Definitions kompiled: 1 (time: 0'4'' elapsed, 0'4'' CPU)
PDF posters kompiled: 1 (time: 0'7'' elapsed, 0'5'' CPU)
Programs krun: 11 (time: 0'5'' elapsed, 0'55'' CPU)
Total time: 0'16'' elapsed, 1'4'' CPU
----------------------------

fslwork$ 
```

**Comment by osa1** [comment]
Fixed a7e835dc358c90f8eca0becc4573d4626e31773b.
