### ISSUE TITLE
Parsing: regarding escape sequences

### ISSUE THREAD

**Issue by daejunpark** [kframework/k-legacy#226]
Parsing problem:

```
"\U"
```

An exception occurs when parsing the above term:

```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 11
    at java.lang.String.substring(String.java:1907)
    at org.kframework.utils.StringUtil.unescapeK(StringUtil.java:125)
    at org.kframework.kil.StringBuiltin.<init>(StringBuiltin.java:107)
    at org.kframework.kil.Token.kAppOf(Token.java:72)
    at org.kframework.kil.loader.JavaClassesFactory.getTerm(JavaClassesFactory.java:89)
    at org.kframework.kil.TermCons.<init>(TermCons.java:39)
    at org.kframework.kil.loader.JavaClassesFactory.getTerm(JavaClassesFactory.java:76)
    at org.kframework.kil.TermCons.<init>(TermCons.java:39)
    at org.kframework.kil.loader.JavaClassesFactory.getTerm(JavaClassesFactory.java:76)
    at org.kframework.kil.TermCons.<init>(TermCons.java:39)
    at org.kframework.kil.loader.JavaClassesFactory.getTerm(JavaClassesFactory.java:76)
    at org.kframework.parser.ProgramLoader.loadPgmAst(ProgramLoader.java:69)
    at org.kframework.parser.ProgramLoader.loadPgmAst(ProgramLoader.java:85)
    at org.kframework.parser.ProgramLoader.processPgm(ProgramLoader.java:124)
    at org.kframework.krun.RunProcess.runParser(RunProcess.java:120)
    at org.kframework.krun.RunProcess.runParserOrDie(RunProcess.java:96)
    at org.kframework.krun.Main.execute_Krun(Main.java:1253)
    at org.kframework.main.Main.main(Main.java:71)
```

**Comment by daejunpark** [comment]
Solved at some point.
