### ISSUE TITLE
Non-ascii character in comment later leads to krun crash

### ISSUE THREAD

**Issue by dfava** [kframework/k-legacy#2280]
Ran kompile on a simple definition which contained a non-ascii character on a comment.  The compilation succeeded, but a subsequent krun caused a crash.

(see https://lists.cs.illinois.edu/lists/arc/k-user/2017-02/msg00027.html)

The non-ascii character are the quotes surrounding the ! in the comment below.

$ cat simple.k
module SIMPLE-SYNTAX
    syntax Globals ::= List{Id,","}
    syntax Pgm ::= "nat" Globals
endmodule

module SIMPLE
imports SIMPLE-SYNTAX
configuration <T><k> $PGM:Pgm </k><H> .Map </H></T>

//Notice how generation of fresh Ints can be done by prepending "!” to the variable
rule <k> nat (Z:Id,Zs:Globals => Zs) </k>
     <H> HMap => HMap[Z <- SetItem(!N:Int)] </H>
     requires notBool(Z in keys(HMap)) // no repeated declaration
endmodule
$ kompile simple.k
$ cat test.simple
nat a, b, c
$ krun test.simple
Exception in thread "main" org.kframework.utils.errorsystem.KEMException: [Error] Critical: Failed to parse Kore file: /Users/dfava/Dropbox/favasynthesis/src/k/mmgo/set/./simple-kompiled/kore.txt
ERROR: Unexpected error while parsing: java.lang.IllegalArgumentException: Less than 4 hex digits in unicode value: '\u' due to end of CharSequence
	at org.kframework.utils.errorsystem.KEMException.create(KEMException.java:109)
	at org.kframework.utils.errorsystem.KEMException.criticalError(KEMException.java:30)
	at org.kframework.utils.inject.DefinitionLoadingModule.parseKore(DefinitionLoadingModule.java:62)
	at org.kframework.utils.inject.DefinitionLoadingModule.koreDefinition(DefinitionLoadingModule.java:82)
	at org.kframework.main.Main.runApplication(Main.java:228)
	at org.kframework.main.Main.main(Main.java:74)

**Comment by dfava** [comment]
[simple.k.txt](https://github.com/kframework/k/files/773103/simple.k.txt)
