### ISSUE TITLE
kompile --- error message needed

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#242]
```
fslwork$ cat t.k
module T
  syntax A ::= Token{"[ab]"}
endmodule
fslwork$ kompile t
GTerm: A1Const(amb([K1Var("K"{(1,25,1,26)}){(1,25,1,26)},Map1Var("K"{(1,25,1,26)}){(1,25,1,26)},MapItem1Var("K"{(1,25,1,26)}){(1,25,1,26)},Bag1Var("K"{(1,25,1,26)}){(1,25,1,26)},BagItem1Var("K"{(1,25,1,26)}){(1,25,1,26)},Set1Var("K"{(1,25,1,26)}){(1,25,1,26)},SetItem1Var("K"{(1,25,1,26)}){(1,25,1,26)},List1Var("K"{(1,25,1,26)}){(1,25,1,26)},ListItem1Var("K"{(1,25,1,26)}){(1,25,1,26)}]){(1,25,1,26)}){(1,25,1,26)}
GTerm: A1Const(K12Var("K"{(1,18,1,19)}){(1,18,1,21)}){(1,18,1,21)}
GTerm: A1Const(amb([K1Var("K"{(1,25,1,26)}){(1,25,1,26)},Map1Var("K"{(1,25,1,26)}){(1,25,1,26)},MapItem1Var("K"{(1,25,1,26)}){(1,25,1,26)},Bag1Var("K"{(1,25,1,26)}){(1,25,1,26)},BagItem1Var("K"{(1,25,1,26)}){(1,25,1,26)},Set1Var("K"{(1,25,1,26)}){(1,25,1,26)},SetItem1Var("K"{(1,25,1,26)}){(1,25,1,26)},List1Var("K"{(1,25,1,26)}){(1,25,1,26)},ListItem1Var("K"{(1,25,1,26)}){(1,25,1,26)}]){(1,25,1,26)}){(1,25,1,26)}
java.lang.AssertionError
    at org.kframework.kil.TermCons.<init>(TermCons.java:35)
    at org.kframework.kil.loader.JavaClassesFactory.getTerm(JavaClassesFactory.java:76)
    at org.kframework.kil.Collection.<init>(Collection.java:38)
    at org.kframework.kil.Ambiguity.<init>(Ambiguity.java:17)
    at org.kframework.kil.loader.JavaClassesFactory.getTerm(JavaClassesFactory.java:147)
    at org.kframework.kil.Rewrite.<init>(Rewrite.java:35)
    at org.kframework.kil.loader.JavaClassesFactory.getTerm(JavaClassesFactory.java:73)
    at org.kframework.kil.Collection.<init>(Collection.java:38)
    at org.kframework.kil.Ambiguity.<init>(Ambiguity.java:17)
    at org.kframework.kil.loader.JavaClassesFactory.getTerm(JavaClassesFactory.java:147)
    at org.kframework.kil.Sentence.<init>(Sentence.java:60)
    at org.kframework.kil.loader.JavaClassesFactory.getTerm(JavaClassesFactory.java:71)
    at org.kframework.parser.generator.ParseRulesFilter.transform(ParseRulesFilter.java:127)
    at org.kframework.kil.StringSentence.accept(StringSentence.java:42)
    at org.kframework.kil.visitors.BasicTransformer.transform(BasicTransformer.java:58)
    at org.kframework.parser.generator.ParseRulesFilter.transform(ParseRulesFilter.java:75)
    at org.kframework.kil.Module.accept(Module.java:102)
    at org.kframework.kil.visitors.BasicTransformer.transform(BasicTransformer.java:40)
    at org.kframework.kil.Definition.accept(Definition.java:112)
    at org.kframework.parser.DefinitionLoader.parseDefinition(DefinitionLoader.java:212)
    at org.kframework.parser.DefinitionLoader.loadDefinition(DefinitionLoader.java:78)
    at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:233)
    at org.kframework.kompile.KompileFrontEnd.kompile(KompileFrontEnd.java:212)
    at org.kframework.kompile.KompileFrontEnd.main(KompileFrontEnd.java:96)
    at org.kframework.main.Main.main(Main.java:45)
[Error] Critical: Cannot parse sentence: null
    File: /home/grosu/k/include/builtins/bool.k
    Location: (31,3,31,32)

fslwork$ 
```

**Comment by dwightguth** [comment]
Closing since this is specific to the SDF parser.
