### ISSUE TITLE
Nasty nontermination bug in Java Rewrite Engine

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#292]
dwightguth@rvwork-1:~/test$ cat test.k
module TEST

syntax K ::= test(K)

rule <k> test(K) ~> _ => K </k>

endmodule
dwightguth@rvwork-1:~/test$ cat 1.test
test(1)
dwightguth@rvwork-1:~/test$ kompile test.k --backend java
dwightguth@rvwork-1:~/test$ krun --backend java 1.test --depth 1
java.lang.RuntimeException: cannot translate term to Z3 format 'test(Int(#"1"))
    at org.kframework.backend.java.symbolic.KILtoZ3.transform(KILtoZ3.java:182)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:497)
    at org.kframework.backend.java.symbolic.SymbolicConstraint.checkUnsat(SymbolicConstraint.java:597)
    at org.kframework.backend.java.kil.ConstrainedTerm.unifyImpl(ConstrainedTerm.java:197)
    at org.kframework.backend.java.kil.ConstrainedTerm.unify(ConstrainedTerm.java:154)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.computeRewriteStep(SymbolicRewriter.java:282)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.rewrite(SymbolicRewriter.java:93)
    at org.kframework.backend.java.symbolic.JavaSymbolicKRun.javaKILRun(JavaSymbolicKRun.java:113)
    at org.kframework.backend.java.symbolic.JavaSymbolicKRun.internalRun(JavaSymbolicKRun.java:84)
    at org.kframework.backend.java.symbolic.JavaSymbolicKRun.step(JavaSymbolicKRun.java:396)
    at org.kframework.krun.Main.normalExecution(Main.java:363)
    at org.kframework.krun.Main.execute_Krun(Main.java:1404)
    at org.kframework.main.Main.main(Main.java:71)
[1, 40.30 ms]
<k>
    _4:K
</k>

I put --depth 1 because otherwise I get infinitely many of these stack traces because the program doesn't terminate. This used to work but at some point it broke and someone commented out the regression test that would have caught it. :/

I suggest Andrei or Yilong run git bisect on this example.

**Comment by yilongli** [comment]
Which regression test are you referring to?

**Comment by andreistefanescu** [comment]
Please add the test in issues (or point to an already existing test).

Andrei

**Comment by dwightguth** [comment]
You can use tests/regression/java-rewrite-engine/list/test1. It's commented out but uncomment it and you'll have an example, although it doesn't print the stack trace unless you turn back on SMT solving.
