### ISSUE TITLE
Windows 8 installation error

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#366]
After fixing the JAVA_HOME undocumented problem, I got another build error:

```
D:\github.grosu\k>ant
Buildfile: D:\github.grosu\k\build.xml

build:

concrete.signature:

concrete.signature.helper:

all.signature:

concrete.stratego2java:

concrete.stratego2java.helper:

all.stratego2java:

build-subprojects:

init:

build-project-java:
     [echo] KTool all: D:\github.grosu\k\src\javasources\KTool\build.xml

build:

jar:
   [delete] Deleting: D:\github.grosu\k\lib\java\k3.jar
      [jar] Building jar: D:\github.grosu\k\lib\java\k3.jar

alllocal:

makeversion:

BUILD FAILED
D:\github.grosu\k\build.xml:19: The following error occurred while executing thi
s line:
D:\github.grosu\k\build.xml:68: Execute failed: java.io.IOException: Cannot run
program "git": CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1041)
        at java.lang.Runtime.exec(Runtime.java:617)
        at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Jav
a13CommandLauncher.java:41)
        at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:428)
        at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:442)
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:628)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:495)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.jav
a:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(Single
CheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)

        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.jav
a:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExe
cutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find th
e file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:385)
        at java.lang.ProcessImpl.start(ProcessImpl.java:136)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1022)
        ... 36 more

Total time: 6 seconds
```

But at least now K built, so I can use it.  Nevertheless, the above should not happen.  It also happened a few days ago when Radu installed the K sources on my other Windows machine to show me something, and that time he said "don't worry about this".  Well, I do worry about everything like this, because it stains our image.  So please, Radu and others, do NOT let such errors pass, especially when you know about them.  These are the lowest-hanging fruits.  We just need to fix them, and the system is immediately much better.

**Comment by radumereuta** [comment]
This happened because you don't have git accessible through the command line.
I will update the readmes, and expand the Troubleshooting part with the JAVA_HOME and git errors.

You can still use K, because ant needs to access git in command line so it creates the version.txt with the git revision hash. That file is used only if you type kompile --version

**Comment by grosu** [comment]
But you should have a check if git is available, and if not to give a warning and put a generic message in the .text file.  Throwing an un caught exception is just plain bad.

Grigore

Sent from phone

-------- Original message --------
From: Radu Mereuta
Date:04/12/2014 11:46 (GMT-06:00)
To: kframework/k
Cc: "Rosu, Grigore"
Subject: Re: [k] Windows 8 installation error (#366)

This happened because you don't have git accessible through the command line.
I will update the readmes, and expand the Troubleshooting part with the JAVA_HOME and git errors.

You can still use K, because ant needs to access git in command line so it creates the version.txt with the git revision hash. That file is used only if you type kompile --version

**Comment by radumereuta** [comment]
I fixed this with @dwightguth a few weeks back.
