### ISSUE TITLE
Kast --parser binary NullPointerException

### ISSUE THREAD

**Issue by chathhorn** [kframework/k-legacy#369]
This must be a fairly recent regression (within the last two weeks or so) that breaks the C semantics:

test.k:

```
module TEST
   syntax K ::= "a"
   configuration <k> a </k>
endmodule
```

Now:

```
$ kompile test.k
$ krun --output binary --output-file conf.bin
$ file conf.bin
conf.bin: Java serialization data, version 5
$ kast --parser binary conf.bin
Exception in thread "main" java.lang.NullPointerException
        at org.kframework.compile.sharing.TokenSortCollector.visit(TokenSortCollector.java:63)
        at org.kframework.kil.Production.accept(Production.java:165)
        at org.kframework.kil.visitors.BasicVisitor.visit(BasicVisitor.java:181)
        at org.kframework.kil.PriorityBlock.accept(PriorityBlock.java:69)
        at org.kframework.kil.visitors.BasicVisitor.visit(BasicVisitor.java:151)
        at org.kframework.kil.Syntax.accept(Syntax.java:101)
        at org.kframework.kil.visitors.BasicVisitor.visit(BasicVisitor.java:77)
        at org.kframework.kil.Module.accept(Module.java:97)
        at org.kframework.kil.visitors.BasicVisitor.visit(BasicVisitor.java:53)
        at org.kframework.kil.Definition.accept(Definition.java:105)
        at org.kframework.compile.sharing.TokenSortCollector.collectTokenSorts(TokenSortCollector.java:50)
        at org.kframework.kil.Definition.preprocess(Definition.java:130)
        at org.kframework.kast.KastFrontEnd.kast(KastFrontEnd.java:157)
        at org.kframework.main.Main.main(Main.java:58)
```

I seem to get this same exception no matter what file I pass to "kast --parser binary", including random binaries and the empty file.

**Comment by chathhorn** [comment]
This regression was introduced at revision ff5f0347d4c211df0ed0e7961d6560399ae72f65 (@dwightguth?). I suspect the fix would be pretty easy.

**Comment by dwightguth** [comment]
Sorry about that... if you want to get a head start on whatever you're working on I suggest you check out dwightguth/k@9a641b6. It will be merged into master as soon as it's through code review.

**Comment by chathhorn** [comment]
Thanks, I really appreciate it!

**Comment by dwightguth** [comment]
It is merged now. Please verify and close if you're happy.
