### ISSUE TITLE
context transformation are too restrictive after the last modifications

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#40]
The following definitions works fine:

module CTXABS

   configuration <T>
          <k color="green"> $PGM:K </k>
          <arch>
            <functions> .Map </functions>
            <ip-group-info color="cyan" multiplicity="*">
              <ip-gr-name color="yellow"> "" </ip-gr-name>
              <operation color="orange" multiplicity="*">
                <op-name> "" </op-name>
                <in-arity> 0 </in-arity>
                <out-arity> 0 </out-arity>
              </operation>
              <geometry> .List </geometry>
            </ip-group-info>
          </arch>
          <state>
            <stack color="blue"> .List </stack>
            <ip-group multplicity="*" color="red">
              <ip-name> "" </ip-name>
              <ip-k> .K </ip-k>
              <ip-state> .Bag
              </ip-state>
            </ip-group>
            <out stream="stdout"> .List </out>
          </state>
        </T>

  rule <k> I:Int => . ...</k>
       <state> 
         <stack>... (. => ListItem(I)) </stack>
       ...</state>

endmodule

Bu if we replace the configuration with the following one

  configuration <T>
          <models>
            <functions> .Map </functions>
            <ip-group-info color="cyan" multiplicity="*">
              <ip-gr-name color="yellow"> "" </ip-gr-name>
              <operation color="orange" multiplicity="*">
                <op-name> "" </op-name>
                <in-arity> 0 </in-arity>
                <out-arity> 0 </out-arity>
              </operation>
              <geometry> .List </geometry>
            </ip-group-info>
          </models>
                  <homadecores>
                    <homadecore multiplicity="*">
                      <k color="green"> $PGM:K </k>
              <stack color="blue"> .List </stack>
                    </homadecore>
                  </homadecores>
          <state>
            <ip-group multplicity="*" color="red">
              <ip-name> "" </ip-name>
              <ip-k> .K </ip-k>
              <ip-state> .Bag
              </ip-state>
            </ip-group>
            <out stream="stdout"> .List </out>
          </state>
        </T>

the we get the following error:

Exception in thread "main" java.lang.AssertionError
    at org.kframework.compile.transformers.ResolveContextAbstraction.transform(ResolveContextAbstraction.java:139)
    at org.kframework.kil.Cell.accept(Cell.java:266)
    at org.kframework.kil.visitors.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:365)
    at org.kframework.kil.visitors.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:390)
    at org.kframework.kil.Bag.accept(Bag.java:55)
    at org.kframework.kil.visitors.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:112)
    at org.kframework.kil.visitors.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:171)
    at org.kframework.compile.transformers.ResolveContextAbstraction.transform(ResolveContextAbstraction.java:59)
    at org.kframework.kil.Rule.accept(Rule.java:72)
    at org.kframework.kil.visitors.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:75)
    at org.kframework.compile.transformers.ResolveContextAbstraction.transform(ResolveContextAbstraction.java:35)
    at org.kframework.kil.Module.accept(Module.java:102)
    at org.kframework.kil.visitors.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:42)
    at org.kframework.kil.Definition.accept(Definition.java:121)
    at org.kframework.compile.utils.CompilerTransformerStep.compile(CompilerTransformerStep.java:24)
    at org.kframework.compile.utils.CompilerSteps.compile(CompilerSteps.java:37)
    at org.kframework.compile.ResolveConfigurationAbstraction.compile(ResolveConfigurationAbstraction.java:28)
    at org.kframework.compile.ResolveConfigurationAbstraction.compile(ResolveConfigurationAbstraction.java:18)
    at org.kframework.compile.utils.CompilerSteps.compile(CompilerSteps.java:37)
    at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:294)
    at org.kframework.kompile.KompileFrontEnd.kompile(KompileFrontEnd.java:250)
    at org.kframework.main.Main.main(Main.java:69)

Note that this example worked  some time ago (in July) and I presented it as a strong feature of K.

**Comment by dlucanu** [comment]
It was my mistake. I close it.
