### ISSUE TITLE
krun.bat --version throws an exception

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/k-legacy#403]
$ krun.bat --version
K-framework nightly build.
Git Revision: 675b44e
Build date: Sun Apr 27 11:38:11 CDT 2014

Exception in thread "Thread-0" java.lang.NullPointerException
        at java.io.File.<init>(File.java:277)
        at org.kframework.krun.Main$2.run(Main.java:954)

OS: Windows 7

**Comment by dwightguth** [comment]
Closing duplicate of #407.
