### ISSUE TITLE
Exception in main: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by chathhorn** [kframework/k-legacy#472]
C semantics doesn't kompile with the latest K. Here's the stack trace:

Basic Parsing                                                =   713
Preprocess                                                   =   206
Checks                                                       =    13
File Gen Pgm                                                 =   249
Generate TBLPgm                                              =  1610
File Gen Def                                                 =  2559
Generate TBLDef                                              = 98673
Importing Files                                              =  2648
Parsing Configs                                              =  2052
Parsing Rules                                                = 37206
Exception in thread "main" java.lang.NoSuchMethodError: org.kframework.compile.utils.CheckVisitorStep.<init>(Lorg/kframework/kil/visitors/Visi
tor;Lorg/kframework/kil/loader/Context;)V
        at org.kframework.backend.BasicBackend.getCompilationSteps(BasicBackend.java:56)
        at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:186)
        at org.kframework.kompile.KompileFrontEnd.kompile(KompileFrontEnd.java:161)
        at org.kframework.kompile.KompileFrontEnd.main(KompileFrontEnd.java:72)
        at org.kframework.main.Main.main(Main.java:49)

Let me know if there's more information I should provide.

**Comment by chathhorn** [comment]
Here's the command line:
kompile c11-translation.k -d "c11-translation-kompiled" -w all -v

**Comment by traiansf** [comment]
hm.  have you done an `ant clean build` ?  When I get that error it usually
indicates the codebase hasn't been properly cleaned.

2014-05-19 22:11 GMT+03:00 Chris Hathhorn notifications@github.com:

**Comment by chathhorn** [comment]
You're right. Thanks!
