### ISSUE TITLE
kompile throws exceptions when a context declaration includes cells

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#479]
The following example is inspired from a discussion with an external user.

The kompilation of the following definition

```
module TEST
  syntax Values ::= Int 

  syntax KResult ::= Values

  syntax Expr ::= "defer-effect" "(" Comm "," Expr ")"
                | Values

  syntax Comm ::= "print" "(" Expr ")" [strict]

  configuration 
    <k> $PGM:K </k> 
    <effects> .List </effects>

  context <k> defer-effect(_, HOLE) ...</k>
          <effects> .List </effects>

endmodule
```

producess the following error:

```
$ kompile test.k
Exception in thread "main" java.lang.NullPointerException
    at org.kframework.compile.utils.MetaK.isComputationSort(MetaK.java:375)
    at org.kframework.compile.transformers.AddKCell.visit(AddKCell.java:56)
    at org.kframework.compile.transformers.AddKCell.visit(AddKCell.java:14)
    at org.kframework.kil.Rule.accept(Rule.java:72)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
    at org.kframework.kil.AbstractVisitor.genericVisitList(AbstractVisitor.java:135)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:300)
    at org.kframework.compile.transformers.AddKCell.visit(AddKCell.java:39)
    at org.kframework.compile.transformers.AddKCell.visit(AddKCell.java:14)
    at org.kframework.kil.Module.accept(Module.java:96)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
    at org.kframework.kil.AbstractVisitor.genericVisitList(AbstractVisitor.java:135)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:284)
    at org.kframework.kil.Definition.accept(Definition.java:183)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.compile.utils.CompilerTransformerStep.compile(CompilerTransformerStep.java:24)
    at org.kframework.compile.utils.CompilerSteps.compile(CompilerSteps.java:44)
    at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:192)
    at org.kframework.kompile.KompileFrontEnd.kompile(KompileFrontEnd.java:161)
    at org.kframework.kompile.KompileFrontEnd.main(KompileFrontEnd.java:72)
    at org.kframework.main.Main.main(Main.java:49)
```

The source of the exception is the context declaration. If such declarations are not supported, then the tool should give an appropriate error message.

**Comment by dwightguth** [comment]
Should probably only be fixed in the new compilation pipeline.
