### ISSUE TITLE
ktest throws exception for wrong typed option

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#485]
```
$ ktest config.xml --update out
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --update
    at org.apache.commons.cli.Parser.processOption(Parser.java:363)
    at org.apache.commons.cli.Parser.parse(Parser.java:199)
    at org.apache.commons.cli.Parser.parse(Parser.java:85)
    at org.kframework.ktest.CmdArgs.CmdArgParser.<init>(CmdArgParser.java:81)
    at org.kframework.ktest.KTest.<init>(KTest.java:36)
    at org.kframework.ktest.KTest.main(KTest.java:107)
    at org.kframework.main.Main.main(Main.java:58)
Exception in thread "main" java.lang.NullPointerException
    at org.kframework.ktest.KTest.main(KTest.java:112)
    at org.kframework.main.Main.main(Main.java:58)
```

**Comment by osa1** [comment]
We had already discussed this in #407 . I'll fix this shortly.
