### ISSUE TITLE
generate-tests is broken

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#500]
```
dwightguth@rvwork-1:~/k/tutorial/1_k/2_imp/lesson_5$ kompile imp.k --backend java
dwightguth@rvwork-1:~/k/tutorial/1_k/2_imp/lesson_5$ krun ../lesson_1/tests/collatz.imp --generate-tests --search-all --pattern "<k> .K </k>"
Exception in thread "main" java.lang.ClassCastException: org.kframework.kil.Cell cannot be cast to org.kframework.kil.Bag
    at org.kframework.backend.java.symbolic.JavaSymbolicKRun.generate(JavaSymbolicKRun.java:316)
    at org.kframework.krun.KRunFrontEnd.normalExecution(KRunFrontEnd.java:118)
    at org.kframework.krun.KRunFrontEnd.execute_Krun(KRunFrontEnd.java:515)
    at org.kframework.main.Main.main(Main.java:71)
```

I haven't tried it in master, but this is what I get in unified builtins.

**Comment by yilongli** [comment]
I haven't worked on test generation since the winter break. Even at that time, it only worked for a special version of IMP I created. I plan to get back to that during the summer, but I don't think this issue is really necessary. Still a long way to go before this can be officially part of the framework.

**Comment by dwightguth** [comment]
Closing. This feature has been removed for the time being and will likely be re-added as a K module.
