### ISSUE TITLE
Java backend cannot deal with some simple function syntax

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#513]
When I test this set of rules:

module C-FUNCTION-DEF
 syntax K ::= initFunction(K, K) [strict]
 syntax Type ::= compositeType(Type, Type) [function]
 syntax Bool ::= isAggregateType(Type) [function]
endmodule

I got error as:
Exception in thread "main" java.lang.ClassCastException: org.kframework.backend.java.kil.KItemProjection cannot be cast to org.kframework.backend.java.kil.KItem
    at org.kframework.backend.java.indexing.IndexingPair.getIndex(IndexingPair.java:25)
    at org.kframework.backend.java.indexing.IndexingPair.getIndexingPair(IndexingPair.java:58)
    at org.kframework.backend.java.kil.Term$1.visit(Term.java:66)
    at org.kframework.backend.java.kil.Cell.accept(Cell.java:116)
    at org.kframework.backend.java.symbolic.BottomUpVisitor.visit(BottomUpVisitor.java:68)
    at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:165)
    at org.kframework.backend.java.symbolic.BottomUpVisitor.visit(BottomUpVisitor.java:61)
    at org.kframework.backend.java.kil.Term$1.visit(Term.java:68)
    at org.kframework.backend.java.kil.Cell.accept(Cell.java:116)
    at org.kframework.backend.java.kil.Term.getIndexingPairs(Term.java:62)
    at org.kframework.backend.java.kil.Rule.<init>(Rule.java:76)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:636)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:74)
    at org.kframework.kil.Rule.accept(Rule.java:72)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:683)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:74)
    at org.kframework.kil.Definition.accept(Definition.java:185)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transformDefinition(KILtoBackendJavaKILTransformer.java:101)
    at org.kframework.backend.java.symbolic.JavaSymbolicBackend.lastStep(JavaSymbolicBackend.java:65)
    at org.kframework.main.LastStep.compile(LastStep.java:22)
    at org.kframework.main.LastStep.compile(LastStep.java:11)
    at org.kframework.compile.utils.CompilerSteps.compile(CompilerSteps.java:44)
    at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:192)
    at org.kframework.kompile.KompileFrontEnd.kompile(KompileFrontEnd.java:161)
    at org.kframework.kompile.KompileFrontEnd.main(KompileFrontEnd.java:72)
    at org.kframework.main.Main.main(Main.java:49)

**Comment by yilongli** [comment]
```
module C-FUNCTION-DEF
  syntax K ::= initFunction(K, K) [strict]
  syntax Type ::= compositeType(Type, Type) [function]
  syntax Bool ::= isAggregateType(Type) [function]
endmodule
```

This problem can be solved by writing `syntax KItem ::= initFunction(K, K) [strict]` instead.

@andreistefanescu BTW, what should be the right error message for production like `syntax K ::= initFunction(K, K) [strict]`?

**Comment by andreistefanescu** [comment]
While that fixed the kompile error, the problem is that [strict] and
[function] should be mutually exclusive, and krun is going to throw an
assertion failure. We should probably have a static check for this. There
should be another static check for productions into K or KList (which are
not allowed to be extended by users).

Andrei

**Comment by grosu** [comment]
But how does K know that initFunction is a function when the only attribute it has is `[strict]`?

**Comment by andreistefanescu** [comment]
Hmm, I misread it. Then it should just give an error message because users
should not be allowed to declare new K constructors.

Andrei

**Comment by liyili2** [comment]
Oh, you mean that we will not have "syntax K ::=" anymore, instead, we will have "syntax KItem ::=", right?

**Comment by andreistefanescu** [comment]
Yes.

Andrei
