### ISSUE TITLE
Strange behavior in transfering KLabel to KItem in Java Backend

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#556]
I found that a strange behavior in java backend where this set of rules is allowed:

```
module TEST
     syntax KItem ::= lab(KLabel) | labs(KLabel,KLabel)
     syntax Bool ::= labelInSet(KLabel,KItem,Set) [function]

     rule labelInSet(A:KLabel,lab(A':KLabel),.Set) => false
       when A =/=KLabel A'

     rule labelInSet(A:KLabel,lab(A:KLabel),.Set) => true

endmodule
```

However, when I turn this by deleting the labs(KLabel,KLabel), then the output will become:

```
module TEST
     syntax KItem ::= lab(KLabel)
     syntax Bool ::= labelInSet(KLabel,KItem,Set) [function]

     rule labelInSet(A:KLabel,lab(A':KLabel),.Set) => false
       when A =/=KLabel A'

     rule labelInSet(A:KLabel,lab(A:KLabel),.Set) => true

endmodule
```

The output will be:

```
Exception in thread "main" java.lang.AssertionError
    at org.kframework.utils.Poset.getMaximalLowerBounds(Poset.java:155)
    at org.kframework.kil.loader.Context.getCommonSubsorts(Context.java:283)
    at org.kframework.backend.java.kil.KItem.<init>(KItem.java:141)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:166)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:76)
    at org.kframework.kil.KApp.accept(KApp.java:175)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:256)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:76)
    at org.kframework.kil.KList.accept(KList.java:52)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:161)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:76)
    at org.kframework.kil.KApp.accept(KApp.java:175)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:568)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:76)
    at org.kframework.kil.Rule.accept(Rule.java:72)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:691)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:76)
    at org.kframework.kil.Definition.accept(Definition.java:185)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transformDefinition(KILtoBackendJavaKILTransformer.java:103)
    at org.kframework.backend.java.symbolic.JavaSymbolicBackend.lastStep(JavaSymbolicBackend.java:65)
    at org.kframework.main.LastStep.compile(LastStep.java:22)
    at org.kframework.main.LastStep.compile(LastStep.java:11)
    at org.kframework.compile.utils.CompilerSteps.compile(CompilerSteps.java:44)
    at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:192)
    at org.kframework.kompile.KompileFrontEnd.kompile(KompileFrontEnd.java:161)
    at org.kframework.kompile.KompileFrontEnd.main(KompileFrontEnd.java:72)
    at org.kframework.main.Main.main(Main.java:49)

```

**Comment by yilongli** [comment]
Same as https://github.com/kframework/k/issues/558.
