### ISSUE TITLE
BuiltinFunction InvocationTargetException.

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#561]
Hi, I find that if I test the java backend by the following set of rules, I will get something like invocation exception without throw out the error:

```
module TEST

    syntax Type ::= "Int" | "Double" | "Unsigned"
    syntax KItem ::= abc(K) | "yes" | "no"

    rule abc(K:K) => yes
      when K in (SetItem(Int))

    rule abc(K:K) => no
      when K in (SetItem(Double) SetItem(Unsigned))


endmodule
```

I detected this by inserting a output lanes in the "try catch" block in the evaluateFunction in KItem of Java backend.

This might be a potential problem. When I tested the C semantics, some exception will be thrown out like:

```
Ignored exception thrown by hook '_in_ : 
java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.kframework.backend.java.symbolic.BuiltinFunction.invoke(BuiltinFunction.java:152)
    at org.kframework.backend.java.kil.KItem.evaluateFunction(KItem.java:269)
    at org.kframework.backend.java.symbolic.LocalEvaluator.transform(LocalEvaluator.java:36)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:488)
    at org.kframework.backend.java.symbolic.CombinedLocalTransformer.transformAll(CombinedLocalTransformer.java:48)
    at org.kframework.backend.java.symbolic.CombinedLocalTransformer.transform(CombinedLocalTransformer.java:128)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:488)
    at org.kframework.backend.java.symbolic.PrePostTransformer.transform(PrePostTransformer.java:149)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:488)
    at org.kframework.backend.java.symbolic.Evaluator.evaluate(Evaluator.java:26)
    at org.kframework.backend.java.kil.Term.evaluate(Term.java:133)
    at org.kframework.backend.java.kil.Term.evaluate(Term.java:110)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.evaluateRule(KILtoBackendJavaKILTransformer.java:778)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.evaluateDefinition(KILtoBackendJavaKILTransformer.java:743)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transformDefinition(KILtoBackendJavaKILTransformer.java:109)
    at org.kframework.backend.java.symbolic.JavaSymbolicBackend.lastStep(JavaSymbolicBackend.java:65)
    at org.kframework.main.LastStep.compile(LastStep.java:22)
    at org.kframework.main.LastStep.compile(LastStep.java:11)
    at org.kframework.compile.utils.CompilerSteps.compile(CompilerSteps.java:44)
    at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:192)
    at org.kframework.kompile.KompileFrontEnd.kompile(KompileFrontEnd.java:161)
    at org.kframework.kompile.KompileFrontEnd.main(KompileFrontEnd.java:72)
    at org.kframework.main.Main.main(Main.java:49)
Caused by: java.lang.IllegalArgumentException: first argument 'l((# _7950:KLabel)(.KList)) is not ground
    at org.kframework.backend.java.builtins.BuiltinSetOperations.in(BuiltinSetOperations.java:51)

```

OR

```
Caused by: java.lang.IllegalArgumentException: first argument 'l((# _7950:KLabel)(.KList)) is not ground
    at org.kframework.backend.java.builtins.BuiltinSetOperations.in(BuiltinSetOperations.java:51)

```

However, when I tested the individual piece of these set of rules from c semantics, this error will not be shown any more. I feel there is something very strange here. Maybe the 
invocation error only happens when you have a large amount set of rules.

**Comment by dwightguth** [comment]
This is more or less ordinary behavior if a hook throws an exception. The hook you reference should not have thrown this exception when it could have returned null though. I fixed that in #637.

Resolving.
