### ISSUE TITLE
the branch unified-builtins2 crashes when compiled with --backend symbolic

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#618]
I tried to kompile the branch unified-buitins2 with the symbolic backend and I got the following error:

$ kompile cink.k --backend symbolic
Exception in thread "main" java.lang.NullPointerException
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.compile.transformers.ResolveBlockingInput.getSort(ResolveBlockingInput.java:264)
    at org.kframework.compile.transformers.ResolveBlockingInput.visit(ResolveBlockingInput.java:199)
    at org.kframework.compile.transformers.ResolveBlockingInput.visit(ResolveBlockingInput.java:34)
    at org.kframework.kil.Cell.accept(Cell.java:287)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
    at org.kframework.kil.AbstractVisitor.genericVisitList(AbstractVisitor.java:135)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:427)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:438)
    at org.kframework.kil.Bag.accept(Bag.java:69)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
    at org.kframework.kil.AbstractVisitor.genericVisitChild(AbstractVisitor.java:113)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:421)
    at org.kframework.compile.transformers.ResolveBlockingInput.visit(ResolveBlockingInput.java:131)
    at org.kframework.compile.transformers.ResolveBlockingInput.visit(ResolveBlockingInput.java:34)
    at org.kframework.kil.Cell.accept(Cell.java:287)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
    at org.kframework.kil.AbstractVisitor.genericVisitChild(AbstractVisitor.java:113)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:326)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:344)
    at org.kframework.compile.transformers.ResolveBlockingInput.visit(ResolveBlockingInput.java:118)
    at org.kframework.compile.transformers.ResolveBlockingInput.visit(ResolveBlockingInput.java:34)
    at org.kframework.kil.Rule.accept(Rule.java:72)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
    at org.kframework.kil.AbstractVisitor.genericVisitList(AbstractVisitor.java:135)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:300)
    at org.kframework.compile.transformers.ResolveBlockingInput.visit(ResolveBlockingInput.java:82)
    at org.kframework.compile.transformers.ResolveBlockingInput.visit(ResolveBlockingInput.java:34)
    at org.kframework.kil.Module.accept(Module.java:96)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
    at org.kframework.kil.AbstractVisitor.genericVisitList(AbstractVisitor.java:135)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:284)
    at org.kframework.compile.transformers.ResolveBlockingInput.visit(ResolveBlockingInput.java:77)
    at org.kframework.compile.transformers.ResolveBlockingInput.visit(ResolveBlockingInput.java:34)
    at org.kframework.kil.Definition.accept(Definition.java:185)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.compile.utils.CompilerTransformerStep.compile(CompilerTransformerStep.java:24)
    at org.kframework.compile.utils.CompilerSteps.compile(CompilerSteps.java:44)
    at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:192)
    at org.kframework.kompile.KompileFrontEnd.kompile(KompileFrontEnd.java:161)
    at org.kframework.kompile.KompileFrontEnd.main(KompileFrontEnd.java:72)
    at org.kframework.main.Main.main(Main.java:49)

**Comment by andreiarusoaie** [comment]
It seems that there is a general problem with configuration variables. If you go in imp++/lesson_7/imp.k and put a variable in the configuration, say $IN:List in the <in> </in> cell, then you'll get the same exception.

Here is exactly what I did:

andrei~/work/k$ git pull
Already up-to-date.
andrei~/work/k$ git status
On branch unified-builtins2
Your branch is up-to-date with 'origin/unified-builtins2'.

nothing to commit, working directory clean
andrei~/work/k$ ant
Buildfile: /Users/andrei/work/k/build.xml

build:

concrete.signature:

concrete.signature.helper:

all.signature:

concrete.stratego2java:

concrete.stratego2java.helper:

all.stratego2java:

build-subprojects:

init:

build-project-java:
     [echo] KTool all: /Users/andrei/work/k/src/javasources/KTool/build.xml

build:

jar:
   [delete] Deleting: /Users/andrei/work/k/lib/java/k3.jar
      [jar] Building jar: /Users/andrei/work/k/lib/java/k3.jar

alllocal:

makeversion:
     [echo] ./lib/version.txt
     [echo] K-framework nightly build.
     [echo] Git Revision: 52f6c76
     [echo] Build date: Tue Jun 17 10:22:14 EEST 2014

BUILD SUCCESSFUL
Total time: 3 seconds
andrei~/work/k$ java -version
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)
andrei~/work/k$ cd tutorial/1_k/4_imp++/lesson_7/
andrei~/work/k/tutorial/1_k/4_imp++/lesson_7$ emacs -nw imp.k 

// here, I changed line 46:
<in color="magenta" stream="stdin"> .List </in>
// with
<in color="magenta" stream="stdin"> $IN:List </in>

andrei~/work/k/tutorial/1_k/4_imp++/lesson_7$ kompile imp.k 
Exception in thread "main" java.lang.AssertionError: left terms no longer allowed here
    at org.kframework.kil.ListBuiltin.of(ListBuiltin.java:70)
    at org.kframework.kil.DataStructureBuiltin.of(DataStructureBuiltin.java:175)
    at org.kframework.compile.utils.CompileDataStructures.visit(CompileDataStructures.java:145)
    at org.kframework.compile.utils.CompileDataStructures.visit(CompileDataStructures.java:38)
    at org.kframework.kil.KApp.accept(KApp.java:180)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
    at org.kframework.kil.AbstractVisitor.genericVisitChild(AbstractVisitor.java:113)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:421)
    at org.kframework.kil.Cell.accept(Cell.java:287)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
    at org.kframework.kil.AbstractVisitor.genericVisitList(AbstractVisitor.java:135)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:427)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:438)
    at org.kframework.kil.Bag.accept(Bag.java:69)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
    at org.kframework.kil.AbstractVisitor.genericVisitChild(AbstractVisitor.java:113)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:421)
    at org.kframework.kil.Cell.accept(Cell.java:287)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
    at org.kframework.kil.AbstractVisitor.genericVisitChild(AbstractVisitor.java:113)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:421)
    at org.kframework.kil.Cell.accept(Cell.java:287)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
    at org.kframework.kil.AbstractVisitor.genericVisitChild(AbstractVisitor.java:113)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:326)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:334)
    at org.kframework.kil.Configuration.accept(Configuration.java:39)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
    at org.kframework.kil.AbstractVisitor.genericVisitList(AbstractVisitor.java:135)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:300)
    at org.kframework.kil.Module.accept(Module.java:96)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
    at org.kframework.kil.AbstractVisitor.genericVisitList(AbstractVisitor.java:135)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:284)
    at org.kframework.kil.Definition.accept(Definition.java:185)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.compile.utils.CompilerTransformerStep.compile(CompilerTransformerStep.java:24)
    at org.kframework.compile.utils.CompilerSteps.compile(CompilerSteps.java:44)
    at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:192)
    at org.kframework.kompile.KompileFrontEnd.kompile(KompileFrontEnd.java:161)
    at org.kframework.kompile.KompileFrontEnd.main(KompileFrontEnd.java:72)
    at org.kframework.main.Main.main(Main.java:49)
andrei~/work/k/tutorial/1_k/4_imp++/lesson_7$

**Comment by grosu** [comment]
Is this the same error, or they are different?  Regardless, this needs to be fixed asap.  Who can best fix this asap?  Traian, Andrei, Yilong?

**Comment by dlucanu** [comment]
Perhaps yes, but it is hard to deduce that from messages. My definition can be found in the branch "unified-builtins" in cink-semantics repository (it is enough  to test the definition from the subfolder "basic").

**Comment by dwightguth** [comment]
This is the symbolic backend that you work on in Romania. We informed you
before that it was broken. We do not at this time have the resources to
work on this code path when it is not part of our vision of the tool. You
will need to debug this on your own with your own developer resources.

**Comment by dwightguth** [comment]
Sorry, I misread this issue. You filed two separate bugs with the same issue number, please do not do that again. You should create a minimal example and then create a new issue, and I will assign it.

**Comment by grosu** [comment]
I agree, in what regards the first report, Dorel's.  But Andrei's is a real bug, I think, regarding variables in the initial configuration.

**Comment by dwightguth** [comment]
Yes, I noticed. they should create a new issue and provide a minimal
example.

**Comment by andreiarusoaie** [comment]
I'll create an issue as soon as I have access to a computer. 

I tend to believe that the bug is the same, even though the exceptions are different. 

Regarding my symbolic backend, I'll take care of it, so you should not worry about it.
