### ISSUE TITLE
krun backendTerm cannot turn into term

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#623]
The program is:
ctype.c11-translation

```
'TranslationUnit("/home/qangel/project/c-semantics/libc/src/ctype.c",, 1 ,, 0)
```

The command to run it is:

```
krun --output="binary" -cOPTIONS="(SetItem(NOLINK) .Set)" -cOBJ1=".Bag" -cOBJ2=".Bag" --parser="cat" -d c11-translation-kompiled ctype.c11-translation
```

**Comment by liyili2** [comment]
Actually, it is stuck on importing the configuration of translation. The final output is like:

```
loadMergeObj(# .Bag(.KList), # .Bag(.KList)) ~> 'TranslationUnit(...)
```

However, the term which the krun suggests to be a backendTerm is the 'TranslationUnit(...)

**Comment by liyili2** [comment]
The kcc command is:

```
dist/kcc -s -d libc/src/ctype.c
```

**Comment by liyili2** [comment]
I am able to produce the smallest set of what happen for this bug:

If I input the following test cases:

```
module TEST

     configuration <k> loadMergeObj($OBJ1:Bag, $OBJ2:Bag) ~>  $PGM:K  </k>
           <bag> <b multiplicity="*"> 0 </b> </bag><options> $OPTIONS:Set </options>

     syntax TranslationUnit ::= TranslationUnit(String, K, K)
          [klabel('TranslationUnit)]
     syntax KItem ::= loadMergeObj(Bag , Bag) [function]

     rule TranslationUnit(S:String, K1:K, K2:K) => .

     rule loadMergeObj(.Bag , .Bag) => .

endmodule
```

with the following program:

```
TranslationUnit("a", 0, 1)
```

If I input the following command:

```
krun -cOPTIONS="(SetItem(NOLINK) .Set)" -cOBJ1=".Bag" -cOBJ2=".Bag" program1.test
```

The krun will runs fine.

However, if I input the following command:

```
krun -cOPTIONS="(SetItem(NOLINK) .Set)" -cOBJ1=".Bag" -cOBJ2=".Bag" --parser="cat" program1.test
```

The krun will have the following output:

```
Exception in thread "main" java.lang.ClassCastException: org.kframework.kil.BackendTerm cannot be cast to org.kframework.backend.java.kil.Term
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:240)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:78)
    at org.kframework.kil.KSequence.accept(KSequence.java:46)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:279)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:78)
    at org.kframework.kil.Cell.accept(Cell.java:287)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:326)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:78)
    at org.kframework.kil.Bag.accept(Bag.java:69)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:269)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:78)
    at org.kframework.kil.Cell.accept(Cell.java:287)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transformTerm(KILtoBackendJavaKILTransformer.java:134)
    at org.kframework.backend.java.kil.Term.of(Term.java:50)
    at org.kframework.backend.java.symbolic.JavaSymbolicKRun.javaKILRun(JavaSymbolicKRun.java:96)
    at org.kframework.backend.java.symbolic.JavaSymbolicKRun.internalRun(JavaSymbolicKRun.java:81)
    at org.kframework.backend.java.symbolic.JavaSymbolicKRun.run(JavaSymbolicKRun.java:76)
    at org.kframework.krun.Main.normalExecution(Main.java:372)
    at org.kframework.krun.Main.execute_Krun(Main.java:1454)
    at org.kframework.main.Main.main(Main.java:64)
```

@chathhorn  and @andreistefanescu , I wonder what is the use of the parser option "cat" here. Why c semantics needs this option and why does it not work.

**Comment by dwightguth** [comment]
The problem is in krun. To fix this requires the kast parser. I should be
able to figure out how to fix it, if you provide me an exhaustive grammar
of what all kast syntax kcc is able to output.

**Comment by yilongli** [comment]
Thank you, Dwight. This issue seems to be something out of my control.

**Comment by liyili2** [comment]
Do you want me to write out the javacc kast parser, Or do you want me to write out the grammar for c semantics only. Since we are going to have the javacc kast parser, what is the reason to produce the grammar of c semantics only?

@radumereuta, I wonder why we cannot just parse the program by the concrete parser since all kast formats can be parsed by concrete parser.

**Comment by dwightguth** [comment]
It's worth a try... Have you tried it with `--parser "kast --parser
ground"`?

**Comment by chathhorn** [comment]
FWIW, the input in this case is generated by this xml-to-k script:

https://github.com/kframework/c-semantics/blob/java_rewrite_engine/scripts/xml-to-k

**Comment by dwightguth** [comment]
Okay well I don't know perl very well but I think this script will need to
be changed into something which outputs something parseable as kast before I
can address this issue. This is something that Liyi will have to do.

**Comment by liyili2** [comment]
The command --parser "kast --parser ground" works.

Do you know what is the difference between parser=cat and kast --parser ground?

**Comment by grosu** [comment]
As soon as you find it out, please also add an item in the manual.

Thanks,
Grigore

**Comment by liyili2** [comment]
It does not work for the whole file. There must some difference between commands kast --parser ground and --parset=cat

**Comment by radumereuta** [comment]
But 'cat' is a unix command. It takes the input of a file and prints it at stdout. It doesn't do any parsing at all. Are you sure you are not misusing it?

**Comment by liyili2** [comment]
Yes, I am very sure. That must be something wrong in krun.

**Comment by dwightguth** [comment]
Yes, I'm fully aware that krun has a nasty hack right now. That was what I
proposed to fix when I have the time. Can you please show me the syntax
that kcc outputs which kast cannot interpret? I can help you figure out
what to do. Obviously we need to fix the hack eventually, but it will be
much easier to do with the new kast, so I would rather wait if I can.

**Comment by dwightguth** [comment]
Closing in favor of #636
