### ISSUE TITLE
Error when parsing with null pointer

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#633]
This error show up this morning when I update my unified-builtins branch to the newest one (I did update yesterday). Before today, this set or rules can be parsed.

When I have this set of rules:

```
module C-SYMBOLIC-VALUE
     syntax SymLoc ::= "NullPointer"
     syntax Bits ::= Int
     syntax CSize ::= Int
     syntax CSize ::= SymVal
     syntax SymLoc ::= SymVal
     syntax Bits ::= SymVal
     syntax SymVal ::= "symVal"
     syntax Int ::= offset(SymLoc) [function]
     rule offset(symVal) => symVal

endmodule
```

It will show this error:

```
Exception in thread "main" java.lang.NullPointerException
    at org.kframework.parser.concrete.disambiguate.CorrectRewritePriorityFilter.visit(CorrectRewritePriorityFilter.java:54)
    at org.kframework.parser.concrete.disambiguate.CorrectRewritePriorityFilter.visit(CorrectRewritePriorityFilter.java:28)
    at org.kframework.kil.Ambiguity.accept(Ambiguity.java:63)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
    at org.kframework.kil.AbstractVisitor.genericVisitChild(AbstractVisitor.java:113)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:326)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:344)
    at org.kframework.kil.Rule.accept(Rule.java:72)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.parser.generator.DisambiguateRulesFilter.visit(DisambiguateRulesFilter.java:49)
    at org.kframework.parser.generator.DisambiguateRulesFilter.visit(DisambiguateRulesFilter.java:26)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:344)
    at org.kframework.kil.Rule.accept(Rule.java:72)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
    at org.kframework.kil.AbstractVisitor.genericVisitList(AbstractVisitor.java:135)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:300)
    at org.kframework.parser.generator.DisambiguateRulesFilter.visit(DisambiguateRulesFilter.java:39)
    at org.kframework.parser.generator.DisambiguateRulesFilter.visit(DisambiguateRulesFilter.java:26)
    at org.kframework.kil.Module.accept(Module.java:96)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
    at org.kframework.kil.AbstractVisitor.genericVisitList(AbstractVisitor.java:135)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:284)
    at org.kframework.kil.Definition.accept(Definition.java:185)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.parser.DefinitionLoader.parseDefinition(DefinitionLoader.java:301)
    at org.kframework.parser.DefinitionLoader.loadDefinition(DefinitionLoader.java:86)
    at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:181)
    at org.kframework.kompile.KompileFrontEnd.kompile(KompileFrontEnd.java:161)
    at org.kframework.kompile.KompileFrontEnd.main(KompileFrontEnd.java:72)
    at org.kframework.main.Main.main(Main.java:49)

```

**Comment by dwightguth** [comment]
Radu can you bisect this and add a regression test?

**Comment by radumereuta** [comment]
I managed to minimize it even more:

```
module TEST
     syntax T1 ::= B1 | B2
     syntax T2 ::= B1 | B2
     syntax B1 ::= "b1"
     syntax B2 ::= "b2"
     rule b1 => b2
endmodule
```

The problem is that I cannot infer a unique sort for the rewrite, since I can have both T1 and T2.
I'm thinking of making this an error, since the therm is ambiguous from a sorting perspective.

This is happening now in unified-builtins because yesterday, @yilongli changed how we calculate LUB.
In master it returns one of them (wrong), in u-b2 it returns null.

So, what is the sort of the rewrite then? Should I make it K if I can't uniquely infer something smaller?
@grosu @andreistefanescu @dwightguth @yilongli suggestions?

**Comment by dwightguth** [comment]
Yes, KItem sounds correct in this case.

**Comment by radumereuta** [comment]
I think I'm going to try and do it with a fixed point calculation.
If I find T1 and T2 after running the LUB algorithm, then try to run it again with T1 and T2, and so on, until we get an unique result. Worst case scenario we will get K.

I will start working on this right now. Please speak quickly if you disagree.

**Comment by dwightguth** [comment]
That sounds acceptable, but please make it a method of class Poset called "greatest unique lower bound" or something.

**Comment by grosu** [comment]
I personally think that this should be an error.  The user the option to syntactically cast some terms in the rule; any of the following would work:

```

     rule b1::T1 => b2    // b2 would then also be inferred sort T1

     rule b1 => b2::T1    // b1 would then also be inferred sort T1

     rule b1::T1 => b2::T1

     rule b1::K => b2::T1


rule b1::T1 => b2::K

     rule b1::K => b2::K


```

and similarly for T2.

In general, I think that rules should be inferred to have the LUB sort of the LHS and RHS, but to report an error if such a LUB does not exist in the partial order of sorts.  It should NOT assume the sort K by default, because in most cases that is likely hiding some error.  If users really mean K, then they have the option to cast the two terms to K.

Grigore

**Comment by grosu** [comment]
I think greatest unique UB is risky, because it can hide errors.  I would stick to LUB in the user-defined sort lattice, with an error if such a LUB does not exist.  But I'm open for debates.

**Comment by dwightguth** [comment]
Oh wait. I misunderstood the example. Yes, Grigore is correct, if a term does not have a unique GLB, it should be an error.

**Comment by radumereuta** [comment]
Ok, I can go with that too. I think we will find some errors in our definitions.
Since @yilongli is the last one to modify the code, would you like to take care of it?
I'm not sure why you needed the change, and how you want to use it in the java backend.
The only change would be to return a set of possibilities, or to throw an exception with some information regarding the found sorts (I'm favoring the first solution).

**Comment by yilongli** [comment]
Yeah, I already have a method called `getMaximalUpperBounds` and I will create another `getMinimalLowerBounds` and use it for the error message. I will do it when I have time.

**Comment by radumereuta** [comment]
Ok, let me know when you have them, so I can close this issue.

**Comment by dwightguth** [comment]
Assigning to Radu. Please fix asap tomorrow. This is blocking our deliverable at the end of the month

**Comment by yilongli** [comment]
@radumereuta the `getMinimalLowerBounds` is already implemented. The only thing left is to give an error message in your parser. Thanks.

**Comment by radumereuta** [comment]
This is no longer an issue.
