### ISSUE TITLE
Standard output does not work

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#654]
I think this is a very trivial bug, so I believe that someone is working on this. Can anyone tell me when it will be done? OR what is the correct output for java backend

```
module TEST
     syntax KItem ::= "printSuccess"
     rule printSuccess => #write(#stdout, "Translation successful!\n")

endmodule
```

The output for Maude backend is 

```
Translation successful!
<k>
    .K
</k>
```

The output for Javabackend is 

```
[2, 11.01 ms]
<k>
    #write ( #stdout , "Translation successful!\n" ) ~> _46:K
</k>
```

**Comment by liyili2** [comment]
Update some information about this problem:

This set of rules does not work:

```
module TEST

     syntax KItem ::= print(String) [function]

     rule print(S:String) => #write(#stdout,S)


endmodule
```

The output of krun is:

```
[0, 2.782 ms]
<k>
    #write ( #stdout , "success" )
</k>
```

This set of rules works:

```
module TEST

     syntax KItem ::= print(String) [function]

     rule print(S:String) => #write(1,S)


endmodule
```

The output is that:

```
success[0, 1.970 ms]
<k>
    .K
</k>
```

This set of rules works

```
module TEST

     syntax KItem ::= print(Int,String) [function]

     rule print(I:Int,S:String) => #write(I,S)


endmodule
```

The output is:

```
success[0, 1.934 ms]
<k>
    .K
</k>

```

**Comment by liyili2** [comment]
Update information:

This set of rules:

```
module TEST

     configuration <k> $PGM:K ~> print </k>

     syntax KItem ::= "print" [function] | Int

     rule <k> I:Int => .K ...</k>

     rule print => #write(1,"success")


endmodule
```

If I run program a.test and use krun --smt=none:

```
1
```

The output is more strange:

```
Exception in thread "main" java.lang.ClassCastException: org.kframework.backend.java.kil.KItemProjection cannot be cast to org.kframework.backend.java.kil.Variable
    at org.kframework.backend.java.kil.KSequence.of(KSequence.java:75)
    at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:279)
    at org.kframework.backend.java.symbolic.PrePostTransformer.transform(PrePostTransformer.java:229)
    at org.kframework.backend.java.kil.KSequence.accept(KSequence.java:193)
    at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:52)
    at org.kframework.backend.java.symbolic.PrePostTransformer.transform(PrePostTransformer.java:62)
    at org.kframework.backend.java.kil.Cell.accept(Cell.java:119)
    at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:64)
    at org.kframework.backend.java.symbolic.PrePostTransformer.transform(PrePostTransformer.java:74)
    at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:195)
    at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:52)
    at org.kframework.backend.java.symbolic.PrePostTransformer.transform(PrePostTransformer.java:62)
    at org.kframework.backend.java.kil.Cell.accept(Cell.java:119)
    at org.kframework.backend.java.kil.Term.substituteAndEvaluate(Term.java:169)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.constructNewSubjectTerm(SymbolicRewriter.java:383)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.computeRewriteStep(SymbolicRewriter.java:276)
    at org.kframework.backend.java.symbolic.SymbolicRewriter.rewrite(SymbolicRewriter.java:94)
    at org.kframework.backend.java.symbolic.JavaSymbolicKRun.javaKILRun(JavaSymbolicKRun.java:118)
    at org.kframework.backend.java.symbolic.JavaSymbolicKRun.internalRun(JavaSymbolicKRun.java:81)
    at org.kframework.backend.java.symbolic.JavaSymbolicKRun.run(JavaSymbolicKRun.java:76)
    at org.kframework.krun.Main.normalExecution(Main.java:371)
    at org.kframework.krun.Main.execute_Krun(Main.java:1453)
    at org.kframework.main.Main.main(Main.java:64)

```

**Comment by dwightguth** [comment]
@liyili2 is this still an active issue for you?

**Comment by liyili2** [comment]
This works fine now.
