### ISSUE TITLE
Parsing error of java backend when parsing programs.

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#669]
If I have this set of rules:

```
module TEST

     configuration <k> $PGM:K</k><ss>""</ss>

     syntax KResult ::= C
     syntax KItem ::= klist(KList) [klabel('klist)]
     syntax C ::= list(List)


     syntax TranslationUnit ::= TranslationUnit(String, K, K)
          [klabel('TranslationUnit),strict(2,3)]

     rule klist(.KList) => list(.List) [structural]

     rule <k>TranslationUnit(S:String, A:C, B:C) => A ~> B ...</k>
      <ss> _:String => S </ss>

endmodule
```

and I have the following program:

```
'TranslationUnit("/home/qangel/project/c-semantics/libc/src/ctype.c",, 'klist(.KList),, 'klist(.KList))
```

with the command:

```
krun a.test --smt=none --parser "kast --parser ground"
```

The output is not correct, becuase the 'klist(.KList) cannot be recognized as klist and it cannot be rewritten to list(.List)

```
[1, 13.31 ms]
<k>
    'klist(.KList) ~> TranslationUnit ( 
      "/home/qangel/project/c-semantics/libc/src/ctype.c" , HOLE , 'klist(
      .KList) )
</k>
<ss>
    ""
</ss>

```

If I have the following set of rules:

```
module TEST

     configuration <k> $PGM:K</k><ss>""</ss>

     syntax KItem ::= klist(KList) [klabel('klist)]
     syntax C ::= list(List)
     syntax TranslationUnit ::= TranslationUnit(String, K, K)
          [klabel('TranslationUnit)]

     rule klist(.KList) => list(.List) [structural]

     syntax KList ::= "UnitOfKList"

     rule UnitOfKList => .KList [structural]

     rule <k>TranslationUnit(S:String, A:C, B:C) => A ~> B ...</k>
      <ss> _:String => S </ss>

endmodule
```

and I run this following program:

```
TranslationUnit("/home/qangel/project/c-semantics/libc/src/ctype.c", klist(UnitOfKList), klist(UnitOfKList))
```

with the command:

```
krun a.test --smt=none
```

The output will be an error:

```
Exception in thread "main" java.lang.ClassCastException: org.kframework.kil.TermCons cannot be cast to org.kframework.backend.java.kil.Term
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:190)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:78)
    at org.kframework.kil.KInjectedLabel.accept(KInjectedLabel.java:81)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:165)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:78)
    at org.kframework.kil.KApp.accept(KApp.java:180)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:249)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:78)
    at org.kframework.kil.KList.accept(KList.java:52)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:166)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:78)
    at org.kframework.kil.KApp.accept(KApp.java:180)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:249)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:78)
    at org.kframework.kil.KList.accept(KList.java:52)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:166)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:78)
    at org.kframework.kil.KApp.accept(KApp.java:180)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:268)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:78)
    at org.kframework.kil.Cell.accept(Cell.java:287)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:315)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:78)
    at org.kframework.kil.Bag.accept(Bag.java:69)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:258)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:78)
    at org.kframework.kil.Cell.accept(Cell.java:287)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transformTerm(KILtoBackendJavaKILTransformer.java:134)
    at org.kframework.backend.java.kil.Term.of(Term.java:50)
    at org.kframework.backend.java.symbolic.JavaSymbolicKRun.javaKILRun(JavaSymbolicKRun.java:96)
    at org.kframework.backend.java.symbolic.JavaSymbolicKRun.internalRun(JavaSymbolicKRun.java:81)
    at org.kframework.backend.java.symbolic.JavaSymbolicKRun.run(JavaSymbolicKRun.java:76)
    at org.kframework.krun.Main.normalExecution(Main.java:371)
    at org.kframework.krun.Main.execute_Krun(Main.java:1453)
    at org.kframework.main.Main.main(Main.java:64)

```

**Comment by dwightguth** [comment]
@yilongli do we have a check now that forbids users to extend KList?

**Comment by yilongli** [comment]
No. I will add one in https://github.com/kframework/k/pull/714.

**Comment by yilongli** [comment]
I am not even sure if it is a bug in the Java backend. The problem is that in the definition `klist(.KList)` is considered as klabel `'klist` applied to a single argument `.KList`, while in the program parsed with option `--parser "kast --parser ground"`, `klist(.KList)` is considered as klabel `'klist` applied to an empty KList (which is incorrect).

Then the Java rewrite engine just does what it is supposed to do.

How should I proceed here? @radumereuta @andreistefanescu

**Comment by andreistefanescu** [comment]
The kast parser output is incorrect. It should inject .KList, although I am
not sure what the correct syntax is.

**Comment by yilongli** [comment]
I think the syntax is correct but the parser is not?

**Comment by radumereuta** [comment]
You should look over the maudifying filter, because in the parser I'm not adding any injections.

**Comment by yilongli** [comment]
I am afraid I am not the best person to fix this problem.

**Comment by dwightguth** [comment]
So klist injections are deprecated and we have no long term support plans
for them. As long as everything works correctly for users who inject KList
using an ordinary klabel, we should not take further action on this. Which
is it? Is it just the KList2KLabel that's broken, or is there something
else?
