### ISSUE TITLE
error in java backend of casting variable to term

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#676]
Hi,

   When I use krun to run the c program in c semantics library and use this command:

```
krun --smt=none --output="pretty" --output-file="ctype.pretty.o" -cOPTIONS="(SetItem(NOLINK) .Set)" -cOBJ1=".Bag" -cOBJ2=".Bag" --parser "kast --parser ground" -d /home/qangel/project/c-semantics/dist/c11-translation-kompiled ctype.c11-translation
```

The output is not correct, some steps are missing and escaping. 

Then, I tried to use the command:

```
krun --smt=none --output="pretty" --output-file="ctype.pretty.o" -cOPTIONS="(SetItem(NOLINK) .Set)" -cOBJ1=".Bag" -cOBJ2=".Bag" --parser "kast --parser ground" -d /home/qangel/project/c-semantics/dist/c11-translation-kompiled ctype.c11-translation --depth=4
```

It will give me an error as:

```
[4, 45.74 ms]
Exception in thread "main" java.lang.ClassCastException: org.kframework.kil.Variable cannot be cast to org.kframework.backend.java.kil.Term
    at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:525)
    at org.kframework.backend.java.kil.SetElementChoice.accept(SetElementChoice.java:105)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transformTerms(BackendJavaKILtoKILTransformer.java:124)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:111)
    at org.kframework.backend.java.kil.KList.accept(KList.java:148)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:80)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:482)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:87)
    at org.kframework.backend.java.kil.KItemProjection.accept(KItemProjection.java:97)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transformTerms(BackendJavaKILtoKILTransformer.java:124)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:117)
    at org.kframework.backend.java.kil.KSequence.accept(KSequence.java:193)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:50)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:63)
    at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:195)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:50)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:63)
    at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:195)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:50)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:63)
    at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:195)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:50)
    at org.kframework.backend.java.kil.Cell.accept(Cell.java:119)
    at org.kframework.backend.java.symbolic.JavaSymbolicKRun.internalRun(JavaSymbolicKRun.java:82)
    at org.kframework.backend.java.symbolic.JavaSymbolicKRun.step(JavaSymbolicKRun.java:401)
    at org.kframework.krun.Main.normalExecution(Main.java:366)
    at org.kframework.krun.Main.execute_Krun(Main.java:1453)
    at org.kframework.main.Main.main(Main.java:64)

```

**Comment by liyili2** [comment]
If I run the command by using raw option:

```
krun --smt=none --output="raw" --output-file="ctype.pretty.o" -cOPTIONS="(SetItem(NOLINK) .Set)" -cOBJ1=".Bag" -cOBJ2=".Bag" --parser "kast --parser ground" -d /home/qangel/project/c-semantics/dist/c11-translation-kompiled ctype.c11-translation --depth=4
```

The output is still the same.

**Comment by liyili2** [comment]
I am reporting how to achieve this error by using my c-semantics.
First, download liyili2/c-semantics and go to java-rewriting-engine2 branch.

Second, use make command and once the make command has finished compiled file and it is going into the translation library step, hit Crtl+C and stop the step.

Third, open dict/kcc file and delete 529  - 531 lines (delete all things in sub finalCleanup function).

Fourth, run the command (you can hit Crtl+C immediately after it runs the first krun, this step is to generate the ctype.c11-translation file):

```
dist/kcc -d -clib -o dist/lib/libc.o libc/src/ctype.c libc/src/math.c libc/src/stdio.c libc/src/stdlib.c libc/src/string.c

```

Fifth, run the command:

```
krun --smt=none --output="pretty" --output-file="ctype.pretty.o" -cOPTIONS="(SetItem(NOLINK) .Set)" -cOBJ1=".Bag" -cOBJ2=".Bag" --parser "kast --parser ground" -d /home/qangel/project/c-semantics/dist/c11-translation-kompiled ctype.c11-translation 
```

and

```
krun --smt=none --output="pretty" --output-file="ctype.pretty.o" -cOPTIONS="(SetItem(NOLINK) .Set)" -cOBJ1=".Bag" -cOBJ2=".Bag" --parser "kast --parser ground" -d /home/qangel/project/c-semantics/dist/c11-translation-kompiled ctype.c11-translation --depth=4

```

Then, you can see the difference.

**Comment by yilongli** [comment]
the crashing error should be fixed via https://github.com/kframework/k/pull/700
