### ISSUE TITLE
strange a meaningless error message when compiling definitions with tokens

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#693]
Compiling the following definition 

```
module TEST
   syntax Text ::= Token{[A-Z]}
endmodule
```

I got the following output:

```
$ kompile test.k 
Exception in thread "main" java.lang.AssertionError: An error message should have been thrown here in the above loop.
    at org.kframework.parser.concrete.disambiguate.VariableTypeInferenceFilter.visit(VariableTypeInferenceFilter.java:234)
    at org.kframework.parser.concrete.disambiguate.VariableTypeInferenceFilter.visit(VariableTypeInferenceFilter.java:26)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:344)
    at org.kframework.kil.Rule.accept(Rule.java:72)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.parser.generator.DisambiguateRulesFilter.visit(DisambiguateRulesFilter.java:54)
    at org.kframework.parser.generator.DisambiguateRulesFilter.visit(DisambiguateRulesFilter.java:26)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:344)
    at org.kframework.kil.Rule.accept(Rule.java:72)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
    at org.kframework.kil.AbstractVisitor.genericVisitList(AbstractVisitor.java:135)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:300)
    at org.kframework.parser.generator.DisambiguateRulesFilter.visit(DisambiguateRulesFilter.java:39)
    at org.kframework.parser.generator.DisambiguateRulesFilter.visit(DisambiguateRulesFilter.java:26)
    at org.kframework.kil.Module.accept(Module.java:96)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
    at org.kframework.kil.AbstractVisitor.genericVisitList(AbstractVisitor.java:135)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:284)
    at org.kframework.kil.Definition.accept(Definition.java:183)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.parser.DefinitionLoader.parseDefinition(DefinitionLoader.java:303)
    at org.kframework.parser.DefinitionLoader.loadDefinition(DefinitionLoader.java:86)
    at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:181)
    at org.kframework.kompile.KompileFrontEnd.kompile(KompileFrontEnd.java:161)
    at org.kframework.kompile.KompileFrontEnd.main(KompileFrontEnd.java:72)
    at org.kframework.main.Main.main(Main.java:49)
```

**Comment by dwightguth** [comment]
Assigning to Radu since it pertains to sort inference.

**Comment by radumereuta** [comment]
This is already fixed in the unified builtins branch (we are trying to move away from master).
You would get the following error message:

```
[Error] Critical: Unsolvable ambiguities. Please write the rule in labeled form.
 (Generally because of __ productions mixing with variables).
        File: D:\work\k\include\k-prelude.k
        Location: (21,3,21,51)
```

The problem is that that the token declaration creates loads of ambiguities conflicting with variables.
Please consider using [onlyLabel].

**Comment by grosu** [comment]
What?  This is a TERRIBLE error message, Radu!  First, there is no rule in Dorel's example.  Second, we do NOT want to encourage users to use the labeled form ever in their definitions!  That is reserved for experts and in rare cases.  We have syntactic casts which should/must be capable of solving any syntactic conflicts.

**Comment by radumereuta** [comment]
Believe me or not, but that is the best I can do.
First of all, the problem comes from the fact that we have only one parse table for all files. If you look at the location of the error message, is in `k-prelude.k`.
Secondly I can't detect this type of ambiguities. All I can see is that on different branches of ambiguities I have different numbers of variables. That's where I'm reporting this error message.

I'm opened to suggestions if you have better ideas.

**Comment by grosu** [comment]
For God's sake Radu, you should never report an error message in the k-prelude.k or anything that we provide!  That is supposed to be error-free.  No matter what the user does, there should be no errors in the provided modules (unless they modify those).  The fact that you mix all the syntax and then parse all the modules is just plain wrong and needs to be changed from the root.

**Comment by radumereuta** [comment]
I know that, the alternative with SDF would be that parsing would take several minutes for the most simple example.
This is one of the problems the new parser should solve, because right now we can't even talk about modularity.

**Comment by dwightguth** [comment]
Well no, we could do what I tried to get us to do and we decided not to,
which is to cache the parse for the entire includes directory when ant is
run.

**Comment by radumereuta** [comment]
That would be yet another half measure hack involving SDF.
I think we are way past the point where we should try and improve the old parser, so I am not willing to work on this.

**Comment by andreistefanescu** [comment]
I agree that we should focus our efforts on the new parser. Radu, can you
remind us what is the status of the new parser, and what is left to be done?

**Comment by radumereuta** [comment]
Basically, same as a month ago. I've spent my time with bugs and fixes to SDF, the disambiguation filters, caching...
When I left the new parser, I could parse all programs using java disambiguation filters (parser returns the full DAG). It isn't very efficient yet. I have to implement native priority support, which would disambiguate at parse time, making parsing more efficient.

Considering my latest progress with my work, I will try harder to actively ignore bugs in the old code. So I am apologizing in advance.

**Comment by dlucanu** [comment]
I understand that, but I need to solve some how the problem with //. Can we an option that disables the use of "//" as a line comment?

**Comment by radumereuta** [comment]
Whitespace is so deeply embedded into SDF that right now I can only recommend an external parser.
