### ISSUE TITLE
Java backend hooking =/=K problem

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#719]
Hi,

   When I kompile my version of c semantics after we delete the =/=List, a problem appears when the we are kompiling the c semantics and trying to hook the =/=K function. The exception of java backend is like:

```
Basic Parsing                                                =   589
Preprocess                                                   =   245
Checks                                                       =    15
File Gen Pgm                                                 =   294
Generate TBLPgm                                              =  1162
File Gen Def                                                 =  1713
Generate TBLDef                                              = 65148
Importing Files                                              =  1925
Parsing Configs                                              =  1599
Parsing Rules [1935/1935]                                    = 22532
Ignored exception thrown by hook '_=/=K_ : 
java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.kframework.backend.java.symbolic.BuiltinFunction.invoke(BuiltinFunction.java:147)
    at org.kframework.backend.java.kil.KItem.evaluateFunction(KItem.java:273)
    at org.kframework.backend.java.symbolic.LocalEvaluator.transform(LocalEvaluator.java:47)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:483)
    at org.kframework.backend.java.symbolic.CombinedLocalTransformer.transformAll(CombinedLocalTransformer.java:48)
    at org.kframework.backend.java.symbolic.CombinedLocalTransformer.transform(CombinedLocalTransformer.java:128)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:483)
    at org.kframework.backend.java.symbolic.PrePostTransformer.transform(PrePostTransformer.java:145)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:483)
    at org.kframework.backend.java.symbolic.Evaluator.evaluate(Evaluator.java:26)
    at org.kframework.backend.java.kil.Term.evaluate(Term.java:186)
    at org.kframework.backend.java.kil.Term.evaluate(Term.java:163)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.evaluateRule(KILtoBackendJavaKILTransformer.java:783)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.evaluateDefinition(KILtoBackendJavaKILTransformer.java:730)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transformDefinition(KILtoBackendJavaKILTransformer.java:111)
    at org.kframework.backend.java.symbolic.JavaSymbolicBackend.lastStep(JavaSymbolicBackend.java:65)
    at org.kframework.main.LastStep.compile(LastStep.java:22)
    at org.kframework.main.LastStep.compile(LastStep.java:11)
    at org.kframework.compile.utils.CompilerSteps.compile(CompilerSteps.java:44)
    at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:192)
    at org.kframework.kompile.KompileFrontEnd.kompile(KompileFrontEnd.java:161)
    at org.kframework.kompile.KompileFrontEnd.main(KompileFrontEnd.java:72)
    at org.kframework.main.Main.main(Main.java:49)
Caused by: java.lang.UnsupportedOperationException: list matching is only supported when one of the lists is a variable.
    at org.kframework.backend.java.symbolic.SymbolicUnifier.unify(SymbolicUnifier.java:216)
    at org.kframework.backend.java.kil.BuiltinList.accept(BuiltinList.java:166)
    at org.kframework.backend.java.symbolic.SymbolicUnifier.unify(SymbolicUnifier.java:203)
    at org.kframework.backend.java.symbolic.SymbolicUnifier.unify(SymbolicUnifier.java:142)
    at org.kframework.backend.java.symbolic.SymbolicConstraint.simplify(SymbolicConstraint.java:982)
    at org.kframework.backend.java.builtins.TermEquality.getEqualityTruthValue(TermEquality.java:57)
    at org.kframework.backend.java.builtins.TermEquality.ne(TermEquality.java:36)
    ... 26 more
Ignored exception thrown by hook '_=/=K_ : 
java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.kframework.backend.java.symbolic.BuiltinFunction.invoke(BuiltinFunction.java:147)
    at org.kframework.backend.java.kil.KItem.evaluateFunction(KItem.java:273)
    at org.kframework.backend.java.symbolic.LocalEvaluator.transform(LocalEvaluator.java:47)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:483)
    at org.kframework.backend.java.symbolic.CombinedLocalTransformer.transformAll(CombinedLocalTransformer.java:48)
    at org.kframework.backend.java.symbolic.CombinedLocalTransformer.transform(CombinedLocalTransformer.java:128)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:483)
    at org.kframework.backend.java.symbolic.PrePostTransformer.transform(PrePostTransformer.java:145)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:483)
    at org.kframework.backend.java.symbolic.Evaluator.evaluate(Evaluator.java:26)
    at org.kframework.backend.java.kil.Term.evaluate(Term.java:186)
    at org.kframework.backend.java.kil.Term.evaluate(Term.java:163)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.evaluateRule(KILtoBackendJavaKILTransformer.java:783)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.evaluateDefinition(KILtoBackendJavaKILTransformer.java:730)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transformDefinition(KILtoBackendJavaKILTransformer.java:111)
    at org.kframework.backend.java.symbolic.JavaSymbolicBackend.lastStep(JavaSymbolicBackend.java:65)
    at org.kframework.main.LastStep.compile(LastStep.java:22)
    at org.kframework.main.LastStep.compile(LastStep.java:11)
    at org.kframework.compile.utils.CompilerSteps.compile(CompilerSteps.java:44)
    at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:192)
    at org.kframework.kompile.KompileFrontEnd.kompile(KompileFrontEnd.java:161)
    at org.kframework.kompile.KompileFrontEnd.main(KompileFrontEnd.java:72)
    at org.kframework.main.Main.main(Main.java:49)
Caused by: java.lang.UnsupportedOperationException: list matching is only supported when one of the lists is a variable.
    at org.kframework.backend.java.symbolic.SymbolicUnifier.unify(SymbolicUnifier.java:216)
    at org.kframework.backend.java.kil.BuiltinList.accept(BuiltinList.java:166)
    at org.kframework.backend.java.symbolic.SymbolicUnifier.unify(SymbolicUnifier.java:203)
    at org.kframework.backend.java.symbolic.SymbolicUnifier.unify(SymbolicUnifier.java:142)
    at org.kframework.backend.java.symbolic.SymbolicConstraint.simplify(SymbolicConstraint.java:982)
    at org.kframework.backend.java.builtins.TermEquality.getEqualityTruthValue(TermEquality.java:57)
    at org.kframework.backend.java.builtins.TermEquality.ne(TermEquality.java:36)
    ... 26 more
```

**Comment by yilongli** [comment]
I am not familiar with this issue. @dwightguth @andreistefanescu What do these exceptions mean?

**Comment by andreistefanescu** [comment]
The current implementation of ==K tries to unify the two arguments, and return true if they are unifiable with the empty substitution and false if they are not unifiable. Right now the unification throws an exception because there are lists in both side which is not supported. I would say it kind of is the expected behavior. Maybe we should only print this error messages if --debug is set, or something.

**Comment by liyili2** [comment]
Actually, I found that the following rule will cause the exception.

```
     rule Comma(list(ListItem(K:K) L:List)) 
          => commaEval(K) ~> discard ~> Comma(list(L))
          when L =/=MSet .List
          [structural]
```

It seems that the exception will be thrown not only when we have lists in both side of a condition, but also when we have a matching of list variable in a body of a rule and we use this variable in the condition.

**Comment by yilongli** [comment]
@andreistefanescu I understand that you need to invoke unification in order to use z3. But shouldn't ==K be the simple syntactic equality check?

**Comment by andreistefanescu** [comment]
@yilongli you can make ==K to be the syntactic equality, but them most of the places should use =K (the semantics equality), or the definitions would not work well in a symbolic checking.

**Comment by yilongli** [comment]
@andreistefanescu I know. Then why do we differentiate ==K and =K in the first place if the pure syntactic equality check is rarely used? Maybe what we need is different behaviors of ==K under concrete mode and symbolic mode?

**Comment by andreistefanescu** [comment]
I don't think changing the behavior of ==K based on concrete or symbolic
execution is a good idea. First, we should consider what are the cases
where syntactic equality is actually needed.

**Comment by dlucanu** [comment]
IMHO, the definitions of "==K" and "=K" should clear, clean and independent of backend.
"==K" must be only for syntactic equality and "=K" for semantic equality. If we have "I =K J $ and I, J are of sort Int, then "=K" must become "=Int" (the semantic equality on Int).
