### ISSUE TITLE
ktest crashes!

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#72]
fslwork$ pwd
/home/grosu/k/dist/tutorial/1_k/2_imp/lesson_5
fslwork$ ktest -d imp.k
Kompiling the language definitions...(1)
SUCCESS
Generating PDF documentation...(1)
Exception in thread "pool-2-thread-1" java.lang.NullPointerException
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1010)
    at org.kframework.ktest.execution.Task.run(Task.java:43)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)

FAIL: imp.k

Running imp.k programs... (0)
SUCCESS
fslwork$

**Comment by daejunpark** [comment]
Fixed at b5e9133c857f9c05b497ebf48f71e68ad5d0f2d6.
