### ISSUE TITLE
Happen again: when I use depth to show a intermediate step in Java backend

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#722]
When I run the ctype.c program by c semantics in Java backend. If I run the following command:

```
 krun --smt=none --output="pretty" --output-file="ctype.pretty.o" -cOPTIONS="(SetItem(NOLINK) .Set)" -cOBJ1=".Bag" -cOBJ2=".Bag" --parser "kast --parser ground" -d /home/qangel/project/c-semantics/dist/c11-translation-kompiled ctype.c11-translation --depth=55
```

I will get the result of:

```
Exception in thread "main" java.lang.UnsupportedOperationException: Not implemented, yet
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:267)
    at org.kframework.backend.java.kil.ListLookup.accept(ListLookup.java:119)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transformTerms(BackendJavaKILtoKILTransformer.java:148)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:135)
    at org.kframework.backend.java.kil.KList.accept(KList.java:148)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:104)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:483)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transformTerms(BackendJavaKILtoKILTransformer.java:148)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:141)
    at org.kframework.backend.java.kil.KSequence.accept(KSequence.java:196)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:74)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:87)
    at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:200)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:74)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:87)
    at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:200)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:74)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:87)
    at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:200)
    at org.kframework.backend.java.symbolic.BackendJavaKILtoKILTransformer.transform(BackendJavaKILtoKILTransformer.java:74)
    at org.kframework.backend.java.kil.Cell.accept(Cell.java:142)
    at org.kframework.backend.java.symbolic.JavaSymbolicKRun.internalRun(JavaSymbolicKRun.java:82)
    at org.kframework.backend.java.symbolic.JavaSymbolicKRun.step(JavaSymbolicKRun.java:401)
    at org.kframework.krun.Main.normalExecution(Main.java:366)
    at org.kframework.krun.Main.execute_Krun(Main.java:1449)
    at org.kframework.main.Main.main(Main.java:64)

```

It seems that the intermediate step cannot be printed out.

**Comment by yilongli** [comment]
fixed in https://github.com/kframework/k/pull/726
