### ISSUE TITLE
New error in new version of Kompile in Java Backend

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#781]
This function runs successfully for the version of Java Backend before Friday; however, when I run it today, it fails. The definition is:

```
module TEST

     syntax Set ::= #filterSet(K,Set,KLabel) [function]

     rule #filterSet(K:K,.Set,Pred:KLabel)
      => SetItem(K:K)
      requires Pred(K:K) ==K true
     rule #filterSet(K:K,.Set,Pred:KLabel)
      => .Set 
          requires Pred(K:K) =/=K true
     rule #filterSet(K:K,SetItem(K':K) S:Set,Pred:KLabel)
      => SetItem(K) #filterSet(K',S,Pred)
      requires Pred(K:K) ==K true
     rule #filterSet(K:K,SetItem(K':K) S:Set,Pred:KLabel)
      => #filterSet(K',S,Pred)
          requires Pred(K:K) =/=K true

endmodule
```

The kompile error is:

```
Exception in thread "main" java.lang.AssertionError: unexpected sort KItem of concatenated term '#filterSet(K':K,, GeneratedFreshVar50:Set[K':K <- undef],, (# Pred:KLabel)(.KList)); expected Set
    at org.kframework.backend.java.kil.BuiltinSet$Builder.concatenate(BuiltinSet.java:179)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:389)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:79)
    at org.kframework.kil.SetBuiltin.accept(SetBuiltin.java:28)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:499)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:79)
    at org.kframework.kil.Rule.accept(Rule.java:93)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:633)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:79)
    at org.kframework.kil.Definition.accept(Definition.java:185)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transformDefinition(KILtoBackendJavaKILTransformer.java:107)
    at org.kframework.backend.java.symbolic.JavaSymbolicBackend.lastStep(JavaSymbolicBackend.java:54)
    at org.kframework.backend.LastStep.compile(LastStep.java:21)
    at org.kframework.backend.LastStep.compile(LastStep.java:10)
    at org.kframework.compile.utils.CompilerSteps.compile(CompilerSteps.java:44)
    at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:148)
    at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:118)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:40)
    at org.kframework.main.Main.main(Main.java:86)
```

**Comment by yilongli** [comment]
What is "the version of Java Backend before yesterday"? Please be specific.

**Comment by liyili2** [comment]
I don't know. I did update every day except Friday and Sat. However, I tried to reset back to the version  on Wednesday, it still didn't work.

**Comment by yilongli** [comment]
Then please find out the exact version. This is common practice of filing bug report.

**Comment by liyili2** [comment]
if I tries to reset to this version number: 

```
4d5766553706dc533d46513f4d0329613edff80d
```

it works.

**Comment by liyili2** [comment]
Sorry, I make a mistake for the version number. The version which will work for my c semantics is:

```
1f5aea62a9c1cca7d66c59cc8070737da3c97235

```

**Comment by liyili2** [comment]
@yilongli , Hi, Would you mind to tell me what is the status of the bug fixing?

**Comment by yilongli** [comment]
I have looked into this issue and it may take me the weekend to fix it.

**Comment by liyili2** [comment]
Thank you very much

**Comment by liyili2** [comment]
@andreistefanescu 

I test more on this definition and find that The last version which makes the definition work is 

```
1f5aea62a9c1cca7d66c59cc8070737da3c97235
```

The first version which makes the definition fail is

```
083e0af1ef3a250d32d92904b1dc2ea29b628c04
```

**Comment by yilongli** [comment]
fixed via https://github.com/kframework/k/pull/815
