### ISSUE TITLE
Java backend reports errors when builtins operation names are overloaded

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#796]
The following definition

```
module ISSUE
  syntax Exp ::= Int | Id
               | Exp "+" Exp 
               | Exp "+Int" Exp 
endmodule
```

compiles fine with the Maude backend, but Java backend reports an error:

```
$ kompile issue.k --backend java
Exception in thread "main" java.lang.AssertionError: Cannot determine if the KLabel '_+Int_ is a function symbol because there are multiple productions associated with this KLabel: [Exp "+Int" Exp , Int "+Int" Int ]
    at org.kframework.backend.java.kil.KLabelConstant.<init>(KLabelConstant.java:94)
    at org.kframework.backend.java.kil.KLabelConstant.of(KLabelConstant.java:138)
    at org.kframework.backend.java.symbolic.BuiltinFunction.<init>(BuiltinFunction.java:101)
    at org.kframework.backend.java.kil.GlobalContext.<init>(GlobalContext.java:15)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:617)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:79)
    at org.kframework.kil.Definition.accept(Definition.java:185)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transformDefinition(KILtoBackendJavaKILTransformer.java:107)
    at org.kframework.backend.java.symbolic.JavaSymbolicBackend.lastStep(JavaSymbolicBackend.java:53)
    at org.kframework.backend.LastStep.compile(LastStep.java:21)
    at org.kframework.backend.LastStep.compile(LastStep.java:10)
    at org.kframework.compile.utils.CompilerSteps.compile(CompilerSteps.java:44)
    at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:148)
    at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:118)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:40)
    at org.kframework.main.Main.main(Main.java:86)
```

IMHO, this definition is correct and the Maude backend compiles it correctly.

**Comment by dwightguth** [comment]
So this should generate a correct error message instead of a stack trace,
but it is not a correct definition. Productions with the same klabel must
either all be functions or all be constructors.

**Comment by dlucanu** [comment]
It seems to me that this is a new language constraint, perhaps needed for Java  backend. If yes, its violation should be reported at the parsing time, it shouldn't be backend-dependent. 
However, I find this constraint a bit too restrictive. It means that we cannot have definitions like

```
module ISSUE
  syntax Exp ::= Int | Id
               | Exp "+" Exp 
               | size(Exp)
endmodule
```

because "size" is a function defined over sets.

**Comment by radumereuta** [comment]
That's actually a very good point.
This brings back again the discussion about having unique klabels. Right now we are generating the same klabel for productions which may look the same, but which are not overloaded. In the front end I'm not giving any error message, because I am able to properly disambiguate using the context, but the backend uses (I think) the klabel to get the original production, and in this case it can't figure out which one was it.

The problem of unique klabels needs to be addressed sooner than later.
