### ISSUE TITLE
Assertion error on a certain kind of list pattern

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#8]
```
require "builtins/list.k"

module TEST
  imports LIST

  configuration <k> $PGM:K </k><l> .MyList </l>

  rule <l> .MyList (MyListItem(5) (L:MyList MyListItem(6))) => . </l>



endmodule
```

This should work. But instead I get:

Exception in thread "main" java.lang.AssertionError
        at org.kframework.kil.DataStructureBuiltin.of(DataStructureBuiltin.java:134)
        at org.kframework.compile.utils.CompileDataStructures.transform(CompileDataStructures.java:122)
        at org.kframework.kil.KApp.accept(KApp.java:148)
        at org.kframework.compile.utils.CompileDataStructures.transform(CompileDataStructures.java:118)
        at org.kframework.kil.KApp.accept(KApp.java:148)
        at org.kframework.kil.visitors.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:345)
        at org.kframework.kil.Cell.accept(Cell.java:266)
        at org.kframework.kil.visitors.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:365)
        at org.kframework.kil.visitors.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:390)
        at org.kframework.kil.Bag.accept(Bag.java:55)
        at org.kframework.kil.visitors.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:345)
        at org.kframework.kil.Cell.accept(Cell.java:266)
        at org.kframework.compile.utils.CompileDataStructures.transform(CompileDataStructures.java:56)
        at org.kframework.kil.Rule.accept(Rule.java:68)
        at org.kframework.kil.visitors.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:75)
        at org.kframework.kil.Module.accept(Module.java:136)
        at org.kframework.kil.visitors.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:42)
        at org.kframework.kil.Definition.accept(Definition.java:121)
        at org.kframework.compile.utils.CompilerTransformerStep.compile(CompilerTransformerStep.java:24)
        at org.kframework.compile.utils.CompilerSteps.compile(CompilerSteps.java:37)
        at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:296)
        at org.kframework.kompile.KompileFrontEnd.kompile(KompileFrontEnd.java:252)
        at org.kframework.main.Main.main(Main.java:68)

**Comment by dwightguth** [comment]
Er sorry that's a perfectly good error that needs to be fixed, but I just realized the exact version I need to be working is this:

rule `<l> .MyList ((MyListItem(5) L:MyList) MyListItem(6)) => . </l>`

**Comment by traiansf** [comment]
I think this compiles now.  Dwight, could you please check this is what you wanted/needed?

**Comment by dwightguth** [comment]
I no longer get this error. If something is wrong, I won't know until the program finally starts to execute, but until then I am closing this.
