### ISSUE TITLE
meaningless error message

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#804]
The following error message is completely useless:

```
$ kompile spec.k --transition computational

GTerm: null(K1Var("Ks"{(2,48,2,50)}){(2,48,2,50)},null(K1Var("Bound"{(2,52,2,57)}){(2,52,2,57)},K1Var("Free"{(2,59,2,63)}){(2,59,2,63)}){(2,52,2,63)}){(2,48,2,63)}
Error XMLifying at: null(K1Var("Ks"{(2,48,2,50)}){(2,48,2,50)},null(K1Var("Bound"{(2,52,2,57)}){(2,52,2,57)},K1Var("Free"{(2,59,2,63)}){(2,59,2,63)}){(2,52,2,63)}){(2,48,2,63)}
GTerm: null(K1Var("Ks"{(2,48,2,50)}){(2,48,2,50)},null(K1Var("Bound"{(2,52,2,57)}){(2,52,2,57)},K1Var("Free"{(2,59,2,63)}){(2,59,2,63)}){(2,52,2,63)}){(2,48,2,63)}
Error XMLifying at: null(K1Var("Ks"{(2,48,2,50)}){(2,48,2,50)},null(K1Var("Bound"{(2,52,2,57)}){(2,52,2,57)},K1Var("Free"{(2,59,2,63)}){(2,59,2,63)}){(2,52,2,63)}){(2,48,2,63)}
Exception in thread "main" java.lang.NullPointerException
    at org.kframework.utils.XmlLoader.reportErrors(XmlLoader.java:70)
    at org.kframework.parser.generator.ParseRulesFilter.visit(ParseRulesFilter.java:73)
    at org.kframework.parser.generator.ParseRulesFilter.visit(ParseRulesFilter.java:29)
    at org.kframework.kil.StringSentence.accept(StringSentence.java:36)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
    at org.kframework.kil.AbstractVisitor.genericVisitList(AbstractVisitor.java:135)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:300)
    at org.kframework.parser.generator.ParseRulesFilter.visit(ParseRulesFilter.java:48)
    at org.kframework.parser.generator.ParseRulesFilter.visit(ParseRulesFilter.java:29)
    at org.kframework.kil.Module.accept(Module.java:94)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:84)
    at org.kframework.kil.AbstractVisitor.genericVisitList(AbstractVisitor.java:135)
    at org.kframework.kil.AbstractVisitor.visit(AbstractVisitor.java:284)
    at org.kframework.kil.Definition.accept(Definition.java:185)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.parser.DefinitionLoader.parseDefinition(DefinitionLoader.java:290)
    at org.kframework.parser.DefinitionLoader.loadDefinition(DefinitionLoader.java:105)
    at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:137)
    at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:118)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:40)
    at org.kframework.main.Main.main(Main.java:86)
```

I cannot use it for create a minimal example that reproduce it.

$ kompile --version
K-framework nightly build.
Git Revision: e7eb8e2
Build date: Wed Aug 6 12:03:36 EEST 2014
Branch: unified-builtins2

**Comment by radumereuta** [comment]
Usually this happens when a lexical production interferes with something from K.
This is one of the things that I can't control in SDF. Please have another look at all the lexical productions, and make sure they don't interact weirdly with other productions (try onlyLabel). If that still doesn't work, you can give me the entire definition and I could have a look.

**Comment by dlucanu** [comment]
Thanks Radu. Being a definition distributed in several files, I accidentally did the same name to two syntactical definitions (supposed to be different) and perhaps this produced the interfering process. 
I do not know whether we should let the issue open or not, this could happen relatively often for big definitions. I let you to make the right decision.

**Comment by radumereuta** [comment]
This happens because SDF produces an AST which doesn't have a representation in KIL. This is why the error is so ugly. More specifically, I'm expecting that each term is wrapped by a label, and in some cases it may happen that some lists or constants are not, so the conversion fails.
This types of errors are hard to spot even when you look at them, automatically giving an informative error message is even harder.
The design of the new parser avoids completely this problem, so I could keep this opened just for reference, but I won't do anything in SDF to solve it.
