### ISSUE TITLE
A Parsing error which will affect Java Backend

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#824]
If I have the following definition:

```

module TEST

     configuration <k>$PGM:K</k><env>.Map</env>

     syntax KItem ::= abc(Int,Int,Int)
            | object(Int,Int,Map)

     rule <k>abc(Old:Int,New:Int,N:Int) ...</k>
      <env> Old |-> object(_, _, M:Map)
               New |-> object(_, _, _:Map (.Map => (N -Int 1) |-> M[N -Int 1])) </env>

endmodule

```

I will get the following error:

```
Exception in thread "main" java.lang.AssertionError: unexpected sort K of concatenated term projection(Map:lookup('_-Int_(N:Int,, Int(#"1")) |-> M:Map   ,, '_-Int_(N:Int,, Int(#"1")))); expected Map
    at org.kframework.backend.java.kil.BuiltinMap$Builder.concatenate(BuiltinMap.java:184)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:404)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:79)
    at org.kframework.kil.MapBuiltin.accept(MapBuiltin.java:73)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:250)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:79)
    at org.kframework.kil.KList.accept(KList.java:52)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:167)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:79)
    at org.kframework.kil.KApp.accept(KApp.java:180)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:399)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:79)
    at org.kframework.kil.MapBuiltin.accept(MapBuiltin.java:73)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:269)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:79)
    at org.kframework.kil.Cell.accept(Cell.java:295)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:316)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:79)
    at org.kframework.kil.Bag.accept(Bag.java:69)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:259)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:79)
    at org.kframework.kil.Cell.accept(Cell.java:295)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:498)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:79)
    at org.kframework.kil.Rule.accept(Rule.java:93)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:626)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:79)
    at org.kframework.kil.Definition.accept(Definition.java:185)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transformDefinition(KILtoBackendJavaKILTransformer.java:107)
    at org.kframework.backend.java.symbolic.JavaSymbolicBackend.lastStep(JavaSymbolicBackend.java:53)
    at org.kframework.backend.LastStep.compile(LastStep.java:21)
    at org.kframework.backend.LastStep.compile(LastStep.java:10)
    at org.kframework.compile.utils.CompilerSteps.compile(CompilerSteps.java:44)
    at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:148)
    at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:118)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:40)
    at org.kframework.main.Main.main(Main.java:86)

```

From the error message "projection(Map:lookup('_-Int_(N:Int,, Int(#"1")) |-> M:Map   ,, '_-Int_(N:Int,, Int(#"1"))))", we can see that the term "(N -Int 1) |-> M[N -Int 1])" in the rule of the definition is not parsed correctly. 

If I change the definition to:

```
module TEST

     configuration <k>$PGM:K</k><env>.Map</env>

     syntax KItem ::= abc(Int,Int,Int)
            | object(Int,Int,Map)

     rule <k>abc(Old:Int,New:Int,N:Int) ...</k>
      <env> Old |-> object(_, _, M:Map)
               New |-> object(_, _, _:Map (.Map => ((N -Int 1) |-> (M[N -Int 1])))) </env>

endmodule

```

The definition will be compiled properly.

**Comment by radumereuta** [comment]
I don't know how you got that stack trace, because I can't reproduce it with the latest version of unified-builtins2.

What I get instead, is an ambiguity:

```
[Warning] Inner Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: Map ::= K "|->" K
   (N:Int -Int 1) |-> (M:Map [ (N -Int 1) ])
2: K ::= Map "[" K "]"
   ((N:Int -Int 1) |-> M:Map) [ (N -Int 1) ]
        File: d:\work\k\samples\test\test.k
        Location: (10,52,10,78)
        Compilation Phase: Ambiguity filter
```

What I recommend doing, is to set up a priority between the two productions:

```
syntax priorities Map:lookup > '_|->_
```
