### ISSUE TITLE
ktest --- throws uncaught exception instead of error message

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#83]
Apparently, no matter what error you have in your config.xml, ktest throws an exception:

fslwork$ ktest config.xml --skip "pdf kompile"
Buildfile: config.xml
[Fatal Error] config.xml:9:9: The element type "all-programs" must be terminated by the matching end-tag "</all-programs>".
org.xml.sax.SAXParseException; systemId: file:/home/grosu/k/dist/tutorial/2_languages/1_simple/2_typed/1_static/exercises/exercise_1/programs/config.xml; lineNumber: 9; columnNumber: 9; The element type "all-programs" must be terminated by the matching end-tag "</all-programs>".
    at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:256)
    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:345)
    at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
    at org.kframework.ktest.KTest.parseXMLConfig(KTest.java:231)
    at org.kframework.ktest.KTest.testConfig(KTest.java:251)
    at org.kframework.ktest.KTest.test(KTest.java:211)
    at org.kframework.main.Main.main(Main.java:55)
Kompiling the language definitions...
Skipped 0 definitions
Generating PDF documentation...
Skipped 0 definitions
fslwork$

**Comment by andreiarusoaie** [comment]
Fixed. Right now it gives only the localized error message of the exception: 

[Fatal Error] config.xml:9:9: The element type "all-programs" must be terminated by the matching end-tag "".
