### ISSUE TITLE
NoClassDefFoundError: org/xmlpull/v1/XmlPullParserException

### ISSUE THREAD

**Issue by adamsmd** [kframework/k-legacy#9]
I was experimenting with `kompile` and got the following error.  Is there a Jar missing from the distribution?

```
$ cat test.k
module TEST

endmodule
```

```
$ ../../../../../../../dist/bin/kompile -xml test.k
Exception in thread "main" java.lang.NoClassDefFoundError: org/xmlpull/v1/XmlPullParserException
    at com.thoughtworks.xstream.XStream.<init>(XStream.java:336)
    at org.kframework.parser.DefinitionLoader.loadDefinition(DefinitionLoader.java:95)
    at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:284)
    at org.kframework.kompile.KompileFrontEnd.kompile(KompileFrontEnd.java:252)
    at org.kframework.main.Main.main(Main.java:68)
Caused by: java.lang.ClassNotFoundException: org.xmlpull.v1.XmlPullParserException
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 5 more

```

**Comment by traiansf** [comment]
Apparently, it is.  I'm not sure though the xml option is still maintained.  we are currently serializing to a binary format.

**Comment by andreistefanescu** [comment]
-xml is no longer supported
