### ISSUE TITLE
Java backend cannot deal with overloaded constructors 

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#902]
For the unified-builtins2 version before last Friday, the following definition can be compiled successfully:

```
module TEST

     syntax SimpleType ::= "int" | "string" | unionType (Id,Id,Id) | incompleteUnionType(Id)
     syntax Type ::= t(Set,SimpleType)

     syntax Bool ::= #areCompat(Type, Type) [function]

     syntax Bool ::= #areCompat(List, List) [function]

     rule #areCompat(
               t(Mods:Set, unionType(X:Id, _, _)),
               t(Mods':Set, incompleteUnionType(X:Id)))
          => true

     rule #areCompat(ListItem(T:Type) L:List, ListItem(T':Type) L':List)
          => #areCompat(T, T') andBool #areCompat(L, L')
     rule #areCompat(.List, .List) => true

endmodule
```

However, when I use the newest version of Unified-builtins2 version, a problem arises:

```
Exception in thread "main" java.lang.UnsupportedOperationException
    at org.kframework.backend.java.kil.ListUpdate.accept(ListUpdate.java:151)
    at org.kframework.backend.java.symbolic.PatternMatcher.match(PatternMatcher.java:507)
    at org.kframework.backend.java.symbolic.PatternMatcher.matchKCollection(PatternMatcher.java:1068)
    at org.kframework.backend.java.symbolic.PatternMatcher.match(PatternMatcher.java:1040)
    at org.kframework.backend.java.kil.KList.accept(KList.java:137)
    at org.kframework.backend.java.symbolic.PatternMatcher.match(PatternMatcher.java:507)
    at org.kframework.backend.java.symbolic.PatternMatcher.patternMatch(PatternMatcher.java:447)
    at org.kframework.backend.java.symbolic.PatternMatcher.patternMatch(PatternMatcher.java:149)
    at org.kframework.backend.java.kil.KItem$KItemOperations.evaluateFunction(KItem.java:362)
    at org.kframework.backend.java.kil.KItem$KItemOperations.resolveFunctionAndAnywhere(KItem.java:286)
    at org.kframework.backend.java.kil.KItem.resolveFunctionAndAnywhere(KItem.java:253)
    at org.kframework.backend.java.symbolic.LocalEvaluator.transform(LocalEvaluator.java:52)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:584)
    at org.kframework.backend.java.symbolic.CombinedLocalTransformer.transformAll(CombinedLocalTransformer.java:48)
    at org.kframework.backend.java.symbolic.CombinedLocalTransformer.transform(CombinedLocalTransformer.java:128)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:584)
    at org.kframework.backend.java.symbolic.PrePostTransformer.transform(PrePostTransformer.java:145)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:584)
    at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transformList(CopyOnWriteTransformer.java:630)
    at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:215)
    at org.kframework.backend.java.symbolic.PrePostTransformer.transform(PrePostTransformer.java:217)
    at org.kframework.backend.java.kil.KList.accept(KList.java:147)
    at org.kframework.backend.java.symbolic.CopyOnWriteTransformer.transform(CopyOnWriteTransformer.java:152)
    at org.kframework.backend.java.symbolic.PrePostTransformer.transform(PrePostTransformer.java:144)
    at org.kframework.backend.java.kil.KItem.accept(KItem.java:584)
    at org.kframework.backend.java.symbolic.Evaluator.evaluate(Evaluator.java:27)
    at org.kframework.backend.java.kil.Term.evaluate(Term.java:166)
    at org.kframework.backend.java.kil.Term.evaluate(Term.java:143)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.evaluateRule(KILtoBackendJavaKILTransformer.java:665)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.evaluateDefinition(KILtoBackendJavaKILTransformer.java:615)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transformDefinition(KILtoBackendJavaKILTransformer.java:117)
    at org.kframework.backend.java.symbolic.JavaSymbolicBackend.lastStep(JavaSymbolicBackend.java:61)
    at org.kframework.backend.LastStep.compile(LastStep.java:21)
    at org.kframework.backend.LastStep.compile(LastStep.java:10)
    at org.kframework.compile.utils.CompilerSteps.compile(CompilerSteps.java:44)
    at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:150)
    at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:120)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:40)
    at org.kframework.main.Main.main(Main.java:86)

```

The Java backend doesn't like the following piece of code:

```
     rule #areCompat(ListItem(T:Type) L:List, ListItem(T':Type) L':List)
          => #areCompat(T, T') andBool #areCompat(L, L')
```

This definition can be compiled in Maude backend.

**Comment by dwightguth** [comment]
Unified builtins is merged. Please use master now. I will delete the remote
branch to avoid confusion. Please update your working copy and let us know
if the issue recurs.

**Comment by liyili2** [comment]
The output is different in master branch, but it is still a bug:

```
[Error] Internal: Uncaught exception thrown of type
UnsupportedOperationException.
Please file a bug report at https://github.com/kframework/k/issues
```

**Comment by yilongli** [comment]
fixed in https://github.com/kframework/k/pull/903
