### ISSUE TITLE
Uncaught exception happening when invalid backend is provided to --backend

### ISSUE THREAD

**Issue by osa1** [kframework/k-legacy#938]
```
➜  k git:(master) ✗ kompile --backend wrong
[Error] Internal: Uncaught exception thrown of type ProvisionException.
Please file a bug report at https://github.com/kframework/k/issues
```

I can see why is this happening but I think we should provide a more helpful error message. Maybe listing usable backends or something like that.

For more info, here's `getMessage()` output:

```
Guice provision errors:

1) null returned by binding at org.kframework.kompile.KompileModule.getBackend()
 but parameter 4 of org.kframework.kompile.KompileFrontEnd.<init>() is not @Nullable
  while locating org.kframework.backend.Backend
    for parameter 4 at org.kframework.kompile.KompileFrontEnd.<init>(KompileFrontEnd.java:74)
  while locating org.kframework.kompile.KompileFrontEnd
  while locating org.kframework.main.FrontEnd

2) Error in custom provider, java.lang.NullPointerException
  at org.kframework.kompile.KompileModule.autoinclude(KompileModule.java:70)
  while locating java.lang.Boolean annotated with @org.kframework.backend.Backend$Autoinclude()
    for parameter 1 at org.kframework.parser.generator.OuterParser.<init>(OuterParser.java:44)
  while locating org.kframework.parser.generator.OuterParser
    for parameter 3 at org.kframework.parser.DefinitionLoader.<init>(DefinitionLoader.java:92)
  while locating org.kframework.parser.DefinitionLoader
    for parameter 8 at org.kframework.kompile.KompileFrontEnd.<init>(KompileFrontEnd.java:74)
  while locating org.kframework.kompile.KompileFrontEnd
  while locating org.kframework.main.FrontEnd
Caused by: java.lang.NullPointerException
    at org.kframework.kompile.KompileModule.autoinclude(KompileModule.java:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:104)
    at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
    at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
    at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
    at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
    at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
    at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
    at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
    at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
    at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
    at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
    at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
    at org.kframework.main.Main.main(Main.java:89)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

3) Error in custom provider, java.lang.NullPointerException
  at org.kframework.kompile.KompileModule.autoinclude(KompileModule.java:70)
  while locating java.lang.Boolean annotated with @org.kframework.backend.Backend$Autoinclude()
    for parameter 5 at org.kframework.parser.DefinitionLoader.<init>(DefinitionLoader.java:92)
  while locating org.kframework.parser.DefinitionLoader
    for parameter 8 at org.kframework.kompile.KompileFrontEnd.<init>(KompileFrontEnd.java:74)
  while locating org.kframework.kompile.KompileFrontEnd
  while locating org.kframework.main.FrontEnd
Caused by: java.lang.NullPointerException
    at org.kframework.kompile.KompileModule.autoinclude(KompileModule.java:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:104)
    at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
    at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
    at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
    at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
    at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
    at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
    at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
    at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
    at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
    at org.kframework.main.Main.main(Main.java:89)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

4) Error in custom provider, java.lang.NullPointerException
  at org.kframework.kompile.KompileModule.autoincludedFile(KompileModule.java:75)
  while locating java.lang.String annotated with @org.kframework.backend.Backend$AutoincludedFile()
    for parameter 2 at org.kframework.parser.generator.OuterParser.<init>(OuterParser.java:44)
  while locating org.kframework.parser.generator.OuterParser
    for parameter 3 at org.kframework.parser.DefinitionLoader.<init>(DefinitionLoader.java:92)
  while locating org.kframework.parser.DefinitionLoader
    for parameter 8 at org.kframework.kompile.KompileFrontEnd.<init>(KompileFrontEnd.java:74)
  while locating org.kframework.kompile.KompileFrontEnd
  while locating org.kframework.main.FrontEnd
Caused by: java.lang.NullPointerException
    at org.kframework.kompile.KompileModule.autoincludedFile(KompileModule.java:75)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:104)
    at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
    at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
    at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
    at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
    at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
    at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
    at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
    at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
    at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
    at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
    at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
    at org.kframework.main.Main.main(Main.java:89)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

5) Error in custom provider, java.lang.NullPointerException
  at org.kframework.kompile.KompileModule.documentation(KompileModule.java:80)
  while locating java.lang.Boolean annotated with @org.kframework.backend.Backend$Documentation()
    for parameter 4 at org.kframework.parser.DefinitionLoader.<init>(DefinitionLoader.java:92)
  while locating org.kframework.parser.DefinitionLoader
    for parameter 8 at org.kframework.kompile.KompileFrontEnd.<init>(KompileFrontEnd.java:74)
  while locating org.kframework.kompile.KompileFrontEnd
  while locating org.kframework.main.FrontEnd
Caused by: java.lang.NullPointerException
    at org.kframework.kompile.KompileModule.documentation(KompileModule.java:80)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:104)
    at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
    at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
    at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
    at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
    at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
    at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
    at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
    at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
    at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
    at org.kframework.main.Main.main(Main.java:89)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

5 errors
```

**Comment by dwightguth** [comment]
Omer: can you fix this? it should be an easy fix: just go into
KompileModule and register an error with the kem if it would otherwise
return null from the method getBackend.

**Comment by osa1** [comment]
Sure. Assigned to myself.

**Comment by dwightguth** [comment]
Oh sorry, it's a Guice thing, I forgot that it might not be obvious. You
can inject parameters into @Provides methods. Just add a parameter of type
KExceptionManager to the method.

**Comment by osa1** [comment]
Thanks for the tip. I updated my pull request.
