### ISSUE TITLE
"Unsatisfied link error" while running an SMT unit test on Windows

### ISSUE THREAD

**Issue by osa1** [kframework/k-legacy#953]
```
Running org.kframework.backend.java.symbolic.UseSMTTest
c:\Program Files\Java\jdk1.8.0_20\jre\bin;C:\Windows\Sun\Java\bin;C:\Windows\sys
tem32;C:\Windows;c:\Users\selas_000\bin;.;C:\Program Files (x86)\Git\local\bin;C
:\Program Files (x86)\Git\mingw\bin;C:\Program Files (x86)\Git\bin;c:\Windows\sy
stem32;c:\Windows;c:\Windows\System32\Wbem;c:\Windows\System32\WindowsPowerShell
\v1.0\;C:\Program Files (x86)\Git\cmd;c:\Users\selas_000\apache-ant-1.9.4\bin;c:
\Program Files\Java\jdk1.8.0_20;c:\Program Files\Java\jdk1.8.0_20\bin;c:\Users\s
elas_000\k\bin;c:\Users\selas_000\k\target/lib/native;.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.181 sec <<< FA
ILURE! - in org.kframework.backend.java.symbolic.UseSMTTest
testGetModel(org.kframework.backend.java.symbolic.UseSMTTest)  Time elapsed: 0.1
7 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: C:\Users\selas_000\k\target\lib\native\z3java.dl
l: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1847)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1119)
        at com.microsoft.z3.Native.<clinit>(Native.java:10)
        at com.microsoft.z3.Context.<init>(Context.java:24)
        at org.kframework.backend.java.symbolic.UseSMT.checkSat(UseSMT.java:34)
        at org.kframework.backend.java.symbolic.UseSMTTest.testGetModel(UseSMTTe
st.java:58)
```

Here's a tip for debugging: In this stack trace, first(and only) argument of java.lang.System.loadLibrary(System.java:1119) is `"z3java"`.

**Comment by dwightguth** [comment]
Have you installed the Microsoft Visual C++ 2012 redistributable? It is
mentioned that this is required by Z3 on windows in the readme.

**Comment by osa1** [comment]
I wasn't sure, so I installed again and restarted the system just to make sure. It's still giving same error.

**Comment by dwightguth** [comment]
Okay. Can you use http://www.dependencywalker.com/ to determine what the
library you're missing is?

**Comment by osa1** [comment]
Thanks for the tip. I searched the missing dependencies printed by dependency walker and figured what's missing: http://www.microsoft.com/en-us/download/details.aspx?id=13523

Just to make sure, I removed all other redistributables from my system and only left 2010 version, and it still worked.

Basically we need 2010, not 2012. I'll update the INSTALL file.
